### ISSUE TITLE
An Overview of Compiler Design

### ISSUE THREAD

**Issue by mbaabuones** [section-engineering-education/engineering-education#1272]
### Brief Summary: 
A compiler design is a computer program that transforms a source language (high-level language) into a machine language (low level language) without changing the program meaning. This article provides an overview of this concept. 

### Key Takeaways: 
1. Introduction to language processing system using compiler
2. The architecture of compiler design
3. Phases of a compiler
4. Applications of compiler technology
5. Conclusion

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @mbaabuones. In order to help keep our production pipelines clean, we're asking that students focus on a single article before suggesting new topics. I just approved another topic suggestion from you. Please work through that content first, and you can request for this issue to be reopened once you've submitted a final draft for your other article. Thank you.

**Comment by mbaabuones** [comment]
@ninjaginja . Alright. Thank you.

**Comment by mbaabuones** [comment]
@ninjaginja I already submitted my draft for the other open issue. Please reopen this issue so that I can start working on it.
