### ISSUE TITLE
Working with forms in php

### ISSUE THREAD

**Issue by JudyNduati** [section-engineering-education/engineering-education#1273]
### Brief Summary: 
When you log in into a website or into a mail box, you interact with a form. Forms get input from the user and submit it to the server for processing. In this tutorial, we will learn about how forms work in php and create them.

### Key Takeaways: 
1. An overview of forms
2. When to use forms.
3. How to create a form in php.
4. POST method.
5. GET method
6. GET vs. POST methods.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @JudyNduati. In order to help keep our production pipelines clean, we're asking that students focus on a single article before suggesting new topics. I see that you currently have an issue open without an open PR. Please work through that content first, and you can request for this issue to be reopened once you've submitted a final draft for your other article. Thank you.

**Comment by JudyNduati** [comment]
@ninjaginja please reopen this issue
