### ISSUE TITLE
How Kubernetes Pods Work 

### ISSUE THREAD

**Issue by EKahuha** [section-engineering-education/engineering-education#1280]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.

Kubernetes is quickly becoming the new standard for deploying and managing software in the cloud. Unlike other systems, Kubernetes doesn’t run containers directly; instead, it wraps one or more containers into a higher-level structure called a pod. Any containers in the same pod will share the same resources and local network.

### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?

1. What are Kubernetes Pods?
2. Pod model types
3. What are the benefits of a pod?
4. How does a pod work?
5. Pod-to-Pod Communications in Kubernetes

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @EKahuha . In order to help keep our production pipelines clean, we're asking that students focus on a single article before suggesting new topics. I see that you have several other issues open without associated PRs. Please work through that content first, and you can request for this issue to be reopened once you've worked through drafts of your outstanding topic suggestions. Thank you.

**Comment by EKahuha** [comment]
Good morning @ninjaginja,
Please reopen this issue. I have submitted PRs for all the other previous issues.
