### ISSUE TITLE
User Defined Functions in SQL Server

### ISSUE THREAD

**Issue by rahulbanerjee26** [section-engineering-education/engineering-education#1284]
### Brief Summary: 
Describe the what, why, and how of your content idea in 2-5 sentences.
The article will be a tutorial on working with User Defined Functions in Microsoft SQL Server. It will teach the reader how to create functions and the difference between scalar functions and table-valued functions
### Key Takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
- Difference between scalar functions and table-valued functions
-  How to Create/Invoke/Update and Delete Functions
- How to work with variables and conditional statements inside functions

### References: 
Please list links to any published content/research that you intend to use to support/guide this article. (If none, please indicate 'N/A'.)
N/A

**Comment by ninjaginja** [comment]
good topic @rahulbanerjee26 - approved.

**Comment by ninjaginja** [comment]
Actually, I just noticed that you have a couple other issues open without associated PRs. In order to help keep our production pipelines clean, we're asking that students focus on a single article before suggesting new topics. Please work through that content first, and you can request for this issue to be reopened once you've worked through drafts of your outstanding topic suggestions. Thank you.

**Comment by rahulbanerjee26** [comment]
Hi @ninjaginja 
I have created a PR for Issue #974 and submitted my first draft.
Would be possible to re-open this issue and close Issue #1223 instead? I plan on creating a PR for this issue soon.
Thanks!
