### ISSUE TITLE
Implementing caching in Node.js using redis.

### ISSUE THREAD

**Issue by mwangiKibui** [section-engineering-education/engineering-education#1286]
### Brief Summary: 
Caching refers to temporarily storing of data so that it can be accessed more quickly. Services that process requests fast rely on caching. Redis is an in-memory data structure used as a virtual database during caching. Redis is responsible for storing the data that need to be cached. In this article, we shall walk through the process of implementing caching in a Node.js app using redis.

### Key Takeaways: 
- Understand what caching is and the need of caching.
- Understand how redis works.
- Be able to implement redis in a Node.js application.

### References: 
- https://hackernoon.com/how-to-setup-caching-in-nodejs-using-redis-tq143usy

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @mwangiKibui. In order to help keep our production pipelines clean, we're asking that students focus on a single article before suggesting new topics. I see that you have several other issues open without associated PRs. Please work through that content first, and you can request for this issue to be reopened once you've worked through drafts of your outstanding topic suggestions. Thank you.

**Comment by mwangiKibui** [comment]
@ninjaginja Is it okay that i proceed with this issues's PR.
