### ISSUE TITLE
How to implement material-ui in React

### ISSUE THREAD

**Issue by WanjaMIKE** [section-engineering-education/engineering-education#1287]
### Brief Summary: 
Material-UI library allows developers to create clean and appealing user interfaces. In React, this library saves a lot of development speed and resources since we import widgets rather than building them from scratch. 

### Key Takeaways: 
 - Understand material-ui
 - Know how to add material-ui library to react project
 - Know how to import and use different components from material-ui

### References: 
N/A

**Comment by ninjaginja** [comment]
Thank you for the topic suggestion @WanjaMIKE. In order to help keep our production pipelines clean, we're asking that students focus on a single article before suggesting new topics. I just approved another topic suggestion from you. Please work through that content first, and you can request for this issue to be reopened once you've submitted a final draft for your other article. Thank you.

**Comment by WanjaMIKE** [comment]
@ninjaginja 
Hello
Could you please re-consider this issue. I have other ongoing article. Thanks

**Comment by ninjaginja** [comment]
Thanks @WanjaMIKE  - you may go ahead and proceed with this article :)
