### ISSUE TITLE
Getting Started with Firebase in Android using Kotlin

### ISSUE THREAD

**Issue by carolinemusyoka** [section-engineering-education/engineering-education#1791]
### Proposed title of article
Getting Started with Firebase in Android using Kotlin

### Introduction paragraph(s):

Firebase is Google’s mobile application development platform that helps you build, improve, and grow your app. Nearly all android projects rely on REST service to send, receive data. But you need a back-end, and that is where Google Firebase comes in.  There are tons of services you can use on your app. You just have to create ane project, connect it to your app and you are good to go.

In this tutorial, we shall learn how to work with Realtime Databases and Authentication. 

### Key takeaways: 
- Introduction to Firebase and its services.
- How Firebase’s Realtime Database works
- How to add  Firebase’s Authentication service

### References: 
N/A

**Comment by hectorkambow** [comment]
@carolinemusyoka  

Just want to make sure that there is not much overlap with this existing article 👀 

https://www.section.io/engineering-education/firebase-email-and-password-authentication-in-android-using-kotlin/

**Comment by hectorkambow** [comment]
Bringing in our Kotlin expert 👀 for more input. 👍 

@LinusMuema

**Comment by LinusMuema** [comment]
Hi @hectorkambow & @carolinemusyoka 
This would be a unique article if the writer focused on database operations. In terms of authentication, you can use social auth since there are no articles on that yet. But the databases section has a lot to cover. Even one database option is enough to create a great article. This will prevent an article where the content is just a shallow overview of the technologies.

@hectorkambow you can advise accordingly.

**Comment by carolinemusyoka** [comment]
Thanks @LinusMuema and @hectorkambow for the input.
