### ISSUE TITLE
How to integrate cloud Firestore database in Android using Kotlin

### ISSUE THREAD

**Issue by nonimdiana** [section-engineering-education/engineering-education#2407]
### Proposed title of article

How to integrate cloud Firestore database in Android using Kotlin

### Introduction paragraph (2-3 paragraphs):

Firestore is a cloud-hosted NoSQL database that can be integrated into various platforms(iOS, Android, and web apps) via the respective native  SDKs. It's a reliable database in that it offers flexible data storage structures expressive querying, offline support, improved identity and access management(IAM), and synchronized real-time updates.
In this article, we'll learn how Firestore can be used in an Android app using the Kotlin programming language. Modern apps are expected to run smoothly and offer the best possible user experience and that's exactly what Firestore brings us.

### Key takeaways: 

This article will guide the reader to:
1. Understand why we need a cloud-hosted database.
2. Implement the Firestore database in an Android app.
3. Perform CRUD operations using the developer console.
4. Manage data access rules/permissions.

### References: 
N/A

**Comment by hectorkambow** [comment]
seems like a helpful topic - lets please be sure it add value beyond what is in the official docs and that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure. - approved @nonimdiana 

PS  - we will close the other article topic in the meantime (since we currently allow one article at a time) it can be re-opened after the 1st one is published.

**Comment by nonimdiana** [comment]
Got it @hectorkambow. Thank you for the approval.
