### ISSUE TITLE
Step by step setup and configuration of a home router

### ISSUE THREAD

**Issue by awinomackrine** [section-engineering-education/engineering-education#2766]
### Introduction paragraph (2-3 paragraphs):
A router is a networking device that facilitates sending and receiving of data on a computer in a network. It basically creates communication between a computer and the internet. This is achieved by allowing transmission of data packets between computers on a network.

In this article, we’ll be discussing the functionality of a router in detail and the step by step procedure involved in the set up and configuration of a of a home router.

### Key takeaways: 

1.  The reader will be in a position to understand what a router is in networking environment and its functionality.

2. The reader will be able to learn the step by step physically set up a router in readiness for functionality.

3. The reader will understand the concept behind configuration of routers and how it is achieved.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
Hi, @awinomackrine. Great topic suggestion. It's very original and not been covered previously. Make sure your article is in-depth and covers the concepts in an easy to understand manner. Topic approved.

**Comment by hectorkambow** [comment]
@awinomackrine 

Thank you for submitting this topic - I see that it was approved - but wanted to follow up on it. 

As it does seem a bit out of our typical wheelhouse. 

Not only does it seem like more of a hardware issue - but these types of instructional material (to set up home routers) can be found extensively online. 

Is there a way to extend this topic?? 

Perhaps  use a software to implement it, like Cisco Packet tracer. Maybe create a simple network, configure the router, etc...

Since we are a software (business) comapany we try to focus on software solution more times than not. Otherwise we may need to try for another topic.

cc @louisefindlay23

**Comment by hectorkambow** [comment]
![image](https://user-images.githubusercontent.com/60800358/124782034-20039880-df01-11eb-973e-b4a71f030aaa.png)
