### ISSUE TITLE
How to implement Regular Expressions (Regex) with Java

### ISSUE THREAD

**Issue by olu-damilare** [section-engineering-education/engineering-education#2845]
### Introduction paragraph (2-3 paragraphs):
Regular Expression popularly referred to as regex in the programming field is a specific and detailed combination of characters which form patterns that are thereon used to match the combination of characters in other Strings.

In this article, we will be introduced to the syntax of regex in Java. Learn the implementation of basic regex expressions, interpretation of the metacharacters in regex patterns, essence and benefits of applying regex in string input validations as compared to other approaches, some of the string methods that make use of regex, Java's Pattern and Matcher API's which are some of the other approaches to implementing regex. 

### Key takeaways: 
At the end of the article, the reader should be able to:

- Identify regex metacharacters and what each one represents.
- deduce and interpret the pattern derived from the combination of regex metacharacters.
- determine the appropriate use-cases of regex.

### References: 
- <https://docs.oracle.com/javase/8/docs/api/index.html?java/util/regex/package-summary.html>
- <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions>
- <https://www.w3schools.com/js/js_regexp.asp>
- <https://eloquentjavascript.net/09_regexp.html>

**Comment by hectorkambow** [comment]
@olu-damilare 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
Hey 👀 @john-amiscaray @BrianaNzivu 

You have experience in Java - what do you think about this topic?

**Comment by BrianaNzivu** [comment]
Hey@ahmadmardeni1 👋🏾.
I think it can make a great how to guide article.
Regex is an upcoming trend in object oriented programming especially Java due to its redundant syntax.

I'd advice that he includes a little bit more detail compared to the reference articles linked  (Regex is used in more ways than what most of the articles are displaying).

I'd like to know your thoughts on this @john-amiscaray 🤔

Otherwise, I think it is a great topic. 🚀

**Comment by ahmadmardeni1** [comment]
Thank you!🚀 @BrianaNzivu 

Approved - @olu-damilare - please make sure to include a little bit more detail compared to the reference articles linked (Regex is used in more ways than what most of the articles are displaying) as Briana said.

**Comment by john-amiscaray** [comment]
@ahmadmardeni1 @BrianaNzivu I'm not very familiar with regex so I don't think I can give a good opinion on what can be done differently from the reference articles but I also believe this could be a very useful topic. Regex seems like a pretty powerful tool that can be a little daunting for a beginner because of how weird and different it can look. I feel like done right, this could be a very useful article that could help beginners or even more advanced programmers who just haven't taken the time to learn regex like myself.
