### ISSUE TITLE
Implementation of CI/CD in .NET application Using Shell Executor on GitLab

### ISSUE THREAD

**Issue by djayjames** [section-engineering-education/engineering-education#2890]
### Proposed title of article
Implementation of CI/CD in .NET application Using Shell Executor on GitLab
### Introduction paragraph (2-3 paragraphs):
Shell Executor is a very simple executor which helps to build the solution locally on the machine, where GitLab Runner is installed. However, it also helps to run Bash and Windows PowerShell scripts and Windows Batch is deprecated. There will be a few requirements and path configuration need to set up GitLab Runner in Shell Executor mode and start implementation on it.

In this article, the reader will understand all processes involved in implementing CI and CD in .NET application. 

### Key takeaways:  
The following are the key takeaways:
1. what shell executor is.
2. requirements specifications.
3.  path configuration.
4. Gitlab runner setup.
5.  Windows GitLab Runner Command

### References: 
N/A

**Comment by hectorkambow** [comment]
@djayjames 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by ahmadmardeni1** [comment]
What do you think of this topic? @louisefindlay23  I'm not familiar with the topic.

**Comment by louisefindlay23** [comment]
> What do you think of this topic? @louisefindlay23  I'm not familiar with the topic.

Hi, @ahmadmardeni1. I'm afraid I don't have experience with these areas either. Perhaps someone in the list-of-peer-reviewers doc does?

**Comment by ahmadmardeni1** [comment]
Please let me know your thoughts if you have experience with the topic.

@srishilesh @zolomohan @mbaabuones

**Comment by srishilesh** [comment]
@ahmadmardeni1 Thanks for pinging me.

I don't have experience working with GitLab or .NET. But, based on what I've looked out on the internet, I found very similar articles to this topic:
- [Article on GFG](https://www.geeksforgeeks.org/implementation-of-ci-cd-in-net-application-using-shell-executor-on-gitlab/)
- [Article on Medium](https://medium.com/@gabriel.faraday.barros/gitlab-ci-cd-with-net-framework-39220808b18f)

@djayjames How is your article different from the above two articles?

Also, I find one such similar article at Section - [Implementing CI/CD using GitLab for Java app](https://www.section.io/engineering-education/ci-cd-java-application-using-shell-docker-executor-gitlab/). Probably, @kayere could help us in the approval, since he has already reviewed one such article.

Thanks.

**Comment by mbaabuones** [comment]
> 
> 
> Please let me know your thoughts if you have experience with the topic.
> 
> @srishilesh @zolomohan @mbaabuones

@ahmadmardeni1 Im not familiar with this topic.

**Comment by djayjames** [comment]
Hello @srishilesh and @ahmadmardeni1  I have looked at the topic you suggested.

I have noticed that those articles do not give a beginner the guide and knowledge to create the .gitlab-ci.yml files . For example, the first suggestion you gave, prompt the reader to copy-paste the file which is not beginner-friendly. In my article, I will let the reader know how to create the .YML file step by step. Also I will show the reader  how to install GitLab runners, register that runner, disabling shared runners and then how to auto deploy from GitLab to the server.

**Comment by kayere** [comment]
Good topic @djayjames - approved. **One important note:** please be sure to put your article through a thorough grammar/readability editing review prior to submitting for final approval. This will help increase the likelihood of your article getting published.
