### ISSUE TITLE
Getting started with Visual Basic .NET

### ISSUE THREAD

**Issue by Dyrstiu** [section-engineering-education/engineering-education#2924]
### Introduction paragraph (2-3 paragraphs):
Desktop application development is among the high-growth fields in tech. We use different technologies to create the apps and among them is Visual basic.net.
Visual Basic.net is a multi-paradigm, object-oriented programming language. We implement it in the .NET framework developed by Microsoft. We widely use it in creating desktop applications. In this tutorial, we will look at the most important basic parts of Visual Basic. net step by step.

### Key takeaways: 
1. set up an environment for running Visual Basic.net i.e. Visual Studio
2. Understand visual basic.net syntax
3. write a hello world program

### References: 
N/A

**Comment by hectorkambow** [comment]
@Dyrstiu 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by LinusMuema** [comment]
Hi @Dyrstiu 
This article would be quite helpful but can be easily covered in the official docs by Microsoft. I would suggest you add more content like advantages and other analytical/research data on top of the `getting started` content. Just make sure your content is more original. Also, check on your grammar. You can check the content by @katungi, @john-amiscaray, or @louisefindlay23. They are quite good at grammar.

Otherwise, topic approved :rocket:

**Comment by Dyrstiu** [comment]
Thanks @LinusMuema I will implement your great  points you  have suggested .
