### ISSUE TITLE
Introduction to network ports

### ISSUE THREAD

**Issue by stevekwachie** [section-engineering-education/engineering-education#2930]
### Introduction paragraph (2-3 paragraphs):
A port is a number used to uniquely identify a transaction over a network by specifying both the host, and the service. They are necessary to differentiate between many different IP services, such as web service (HTTP), mail service (SMTP), and file transfer (FTP). The port number serves to uniquely identify that service on a particular host. The default port number for SMTP is 25, so packets of information relating to email are directed here. 
In this article ill be discussing the general concept behind ports and port number. I will also discuss the commonly used port numbers in computer networking. Finally I will discuss at length the relationship between port number and networking protocols and the functionality of the different ports used in networking.

### Key takeaways: 
1. The reader will be able to understand what a network port is and the different types of port numbers used in networking.
2. The reader will be able to  get the role played by port numbers in networking as a field
3. The reader will learn the different functionalities of port numbers in networking

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@stevekwachie 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by hectorkambow** [comment]
@stevekwachie 
Thank you for the topic suggestion.
Upon giving your article an overview it seems that it could be a valubable article for reader(s). 
Although it seems that this information that you intend to cover is already readily available through the documentation or via other blog sites. 

An alternate path might be to create a unique project using network ports to better explain their functions and how they are used in the real world.!

In order to approve this topic - it would need to go beyond the intro level 🚀  

Thank you.

cc @louisefindlay23 & @ahmadmardeni1
