### ISSUE TITLE
broadcasting a Pirate FM Radio Station using a raspberry pi.

### ISSUE THREAD

**Issue by ruphus-muita** [section-engineering-education/engineering-education#2944]
### How-To Guides Overview 
This is a guide to help beginners understand the basic steps that they can use to get started with Raspberry Pi.

### What is the Scope and Purpose of the Guide
A Raspberry Pi is a single-board computer that mainly runs on Linux and can be used to explore Internet of Things. It can be used to learn code, create automation projects among other interesting things. 

Introduce the purpose of your How-To Guide, what functionalities of the proposed software will you be covering? 
To provide a basic guide to the reader in order to know how they can undertake projects using Raspberry Pi to develop useful systems.

### Common Mistakes to Avoid
-Using low-quality cards or cables 
-Selecting the wrong Distro
-Using wrongly specified power supply

**Comment by hectorkambow** [comment]
@ruphus-muita 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it. 🚀

**Comment by louisefindlay23** [comment]
Hi, @ruphus-muita. Great topic suggestion. 

Section are a software company so the EngEd blog has more of a software focus to reflect that.  Please tweak your topic suggestion accordingly to focus more on the software you can develop using a Raspberry Pi rather than its hardware aspects. 

Something like building a Minecraft server, running a bot, broadcasting a Pirate FM Radio Station, building a web server, etc.)

**Comment by ruphus-muita** [comment]
Hi@louisefindlay23 I will go with broadcasting a Pirate FM Radio Station using a raspberry pi. I think that should be appropriate.

**Comment by louisefindlay23** [comment]
Thanks, @ruphus-muita. Great topic. Topic approved.
