### ISSUE TITLE
Beginner's Guide to HashMaps in C++

### ISSUE THREAD

**Issue by param31** [section-engineering-education/engineering-education#2972]
### Proposed title of article
Beginner's Guide to HashMaps in C++

### Introduction paragraph (2-3 paragraphs):
**There are two types of maps in C++**
1. Map
2. Unordered Maps

Maps are ordered and are build using BST, due to which almost most of the functions are of type log(n).
On the other hand, unordered Maps are unordered. They are build using Hash-tables, which makes the time complexity of 0(1) for all the functions.

**Now, What is Hashtable?**

HashTable is a type of container that stores data with key-value combinations. In simple words, it means that every value would have a specific key linked to it.

`<key, value>`

**Implementation of Unordered Maps**

`unordered_map<string, int> map;`

The above statement will declare our unordered map named "map" with the key of "type String" linked to the value of "type Int."

### Key takeaways: 
In this article, we learned about HashMaps and how to implement them. We also solved a coding question to get ourselves more familiarize with HashMaps.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.  @param31

**Comment by hectorkambow** [comment]
@param31 
Sounds like a helpful topic - lets please be sure it add value beyond what is in the official docs and what is covered in other blog sites.
Please be sure to double check that it does not overlap with any existing EngEd articles or incoming topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved

**Comment by hectorkambow** [comment]
Good afternoon @param31 and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. 

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

In order to approve the topic it has to serve value to the larger developer community at large.

An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topic.

That way a developer could see them in action.

Feel free to ping this suggestions to your peers in the EngEd chat to see where we could draw some more substance from the topic - what would take this topic to the next level. 

cc @ahmadmardeni1 @louisefindlay23 @LinusMuema

**Comment by louisefindlay23** [comment]
Hi, @param31. It's been a while since you've submitted your topic suggestion and we haven't received any new information about how you could take your article idea to the next level to benefit our readers. 

We need to close this for to make room in our queue but feel free to reopen it any time when you're ready to notify us of your planned improvements.

Thanks,
Louise - Content Moderator

cc - @hectorkambow
