### ISSUE TITLE
WPF vs WinForms

### ISSUE THREAD

**Issue by Alicewangari** [section-engineering-education/engineering-education#2984]
### Proposed title of article
WPF vs WinForms

### Introduction paragraph (2-3 paragraphs):
The abbreviation W.P.F simply refers to Microsoft’s Windows Presentation Foundation, and WinForms is a simple concatenation of Windows Forms Applications. These are both Microsoft’s Windows Applications Graphical User Interfaces that developers may use to develop Windows desktop applications. This article focuses on describing the major differences between the two approaches towards developing Windows desktop Applications that can serve a better purpose in modern-day systems development.

### Key takeaways: 
1. What is WinForms and WPF
2.  The architecture of each 
3.  The syntax of the two
4.  The file structure of the two
5.  Application behavior differences between the two to create desktop applications

### References: 
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.  @Alicewangari

**Comment by hectorkambow** [comment]
@Alicewangari 
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. 

We typically try to refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large.

An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project possibly with each.

That way a developer could see them in action.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topic.

**Comment by Alicewangari** [comment]
@hectorkambow Thank you for the question. In this article, I intend to walk through the reader major differences between WPF and WinForms with the help of a unique project. I will equip the reader and mostly the beginner how to set up the projects, create controls, use the methods and functions available in .NET and so much more, as it is totally different  from each other.

**Comment by hectorkambow** [comment]
@Alicewangari 
Just and FYI I will be closing this topic form just to help clear up the queue where possible - can be REOPENED at anytime when ready. 👍

**Comment by Alicewangari** [comment]
Hello @hectorkambow, @ahmadmardeni1  , I apologize for delaying this article. I had some personal issues but would you open this topic as it is ready for submission.

**Comment by WanjaMIKE** [comment]
Closed #2984 via #5761
