### ISSUE TITLE
Computer viruses,What they are,how they affect,spread and preventions

### ISSUE THREAD

**Issue by mwanikialex** [section-engineering-education/engineering-education#3028]
A computer virus is a type of malicious software program that is programmed to spread from one computer to another and can make copies of itself. It is loaded onto a user’s computer without the user’s knowledge and performs all types of malicious actions like either damaging or harming the computer system and its data or take control of a computer.

**Comment by hectorkambow** [comment]
@mwanikialex 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@mwanikialex 
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. 

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topic.
That way a developer could see them in action.

**Comment by louisefindlay23** [comment]
Hi, @mwanikialex. It's been a while since you've submitted your topic suggestion and we haven't received any new information about how you could take your article idea to the next level to benefit our readers. 

We need to close this for to make room in our queue but feel free to reopen it any time when you're ready to notify us of your planned improvements.

Thanks,
Louise - Content Moderator

cc - @hectorkambow
