### ISSUE TITLE
Wireless LAN Configurations

### ISSUE THREAD

**Issue by dentonya** [section-engineering-education/engineering-education#3049]
### Proposed title of article
Understanding Wireless LAN Configurations

### Introduction paragraph (2-3 paragraphs):
Technology is growing day by day, which has led to Wireless LAN (WLAN), a type of wireless network commonly used in homes, offices, and campus environments. This network supports people who are on the move, people connecting using computers, laptops, tablets, and smartphones. The move from dial-up to wireless has led to the need for network personnel to configure the devices on the Local Area Network to connect to the internet without using our landlines. This type of connection rapidly adapt to the changing needs and technologies.

 In this article, we will discuss clearly this concept and the reader will understand the WLAN concepts, operations, how to configure it on network devices, troubleshooting WLAN issues together with its merits. 

### Key takeaways: 
The reader will be able to:
- Understand what WLAN connection is.
- How to configure the WLAN on network devices.
- Troubleshoot common WLAN issues.

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@dentonya 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@dentonya 
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. 

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topic.
That way a developer could see them in action.

**Comment by dentonya** [comment]
The topic at hand .is more of software based ...and it will involve how one using any of the network emulators..can configure network devices to not just use the wired network but also wireless network..for sure its different from the rest.
@hectorkambow
