### ISSUE TITLE
digital signatures

### ISSUE THREAD

**Issue by muyagafranklyne** [section-engineering-education/engineering-education#3051]
### Proposed title of article
Understanding digital signatures

### Introduction paragraph (2-3 paragraphs):
Digital signatures play an important role in enforcing integrity and authenticity of messages. It is the digital equivalent of a handwritten signatures.  They are unique to a person and are used to identify user and protect information.
They ensures that a message or document is not tempered,they provide evidence of identity ,transaction or digital messages.A person can also use them to acknowledge informed consent. 
In this article the reader will be able to understand what the digital signatures are and be able to  understand how they work. The benefits associated with digital signatures and how they are used to enforce integrity and authenticity of messages and documents.

### Key takeaways: 
 - What is a digital signature.
 - Benefits of  digital signatures.
 - How digital signatures work

### References: 
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@muyagafranklyne 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@muyagafranklyne 
Good afternoon___ and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. 

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topic.
That way a developer could see them in action.

**Comment by muyagafranklyne** [comment]
This topic will involve how one can be able to make digital signatures using different application and preventing impersonation of digital communication@

**Comment by muyagafranklyne** [comment]
This topic will involve how one can be able to make digital signatures using different application and preventing impersonation of digital communication.
@hectorkambow

**Comment by hectorkambow** [comment]
That may be a bit to vague to approve. 

I do see you have opened another topic suggestion - we will review that one and close this one for now.
