### ISSUE TITLE
Learning Basic JavaScript Modules

### ISSUE THREAD

**Issue by IsaacMuthini** [section-engineering-education/engineering-education#3064]
### Proposed title of article

Learning Basic JavaScript Modules

### Introduction paragraph (2-3 paragraphs):

So the first question either of us can ask is what is a module? Before we get to JavaScript modules am going to take you through what a module is. A module is a function or a group of functions that are similar.  Modules in JavaScript are files containing related code. The modules are used to break code into smaller parts.

### Key takeaways: 
The following are the key concepts that the learner will learn;
-The learner will understand what are modules are
-The learner will understand the use of the following JavaScript modules
     - import module
     - export module
     - default module

### References: 
N/A

**Comment by hectorkambow** [comment]
@IsaacMuthini 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
@IsaacMuthini 
After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. 

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topic.
That way a developer could see them in action.
