### ISSUE TITLE
Requesting Permissions in Android Applications

### ISSUE THREAD

**Issue by JoelKanyi** [section-engineering-education/engineering-education#3103]
Proposed title of article
### Introduction paragraph (2-3 paragraphs):
App permissions help support user privacy by protecting access to the following:
    Restricted data, such as system state and a user's contact information.
    Restricted actions, such as connecting to a paired device and recording audio.

There are two commonly used permission types:
    Install time permissions - automatically granted when your app is installed.
    Runtime permissions - require your app to go a step further and request permission at runtime.

In this article we will explore both.

### Key takeaways: 
- What are Android Permissions
- Install time Permissions
- Runtime Permissions

### References: 
    [Android Documentation] (developer.android.com/)

**Comment by hectorkambow** [comment]
@JoelKanyi 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by JoelKanyi** [comment]
Thank you for your response

**Comment by hectorkambow** [comment]
@JoelKanyi 
Thank you for the topic suggestion
We're really looking for unique/original content, and based on the content provided, it seems that information that you intend to cover is already readily available through the documentation or via many other blog sites. An alternate path might be to create a unique project that showcases this for readers. 

Otherwise - please feel free to suggest an alternate topic to explore. 🚀
