### ISSUE TITLE
Displaying Images With Fresco Library In Android

### ISSUE THREAD

**Issue by brandy-kay** [section-engineering-education/engineering-education#3163]
### Introduction paragraph (2-3 paragraphs):
Fresco is a powerful system for displaying images in Android applications.

Fresco takes care of image loading and displaying, so you don't have to worry about the logic on how the image is loaded. It will load images from:
- Network 
- Local storage
- Local resources
and display a placeholder until the image has arrived. It has two levels of cache; one in memory and another in internal storage.
In this article we will see how to setup Fresco in an android application. 

### Key takeaways: 
- What is Fresco
- How is Fresco different from other image processing libraries (Glide and Picasso)
- Unique features of Fresco
- How to setup fresco in android

### References: 
- https://frescolib.org/

**Comment by hectorkambow** [comment]
@brandy-kay
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by LinusMuema** [comment]
Hi @brandy-kay 
This sounds like a really interesting topic in Android. I however think there is more about fresco you could talk about. Stuff like streaming images and animations. You could add these to provide an in-depth overview of the library as the normal images loading libraries have addressed them. There are articles already on section on coil and glide and adding more specific features of fresco would help your article stand out. 

Otherwise, article approved :rocket:
