### ISSUE TITLE
Getting Started With FastAPI And SQLAlchemy

### ISSUE THREAD

**Issue by dekings44** [section-engineering-education/engineering-education#3369]
*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*
This article will introduce readers to the FastAPI and how to integrate it with SQLAlchemy to develop a real world application and learn how to develop advanced and industry standard RESTful API with FastAPI.

### Proposed title of article
Getting Started With FastAPI And SQLAlchemy

### Introduction paragraph (2-3 paragraphs):
Readers will learn how to get started Python 3.6 FastAPI
Readers will learn how to develop a real world applications with FastAPI
Readers will learn how to integrate SQLAlchemy with FastAPI

### Key takeaways: 
FastAPI
SQLAlchemy

### References: 
https://www.jitsejan.com/creating-simple-rest-api-with-fastapi-and-sqlalchemy

**Comment by WanjaMIKE** [comment]
@dekings44 
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Good afternoon @dekings44 and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
