### ISSUE TITLE
BUILD AND DEPLOY MACHINE LEARNING MODELS WITH TENSOR FLOW

### ISSUE THREAD

**Issue by SIMIYU7Y0** [section-engineering-education/engineering-education#3491]
Introduction
Machine learning is a wide field that might scare newbies and even pose problems to experts. However, Tensor flow makes it easy for any enthusiast or expert build and deploy machine learning models.
Tensor flow is an open source, end to end platform with friendly tools for training and deployment of machine learning models anywhere. The platform is not only for machine learning, but also provides friendly ecosystem for deep learning and scientific computation.
Tensor flow is learned and used anywhere because it's portable and runs on a variety of platforms.

Key takeaway
Understand Tensor flow 
Build and train models using Keras API, a basis for tensor flow and machine learning
training sequential model
saving and loading Keras model

References
https://www.tensorflow.org/
https://developers.google.com/machine-learning/crash-course/first-steps-with-tensorflow/toolkit

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @SIMIYU7Y0 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Good afternoon @SIMIYU7Y0 and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
