### ISSUE TITLE
Python: List Comprehension for beginners

### ISSUE THREAD

**Issue by dollarkid1** [section-engineering-education/engineering-education#3617]
**We** ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner. Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an article to be reviewed and/or published.

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles to go over.

**NOTE: (Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**NOTE: We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

*We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.*

### Proposed title of the article
Your title should be descriptive of the article/tutorial. Be Specific. *Use keyword research to gain your article a higher ranking.*

### Introduction paragraph (2-3 paragraphs):
Please write the Introductory paragraph(s), that would be included in your article. We will use this writing snippet to help us assess overall quality before approval. We're looking for the first 2-3 paragraphs of the article that appropriately summarize what your article will be about.
Take your time and write the content as you would intend to get it published. 

### Key takeaways: 
What are the 3-5 most important things the reader should understand or be able to do after reading this article? Use this area to get your ideas down on the bulk of your article or tutorial.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

### Introduction 
Hi, this is a beginner's guide to List Comprehension in Python.
In this article, we are going to learn what List Comprehension is and how to use them.

List comprehension offers a shorter syntax when you want to create a new list based on the values of an existing list.
List comprehensions can replace many for statements that iterate over existing sequences and create new lists.

### Key takeaways: 
At the end of the article, we should be able to create and know
Create a list with List Comprehension
Mapping in List Comprehension
Filtering: List Comprehension with if clauses 

### References: 
https://www.w3schools.com/python/python_lists_comprehension.asp
https://www.geeksforgeeks.org/python-list-comprehension/
Harvey Deitel intro to Python 2020

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @dollarkid1 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by WanjaMIKE** [comment]
I think `lists in python` is already covered. Will focusing on comprehension make a detailed tutorial?

**Comment by dollarkid1** [comment]
Yes Sir, the article explain everything a beginner needs to know about
comprehension.

**Comment by lalith1403** [comment]
Good afternoon @dollarkid1,  and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.

**Comment by dollarkid1** [comment]
Thanks, I'll check it out.

**Comment by dollarkid1** [comment]
Spring Boot, MongoDB: JWT Authentication with Spring Security for beginners
