### ISSUE TITLE
How to create an NLP application using SpaCy 

### ISSUE THREAD

**Issue by BRIAN721** [section-engineering-education/engineering-education#3633]
### Proposed title of article
How to create an NLP application using SpaCy 

### Introduction paragraph (2-3 paragraphs):
Natural language processing (NLP) is the branch of artificial intelligence or AI—concerned with giving computers the ability to understand the text and spoken words in much the same way human beings can.
In natural language processing, human language is separated into fragments so that the grammatical structure of sentences and the meaning of words can be analyzed and understood in context. This helps computers read and understand spoken or written text in the same way as humans.
In this tutorial, we shall use Spacy to build a text classification model. Text categorization/text classification is the task of assigning predefined categories to documents. It involves Multilabel classification where we assign our dataset different labels to be used for classification.
We will build a model that is able to classify reviews into a positive or negative review
### Key takeaways: 
1. What is NLP.
2. Spacy installation.
3. Removing Stopwords from our dataset.
4. Lemmatizing of the dataset.
5. Building and training model using a machine learning algorithm.

### References: 
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic suggestion. @BRIAN721 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Good afternoon @BRIAN721  and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
