### ISSUE TITLE
Python enum (Enumeration)

### ISSUE THREAD

**Issue by Bonimum** [section-engineering-education/engineering-education#3683]
### Proposed title of article
Python enum (Enumeration)

### Introduction paragraph (2-3 paragraphs):
In Python, `enumeration` is nothing but a set of some symbolic names bound to unique and constant values. This article will provide readers an easy way to learn enum (enumeration) in Python with the help of practical examples. This article will deal with how to implement methods and properties of enumeration with examples.

### Key takeaways: 
By the end of this article the reader should have learned the following:

- Enumeration definition and description
- Enumeration Methods and Properties
- Example to implement methods and properties of enumeration
- Example to implement enumeration
- Print all enumeration values using enum iteration
- Print all enumeration Item in name - value pairs

### References: 
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @Bonimum 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Good afternoon @Bonimum  and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
