### ISSUE TITLE
Queue Introduction and Array Implementation in python

### ISSUE THREAD

**Issue by tanyaogolla** [section-engineering-education/engineering-education#3806]
### Proposed title of article
Queue Introduction and Array Implementation in python

### Introduction paragraph (2-3 paragraphs):
In a queue, new things are added at one end, dubbed the "back," while current items are removed at the other end, often known as the "front." After entering the queue, an element makes its way forward until its turn comes to be removed.
Distinction between a stack and a queue may be seen in how they are removed. In a stack, delete the item that was added most recently; in a queue, remove the item that was added the least recently.

### Key takeaways: 
1. Operations on Queue
2. Applications of Queue
3. Implementation of Queue
4. Complexity Analysis of Queue Operations
### References: 
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @tanyaogolla 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Good afternoon @tanyaogolla and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
