### ISSUE TITLE
Python Dictionary creation and the operations performed on it

### ISSUE THREAD

**Issue by LittleErick** [section-engineering-education/engineering-education#3815]
### Proposed title of article
Python Dictionary creation and the operations performed on it

### Introduction paragraph (2-3 paragraphs):
A dictionary in python is a data structure that allows us to create a key and a value pairs of data. Therefore a dictionary will contain a key which can be argued to be the "input" which is mapped to an "output" which in our case is the value. Some of the operations that can be performed on a dictionary include: fetching items from it, updating and deleting.

### Key takeaways: 
1.Creation of a dictionary in python
2.Operation performed on a dictionary
3.Differences between a dictionary and a list
4.Applications of a dictionary

### References: 
N/A

### Templates to use as guides
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion. @
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Good afternoon @LittleErick  and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
