### ISSUE TITLE
Working with static files in django

### ISSUE THREAD

**Issue by LittleErick** [section-engineering-education/engineering-education#3818]
### Proposed title of article
Working with static files in django

### Introduction paragraph (2-3 paragraphs):
Javascript, CSS, Images, Audio, and Video are examples of static files in django. Django framework requires a developer to store all the static files he/she would like to use in a directory in a given project. The developer would then "inform" the  project that there exist some static files that are going to be utilized by registering them on a file known as settings.py.

### Key takeaways: 
1.Incoperating static files in django app.
2.Registering static apps in the project
3.How to use static files in a HTML template

### References: 
N/A

### Templates to use as guides
N/A

**Comment by lalith1403** [comment]
Good afternoon @LittleErick and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
