### ISSUE TITLE
How to build an atm application using c++ 

### ISSUE THREAD

**Issue by GeoffreyKangu** [section-engineering-education/engineering-education#3827]
### Proposed title of the tutorial
How to build an atm application using c++ 

### Introduction paragraph (2-3 paragraphs):
ATMs, Automated teller machines. These are machines mostly used in banks for day-to-day transactions. Mostly they are used for cash withdrawals. In this case, they hold and know the account details of an account.

In this tutorial, I will be taking you through how to create a simple ATM machine that holds details like a pin number, Name, Account balance, and is able to process a withdrawal if your account balance is enough after entering the correct pin number.

###Key takeaways:
After reading this tutorial, the reader should be able to understand how Automated Teller Machine works.

This tutorial takes the reader through switch statements, c++ access specifiers and therefore the reader should be able to understand them after reading this tutorial and be able to use them.

This tutorial involves the creation of functions and objects in c++ and therefore the reader should be able to understand the concept of objects and be able to use them in a code.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic suggestion. 
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by hectorkambow** [comment]
Good afternoon @GeoffreyKangu and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. 

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀

**Comment by hectorkambow** [comment]
https://www.google.com/search?q=How+to+build+an+atm+application+using+c%2B%2B&source=hp&ei=TH9HYe_LFMrB0PEPjdCI0AU&iflsig=ALs-wAMAAAAAYUeNXDivWvopq7CIUZeZluZ7roEsMgU3&oq=How+to+build+an+atm+application+using+c%2B%2B&gs_lcp=Cgdnd3Mtd2l6EANQrAxYrAxgtwxoAHAAeACAAQCIAQCSAQCYAQCgAQKgAQE&sclient=gws-wiz&ved=0ahUKEwjvoaqx04vzAhXKIDQIHQ0oAloQ4dUDCAk&uact=5
