### ISSUE TITLE
[Machine Learning]Emotion detection in text using sentiment analysis

### ISSUE THREAD

**Issue by charles721** [section-engineering-education/engineering-education#4020]
#### Proposed title of article
[Machine Learning]Emotion detection in text using sentiment analysis

#### Proposed article introduction
Emotion detection is a type of sentiment analysis that detects emotions and feelings in a given text. such as anger, disgust, fear, happiness, sadness, and surprise.  Many emotion detection systems use lexicons (i.e. lists of words and the emotions they convey) or complex machine learning algorithms. 

Recognizing the type of emotion from a text written by a person plays an important role in applications such as chatbots, customer support forums, customer reviews. This helps businesses to know the emotions of customers when using a certain product. Businesses use reviews to know the emotion of a text.
For Example.
- "This product is the best": The emotion is `Happiness.`
- "This is the worst product ever": The emotion is `Anger.
- 
For detecting emotions from the text, we perform a few steps that will start with preparing the data. Then the next step will be tokenization where the textual data will be converted into tokens and from these tokens, we have to identify the emotional words.

In the tutorial, we shall use Scikit-learn to build our emotion detection model. We shall begin with data preparation then build our model that should be able to predict the emotion of a given text.

#### Key takeaways 
1. What is sentiment analysis.
2. What is emotion detection for sentiment analysis.
3. Data preparation.
4. Building an emotion detection model.
5. Making predictions.
#### Article quality
Emotion detection in a text is a unique topic I will explore. I will build a custom model from scratch, I start with processing our dataset with various text. I then use Scikit-learn to build our model, after training I use model to make predictions.  This is a good tutorial for a reader to follow from the beginning and come up with an emotion detection model. This tutorial follows all the stages of machine learning from data preprocessing, text cleaning, building a model, and finally using the model to make preictions.
### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your article for publishing.
Your article has been entered into our queue and should be reviewed (and published pending any changes) as soon as a peer reviewer is finished with the ones in the queue before it. 🚀
Thank you.

**Comment by lalith1403** [comment]
Good afternoon @charles721 and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
