### ISSUE TITLE
[Languages] A dive into File Handling in Python

### ISSUE THREAD

**Issue by munenekelvin** [section-engineering-education/engineering-education#4050]
#### Proposed title of article
[Languages] A dive into File Handling in Python

#### Proposed article introduction
Like many other programming languages, Python offers file management and allows users to read and write files and perform a variety of other file-related tasks. The file handling concept has been extended to various other languages, but the implementation is either complicated or lengthy. However, like most Python principles, this concept is straightforward.

Python processes file differently depending on whether they are text or binary, which is crucial. Each line of code consists of a series of characters that together constitute a text file. A specific character called the EOL or End of Line character, such as the comma, or newline character, ends each line in a file. It signals to the interpreter that the current line has ended and that a new one has begun. 

#### Key takeaways 
By the end of this article, the reader will have understood:
- what file handling is.
- How to Open Files in Python 
- Reading and Writing to Files in Python
- Writing to a File using Python
- Reading From a File in Python
- How to Close Files in Python
- Handling Files in Python
 
#### Article quality
My article will be beginner-friendly, and my code snippets will be short and simple for all audiences to understand easily.
In my article, I will create an actual file the demonstrates how to handle the file in the python programming language, making my article more practice and easier to understand.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by munenekelvin** [comment]
hello @lalith1403 what is the progress of my article suggestion?

**Comment by lalith1403** [comment]
Good afternoon @munenekelvin and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
