### ISSUE TITLE
How to use Single Value Decomposition(SVD) in Principal Component Analysis(PCA) using Matlab

### ISSUE THREAD

**Issue by collince777** [section-engineering-education/engineering-education#4578]
#### Introduction
Single value decomposition(SVD) is a technique that decomposes data into numerous component matrix. This help to expose a lot of important properties of a given data. This method can be thought of as reduction tool where a high dimensional data is reduced into the key features that are necessary for analyzing, understanding and describing the data. It is the fastest process in most dimensionality reduction and machine learning techniques.  

Principal Component Analysis(PCA) is a dimensionality reduction technique that enables you to identify correlations and patterns in a data set so that it can be transformed into a a data set of significantly lower dimension without loss of important  information. The reason why we are looking at the highly correlation features is because highly correlated independent features usually given an output which is biased. In this tutorial, we will see how to How to use Singular Value Decomposition(SVD) in Principal Component Analysis(PCA) using Matlab.
#### Key takeaways 
- How to use SVD to compute the PCA.
- Basic understanding of the PCA and SVD.
- Matlab code to implement this.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by louisefindlay23** [comment]
@collince777, please fill in the article quality section of the topic suggestion form so we can review your topic.

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
