### ISSUE TITLE
Introduction to blockchain

### ISSUE THREAD

**Issue by kurias713** [section-engineering-education/engineering-education#4721]
### Topic Suggestion
Intoduction to Blockchain
#### Proposed article introduction
Blockchain is a gadget that data statistics in a way that makes it complicated or impossible to harm, hack or spoof the gadget. Blockchain is a dynamic virtual transaction block and is sent throughout a network of computer programs at the blockchain. every block within the collection includes a sequence of activities, and each time a brand new activity happens in a blockchain, a report of that buy is added to every participant's e-book. The site that is shared with the aid of many contributors is called Distributed Ledger Technology (DLT). Blockchain is a form of DLT in which transactions are transcribed with a fixed cryptographic signature called a hash.

#### Key takeaways 

1. Components of Blockchain.
2. Major characteristics and applications of Blockchain.
3. Types of Blockchain.
4. Merits and Demerits of Blockchain.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
N/A

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
