### ISSUE TITLE
Understanding socket programming in python

### ISSUE THREAD

**Issue by davismunene** [section-engineering-education/engineering-education#4730]
### Topic Suggestion
Understanding socket programming in python

#### Proposed article introduction
Socket programming is a manner of connecting computer on a network to speak with every other.
Socket programming allows the verbal exchange for sending and receiving information among the socket endpoints through the usage of the code logic.
The sockets can be a computer, which include a server and one or more client devices. In python, socket programming can be put into action by the use of socket library features' help, and Transmission control Protocol(TCP).
TCP is the protocol implemented for this feature via default.

#### Key takeaways 

1. python socket server.
2. python socket client.
3. sending String from one file to another file.

#### Article quality
This article will be unique because I will use a very different approach from what has been published in other blogs. Also the language is simple for the user to grasp the content very well.

#### References
N/A

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
