### ISSUE TITLE
Matching pattern in python with Regex

### ISSUE THREAD

**Issue by Samrosh** [section-engineering-education/engineering-education#4800]
#### Proposed title of article
Matching pattern in python with Regex

#### Proposed article introduction
A Regular Expression (RE) is a particular text string used to describe a search pattern in a programming language. It's great for extracting data from text, such as code, files, logs, spreadsheets, and even documents.

The first thing worth noting when using a Python regular expression is that everything is essentially a character, and we're building patterns to match a certain sequence of characters, commonly known as a string. The letters on your keyboards are called ascii or latin letters, and Unicode is used to match foreign text. It includes all digits, punctuation, and special characters such as $#@! %, and so on.

#### Key takeaways 
By the end of this tutorial, the reader should understand:
- How to create and match regex object 
- Grouping with parentheses 
- Matching multiple groups with pipe as well as specific repetitions with curly brackets
- Optional matching with question mark 
- Matching zero or more with the star as well as one or more with the plus 

#### Article quality
This will be an in depth article explaining all aspects of this concept. To ensure its beginner friendly i will employ easy use of language to enhance understanding. I will also cover the steps of matching regular expressions. 

#### References
N/A

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
