### ISSUE TITLE
NON-FUNGIBLE TOKEN (NFTs)

### ISSUE THREAD

**Issue by Emem-creator** [section-engineering-education/engineering-education#4805]
####Proposed title of the article

[Blockchain] Non-Fungible Token (NFTs)

####Proposed article Introduction

A non-fungible token is a unique and non-interchangeable unit of data saved on a virtual ledger. Being non-fungible simply means it has unique properties so it cannot be interchanged with something else.NFTs could be bought and sold like other valuables which don't have any tangible form of theirs.

NFTs can represent gadgets that include photos, videos, audio, and different sorts of digital documents as specific gadgets, uses blockchain technology to set up proven and public shreds of evidence of ownership.

NFTs arent currencies, however, it makes use of similar blockchain technology that powers cryptocurrencies. In this article, we will learn more about NFTs.The history, its uses, how it works, and more to broaden our knowledge about it.

####Key takeaways

- History of NFT

- How NFT works

- Uses of NFT

- NFT and copyright

- Standards of NFT in blockchain

#### Article quality

My approach to this article is unique because it is broken down into bits and the explanation is straight to the point.

#### References

<https://www.google.com/search?q=Does+nft+has+to+do+with+cryptocurrency&oq=Does+nft+has+to+do+with+cryptocurrency&aqs=chrome..69i57.24151j0j7&sourceid=chrome&ie=UTF-8>

<https://www.google.com/search?q=what+to+know+about+nfts&oq=what+to+know+about+NFT&aqs=chrome.0.0i20i263i512j69i57j0i20i263i512j0i22i30l4.25760j0j7&sourceid=chrome&ie=UTF-8>

###Conclusion

N/A

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
