### ISSUE TITLE
Python JSON (JavaScript Object Notation)

### ISSUE THREAD

**Issue by Ndolotus** [section-engineering-education/engineering-education#4811]
**Topic suggestion**
Python JSON (JavaScript Object Notation)

**Introduction**
Python supports JSON natively, JSON is the text written in JavaScript object notation. 
This is a syntax for storing and exchanging data. JSON is in-built in Python and can be used to work with JSON data.
JSON supports primitive types, like strings and numbers, as well as nested lists and objects.

**Key Takeaways**
Serializing JSON
De-serializing JSON
Conversion from JSON  to Python
Conversion from Python to JSON
Python objects into JSON strings
**Reference**
N/A

**Article quality**
This article will cover in detail JSON methods and give examples of codes and also will avoid ambiguity for ease of user understanding.

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
