### ISSUE TITLE
[Machine learning]Credit Card Fraud Detection in machine learning

### ISSUE THREAD

**Issue by polly-kym** [section-engineering-education/engineering-education#4831]
#### Proposed title of the article
Credit Card Fraud Detection in machine learning
#### Proposed article introduction
Fraud recognition is a bunch of exercises that are taken to keep cash or property from being acquired affectations.
Misrepresentation can be submitted in various ways and in numerous businesses. Most of the identification strategies join an assortment of extortion recognition datasets to frame an associated outline of both substantial and non-legitimate installment information to settle on a choice.
Since the online business installment frameworks came to the present, there have consistently been individuals who will find better approaches to get somebody's funds illicitly. This has turned into a significant issue in the cutting edge period, as all exchanges can undoubtedly be finished online by just entering your Mastercard data.
#### Key takeaways 
1. Identifying misrepresentation naturally.
2. Constant streaming.
3. Less time required for check strategies. 
4. Distinguishing stowed away relationships in information.
#### Article quality
It is an exceptional article in that it verbalizes a significant methodology in the manner extortion is dealt with contrasted with the current articles that don't brief well on all calculations to be followed.
#### References
N/A

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
