### ISSUE TITLE
[Languages] An Introduction to *args and **kwargs in Python

### ISSUE THREAD

**Issue by annwawesh** [section-engineering-education/engineering-education#4838]
### Proposed title of the article
[Languages] An Introduction to *args and **kwargs in Python.

### Proposed article introduction
*args is a short form of arguments. *args that are used to pass positional/non-keyword arguments. With the use of *args in python, you can take any number of arguments in a user-defined function and convert user inputs to an ordered sequence of named *args. In other words, *args means zero or more arguments which are stored in an ordered sequence otherwise known as tuple named *args.
**kwargs is a short form of keyword arguments. **kwargs are used to pass a number of arguments to another function where the options are unknown.
Both *args and **kwargs are functions that build blocks in python that take zero or more arguments and return a value.
Difference: *args permits functions to take any number of positional arguments while **kwargs permits a function to take any number of keywords/named arguments.
Similarity: Both *args and **kwargs allow the passing of multiple arguments or keyword arguments to a function.

### Key takeaways 
**By the end of this tutorial, the reader should be able to understand:**

- What are *args and **kwargs in python.
- What *args and **Kwargs stands for.
- What does single asterisk * and double asterisk ** mean in Python.
- The purpose of *args.
- The purpose of  **kwargs.
- Why *args and **kwargs are needed.
- How *args and **kwargs can be utilized via practical examples.

### Article quality
This tutorial will aid the readers of any level (especially, the python beginners) to understand or make a better understanding of python magic variables such as *args and **kwargs through some basic practical examples that have not yet been highlighted in other published articles.

### References
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
