### ISSUE TITLE
How to get started with classification

### ISSUE THREAD

**Issue by rene-shigolah** [section-engineering-education/engineering-education#4860]
#### Proposed title of article
[Machine Learning] How to get started with classification

#### Proposed article introduction
Classification is a very vast field of study. Even though it comprises a small part of Machine Learning as a whole, it is one of the most important ones.
On the basis of a training set of data that contains observations and whose categories' membership is known, classification is the challenge of finding out which of the subpopulations to which a new observation belongs.

#### Key takeaways 
By the end of this tutorial, the reader will understand:
- What classification entails in machine learning
- Various methods in classification
- How classification is  used
- Block diagrams of generalized classification
- Algorithms which are the various types of classifiers

#### Article quality
I will also focus on covering practical applications of classification. This article will be covered in-depth covering the aspects of this concept. I will employ an easy language to enhance understanding and with this, the article will be beginner-friendly.

#### References
N/A

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
