### ISSUE TITLE
Python data preprocessing for Machine Learning

### ISSUE THREAD

**Issue by Wanyoike-shift** [section-engineering-education/engineering-education#4861]
#### Proposed title of article
[Machine Learning] Python data preprocessing for Machine Learning

#### Proposed article introduction
During pre-processing, we change our data before feeding it into the algorithm.
Insights Preprocessing is a method for transforming unclean data into a usable one. To put it another way, it is impossible to analyze raw data obtained from many sources since it is presented in this raw form.

#### Key takeaways 
By the end of this tutorial, the reader will understand:
- What is data preprocessing and what it entails
- Why the need to use data preprocessing
- Various techniques for data preprocessing

#### Article quality
This will be in-depth since I will ensure coverage of all the aspects that are entailed in this concept. I will ensure practicable examples where relevant.  The reader will appreciate the fact that the language used will be simple enhancing understanding.
More emphasis will be laid on the techniques of data preprocessing.

#### References
N/A

**Comment by Kayere** [comment]
@lalith1403 - could you please check this topic when you get a chance.

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
