### ISSUE TITLE
Various techniques as used in regression

### ISSUE THREAD

**Issue by terry254** [section-engineering-education/engineering-education#4877]
#### Proposed title of article
[Machine Learning] Various techniques as used in regression

#### Proposed article introduction
Economic factors may be analyzed using regression, a statistical method. Coefficient estimation of the independent variable and reliability testing are two of the initial steps. A hypothesis must be formulated before we can design a function based on it.
When the output variable has a real or continuous value, you have a regression issue. Linear regression is the simplest of several models that may be utilized. Using the optimal hyperplane that passes through the locations, it attempts to fit data.

#### Key takeaways 
By the end of this tutorial, the reader will be able to understand:
- What is regression and what it entails
- When to choose regression
- Various types that can be used in regression

#### Article quality
This will be in-depth coverage of this concept. I will provide relevant examples where appropriate and make them practicable. I will provide formulas for the techniques. I believe the article will benefit the reader in that the usage of language will be easy to understand and more beginner-friendly.

#### References
N/A

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
