### ISSUE TITLE
Data abstraction in Python

### ISSUE THREAD

**Issue by Cindy760** [section-engineering-education/engineering-education#4885]
#### Proposed title of article
Data abstraction in Python

#### Proposed article introduction
For the sake of user privacy, data abstraction is utilized to hide core functions of a task from them. User interaction with the function is limited to interacting with the function's basic implementation. That "what function does" is familiar to the user, but they don't understand "how it does."

#### Key takeaways 
By the end of this tutorial, the reader will be able to understand:
- What is entailed in data abstraction in python
- Importance of data abstraction
- Classes of data abstraction in Python
- Data abstract classes functionality

#### Article quality
In this article, we will go over every feature of this subject in details. I venture  to have it more beginner-friendly as I will be manoeuvring throughout this concept to enhance understanding.   I want to use basic language throughout this article because I believe that it is important to convey my message clearly. Whenever possible, I'll give concrete instances to illustrate my points.

#### References
N/A

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
