### ISSUE TITLE
[Python]Analyzing the mnist dataset with a Convolutional Neural Network

### ISSUE THREAD

**Issue by AshaIha** [section-engineering-education/engineering-education#4891]
#### Proposed title of article
Analyzing the mnist dataset with a Convolutional Neural Network
#### Proposed article introduction
Because of its usefulness, CNN has become a prominent model known as Convolutional Neural Network in recent years. Computational tasks at CNN are handled by multilayer perceptrons. In comparison to other image classification techniques, CNN utilizes a very little amount of preprocessing. Rather than relying on hand-crafted filters, a network learns through the use of pre-programmed filters. As a result, CNNs are the most appropriate tool for image processing.
Using the MNISTdataset, you may analyze handwritten text. Using a functional model and a CNN (Convolutional Neural Network), we can get 99.06 percent accuracy. To keep things simple while connecting the layers, a functional model is used.
#### Key takeaways 
- Including all necessary libraries
- Creating the train data and test data
- Importance of using CNN

#### Article quality
The articles in other blogs don't go into great detail about Analyzing the mnist dataset with a Convolutional Neural Network; they just cover the basics. Introduction, Creating the train data and test data, Including all necessary libraries, and the importance of using CNN will all be covered in detail in this article. As a result, the code snippets and content explanations will be easy to understand, making them suitable for novices, intermediates, and experts.
#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Hello @lalith1403, could you please check this topic when you get a chance?

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
