### ISSUE TITLE
[Python]Introduction to Asynchronous Programming in Python

### ISSUE THREAD

**Issue by IQUESTHUB** [section-engineering-education/engineering-education#4894]
#### Proposed title of the article
Introduction to Asynchronous Programming in Python
#### Proposed article introduction
Asynchronous programming is a sort of parallel programming in which the work unit can run independently of the main application thread. When the work is finished, it notifies the main thread of the worker thread's success or failure. There are numerous advantages to utilizing it, including improved application performance and responsiveness.
In asynchronous programming in Python, scheduling is done by the so-called event loop. Developers can specify in their code when tasks voluntarily give up the CPU so that the event loop can schedule another task, that is, cooperative multitasking.
#### Key takeaways 
- Multiple Processes
- Multiple threads
- Coroutines 
- Asynchronous Programming
#### Article quality
Asynchronous programming can be daunting at first, especially for new developers. In this article, I will introduce and discuss the basic concepts of asynchronous programming to help learners get started. 
#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
