### ISSUE TITLE
Introduction To Hierarchical Clustering Algorithm

### ISSUE THREAD

**Issue by EssyH** [section-engineering-education/engineering-education#4917]
#### Proposed article introduction
Unsupervised Machine Learning is used in the hierarchical clustering process. Its goal is to discover natural groupings based on the data's qualities.
By constructing a hierarchy, the hierarchical clustering method seeks to locate nested groups of data. It's analogous to the plant or animal kingdom's biological taxonomy. The hierarchical tree known as a dendrogram is commonly used to describe hierarchical groups.

#### Key takeaways 
Types of hierarchical clustering algorithm
Steps for hierarchical clustering algorithm
Single Linkage and Complete Linkage

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by Kayere** [comment]
Hello @lalith1403 - could you please check this topic when you get a chance?

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
