### ISSUE TITLE
[Machine Learning] Comparing Linear, Logistic and Polynomial Regression in Supervised Learning

### ISSUE THREAD

**Issue by esthermaina36** [section-engineering-education/engineering-education#4918]
### Proposal Submission

 [Machine Learning] Comparing Linear, Logistic and Polynomial Regression in Supervised Learning

#### Proposed article introduction
The most well-known Machine Learning Algorithms that fall under the supervised learning technique are Linear, polynomial and Logistic Regression. Because the algorithms are supervised, they employ a labeled dataset to generate predictions. The biggest distinction is how they are employed. Regression problems are solved using Linear Regression, polynomial regression is used for making predictions, while classification problems are solved using Logistic Regression. 
In this article we'll get to compare the three algorithms in supervised learning.

#### Key takeaways 
1.A detailed introduction to the algorithms and differences between the three algorithms.
2.The math behind the three algorithms & how to implement linear, logistic and polynomial regression models step by step.
3.Know when to chose one of the algorithms for your model over the others.
4..The use of linear, logistic and polynomial regressions.
5.Advantages and disadvantages of each model.
 
#### Article quality
I will use the same dataset to create the three regression models in order to express the difference in their working.

#### References
N/A

**Comment by Kayere** [comment]
Hello @lalith1403 - could you please check this topic when you get a chance?

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
