### ISSUE TITLE
[API]Building a News App API with Django REST framework

### ISSUE THREAD

**Issue by norah254** [section-engineering-education/engineering-education#5040]
Proposed title of article
Building a News App API with Django REST framework and Deploying 

Proposed article introduction
Django REST framework is a flexible and powerful library for building web APIs which allow applications to communicate with each other. It is built on top of the Django framework, a Python web development framework.

In this tutorial, we will learn step by step how to build a news app API using the Django REST framework.

Key takeaways
At the end of this tutorial, the reader should be able to:

1. Understand APIs and their use.
2. Understand CRUD features.
3. Learn how to set up and run Django REST framework.

Article quality
This article covers more in-depth content by providing handy tips for developing a web API using the Django REST framework.

References
N/A

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
