### ISSUE TITLE
Text Analytics using NLTK in Python

### ISSUE THREAD

**Issue by dentonya** [section-engineering-education/engineering-education#5050]
#### Proposed title of article
Text Analytics using NLTK in Python

#### Proposed article introduction
In today's area of the internet and online services, we generate a lot of data at incredible speed and amount. Text communication is one of the most popular forms of day-to-day conversion. We chat, message, tweet, share status, email, write blogs, share opinions and feedback in our daily routines. These activities are generating text in a significant amount, which is unstructured, hence it is essential for corporate and businesses to analyze textual data to understand customer activities and opinions. This makes Text analytics grow at a faster rate than ever before.
In this article, we will focus on text analytics, its applications, and how we implemet it using Natural Language Toolkit(NLTK) in python. The reader will understand various text analysis operations: Tokenization, Normalization, Stemming, Lemmatization, and POS tagging and how we implement them in Python.

#### Key takeaways 
The reader will be able to:
- Understand the concept of text analysis and text Classification.
- Understand the various operations of text analysis using NLTK
- Understand how to implement text analysis using NLTK with Python.

#### Article quality
The article will guide the reader on what text analytics is and how we can implement it using NLPK in python through the various operations.

#### References
N/A

### Conclusion
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
