### ISSUE TITLE
[Machine Learning] Generating and Accessing QR Codes using Python

### ISSUE THREAD

**Issue by lcheop** [section-engineering-education/engineering-education#5057]
### Topic Suggestion
[Machine Learning] Generating and Accessing QR Codes using Python

#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Generating and Accessing QR Codes using Python

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Quick response (QR) codes are a two-dimensional type of barcode, or scannable series, that can store a range of data, including web links, credit card info, contact information, and even freebies. QR codes are used to encode information in a format that only machines can understand.
Python has a wrapper called  [QRCode](https://pypi.org/project/qrcode/) that allow you to generate QR codes. It can generate QR codes for all sorts of data types, i.e., images, texts etc.
We will also leverage the popular OpenCV computer vision library to help us read and access the information on these generated QR code. 

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader will be able to understand:
- How to generate QR codes.
- How to read and access information using a QR code.
- Use the `QRCode` python class to perform advanced tasks such as changing the background and the painting color of the QR code, performing error corrections, and changing QR box and border sizes.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

With the rise of apps like WeChat, AliPay, Mpesa, QR codes are being used to pay for bills and products as it saves a lot of time. I believe our readers need to have an idea how this is done and this tutorial aims to do just that. We will also accomplish this task with only a few lines of code and I believe this would help our readers learn how to build one themselves without writing a lot of boilerplate code.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
- [QR Code ](https://pypi.org/project/qrcode/)
- [OpenCV](https://opencv.org/)
- [Data Encryption With Quick Response (QR) Codes in Android](https://www.section.io/engineering-education/data-encryption-with-qr-codes-in-android/)

**Comment by WanjaMIKE** [comment]
Let's wait until the PR is closed. Thanks

**Comment by lcheop** [comment]
@WanjaMIKE Please reopen this topic issue. My PR has been published.

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
