### ISSUE TITLE
Introduction to API monitoring and performance

### ISSUE THREAD

**Issue by denismwangi** [section-engineering-education/engineering-education#5061]
### Topic Suggestion
Introduction to API monitoring and performance

#### Proposed article introduction
APIs are a powerful tool that helps software engineers to build web and mobile applications by allowing them to communicate with one another. APIs are used to get, send and exchange data from different web services.
API monitoring is the practice of tracking an API's availability, operability,  downtime, and its performance to verify that its available, functional, and within performance limits.

#### Key takeaways 
- Why API monitoring is important
- What is an API monitoring service
- How to minimize API downtime
- How does API monitoring work
- How to choose the right API monitoring service

#### Article quality
This article will give an in-depth lesson on API performance and monitoring, as well as best practices and technologies that may help developers, companies, and teams monitor their mission-critical APIs quickly and affordably.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
