### ISSUE TITLE
 Performing Important Steps of NLP Using Python: A Beginner's Guide 

### ISSUE THREAD

**Issue by Kimenju793** [section-engineering-education/engineering-education#5063]
### Topic Suggestion
 Performing Important Steps of NLP Using Python: A Beginner's Guide 
#### Proposed article introduction
Using Python to Perform NLP's 5 Essential Steps: One of the most commonly used machine learning techniques to analyze text input is Natural Language Processing (NLP). Everywhere we look, we see impressive data visualizations and the application of business intelligence (BI) by many firms. The vast majority of these findings and reports are based on structured data. Unstructured data can nevertheless be useful in some situations. A variety of media could be used, including but not limited to tweets and photographs. These text-based sources of information are the focus of NLP.

Sentiment analysis is an example of NLP. A corporation can examine the sentiments of its customers via the tweets they send about their new products. Even product reviews posted on your website might be examined in the same manner.
#### Key takeaways 
- Advantages of NLP
- Steps involved in NLP
- Challenges of NLP

#### Article quality
Most articles that are already published mostly talk about only the introduction on NLP but in this article, I will be showing more on the important steps of NLP  that ain't covered i.e Modeling your text, Lemmatization and others.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
