### ISSUE TITLE
[Languages] Pickle module of python

### ISSUE THREAD

**Issue by BarasaG** [section-engineering-education/engineering-education#5065]
#### Proposed title of article
Pickle module of Python

#### Proposed article introduction
Sometimes a developer will wish to send some complicated object commands over the network and save the internal state of their objects to disk or database for later use. Because of Python's Pickle Module, the developer can use the serialization process, which is supported by the standard library.

In this article, we'll go over how to serialize and deserialize objects in Python, as well as which package to use for serialization. The Pickle module in Python can be used to serialize several types of objects. We'll also go over how to use the Pickle module to serialize object hierarchies and what hazards a developer can encounter when deserializing an object from an untrusted source.

#### Key takeaways 
1. Protocol Formats of the Pickle Module in Python
2. Types of Pickleable and Unpickleable
3. Compression of the Pickle Objects
#### Article quality
I am focusing in producing an original content that is well understood by our readers.
#### References
N/A

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
