### ISSUE TITLE
[Languages] Git module in Python

### ISSUE THREAD

**Issue by JOHN-2021-WAMBUA** [section-engineering-education/engineering-education#5069]
#### Proposed title of article
Git module in Python

#### Proposed article introduction
The Python language's Git module is a distributed version control system. A version control system is a collection of tools for tracking the history of a group of project files. By teaching the Git version control system, users may simply save the state of files at any time.

The Git module in the Python programming language will be discussed in this article, as well as how users can use it in Python projects. We'll also go through how to use git modules with GitHub so that we can collaborate on large projects with other people.
#### Key takeaways 
1. Basic Usage of Git Module {Which constitutes the following}
Creating a new repository
Add a new file to the Repository
2. The Staging Area of the Git Module
3. What should not add to a Git Repository?

#### Article quality
My focus and intention is to deliver a unique content based on my topic.
#### References
N/A

**Comment by lalith1403** [comment]
These topics are covered widely on the net and documentation of GitPython. Can you share a project-based approach to refine the suggestion? Thank you :)

**Comment by JOHN-2021-WAMBUA** [comment]
The main idea here is to be well conversant with git and how to navigate when add files, creating repositories and also when adding say projects to your git account

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
