### ISSUE TITLE
[Language] Python's unit test framework and TDD (Test-Driven Development)

### ISSUE THREAD

**Issue by AshaIha** [section-engineering-education/engineering-education#5097]
### Topic Suggestion
Python's unit test framework and TDD (Test-Driven Development)

#### Proposed article introduction
Unit testing is a method of testing code in a repeatable and methodical manner. It's a way to see if the code is working as it's supposed to. Testable parts of an application, such as functions and modules are called "units." Python has a built-in unit test library that we will use to conduct our tests.

Each unit of code must be tested during the development process. The developer remedies the problem if the test fails. After passing the unit test, the unit is put through its paces on a test server for continuous integration and delivery. Unit tests fail the server tests if the developer can't figure out what went wrong and what to change. We merge the unit into the main codebase once it passes the server test.

#### Key takeaways 
- Importance of unit test

- Some basic functions of the unit test framework
- Unit tests for square and double functions
#### Article quality
In this lesson, we will learn about Python's unit test framework and TDD. What differs from the other published articles is that in this one I will include unit tests for functions Using Command-Line Interface and an IDE. In addition, I will add a section on Skipping the tests and expected failures. The article will be comprehensive, and the code provided will be simple to grasp.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by AshaIha** [comment]
@lalith1403 
Can you please give this topic a look whenever you are free. Thanks

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.

**Comment by lalith1403** [comment]
Content available at https://www.analyticsvidhya.com/blog/2021/09/unit-test-framework-and-test-driven-development-tdd-in-python/
