### ISSUE TITLE
Getting started with Google Drive API using Python.

### ISSUE THREAD

**Issue by swambui1** [section-engineering-education/engineering-education#5790]
#### Topic suggestion
Getting started with Google Drive API using Python
#### Proposed title of article
Getting started with Google Drive API using Python.
#### Proposed Article introduction
Google Drive empowers us to store information in a distributed storage given by google, you can get to information put away in google cloud anyplace whenever.
Google Drive is an extremely helpful distributed storage, which is easy to utilize. Additionally it's allowed to use as long as you have a google account, they give you 15GB distributed storage. Further more the security of your information is ensured.

#### key takeaways
- Installing necessary libraries and Enabling Google Drive API.
- Transferring documents in Google Drive.
- Looking through documents.
- Downloading documents.
- Posting documents.

#### Article quality
In this article I will take the establishment of essential libraries, Enabling Google drive API utilizing Python.
Additionally, we will apload, download, rundown and search records utilizing python. Am going to use a simple language for the user to easily understand the content.

#### References
- https://developers.google.com/drive/api/v3/about-sdk
- https://developers.google.com/drive/api/v3/quickstart/python

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
