### ISSUE TITLE
On-Time Series Data utilizing Facebook Prophet, an Anomaly Detection Model

### ISSUE THREAD

**Issue by AshaIha** [section-engineering-education/engineering-education#5792]
### Topic Suggestion
On-Time Series Data utilizing Facebook Prophet, an Anomaly Detection Model
#### Proposed article introduction
The collecting of data at regular intervals, such as hourly or weekly, is called a time series. Examples of time-series data include the stock market and online sales figures. It is possible to split and create random samples in time-series data analysis and preprocessing, making it distinct from other types of data analysis.

Time-series data analysis and preparation must be done with care, as each value depends on the preceding one. Detecting patterns in data using various visualization approaches is common, however, anomaly detection with time-series data is handled differently. You will study and practice anomaly detection in time-series data with Facebook Prophet in this post.

#### Key takeaways 
- Anomaly Detection
- Visualizing the Anomalies in Data
- Anomaly and outlier detection

#### Article quality
In this article, we'll learn about On-Time Series Data utilizing Facebook Prophet, an Anomaly Detection Model. The code will be easy to read and understand.
#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
What is on-time series data?

**Comment by AshaIha** [comment]
> What is on-time series data?

It is called time-stamped data, or time-series data. It is a set of data points that are arranged in time order. It's common for these data points to be made up of a series of measurements taken from the same source over a period of time. They are used to seeing how things have changed over time.
@lalith1403

**Comment by AshaIha** [comment]
It's been long. No response yet.

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
