### ISSUE TITLE
[LANGUAGES] Attendance Management System in Django (Python)

### ISSUE THREAD

**Issue by mose-254** [section-engineering-education/engineering-education#5802]
### Topic Suggestion
Attendance Management System in Django

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.
N/A

#### Proposed title of article
Attendance Management System in Django

#### Proposed article introduction
One of the most difficult practice to  perform in higher education learning institutions is to track the daily attendance of the students. Sometimes it can be such a time-consuming and boredom to keep several files of records when it comprises of multiple classes in a single year of study.  
In this tutorial we will come up with a simple solution on recording the attendance of the students in an institution. Through the tutorial, we will be able to save faculty time, have a easily scalable and flexible way of minimizing the number of files in an office . 

#### Key takeaways 
At the end of this tutorial, the reader should be able to:

1. Enhance and develop the skills and logic ideas important in practicing the python programming language.
2. Have an understanding on real-time integration with attendance device types.
3. Have a deep understanding on various forms of recognition in attendance management systems.

#### Article quality
The article is intended to be precise and clear to the point, it will be  illustrated with the lines of codes making it more practical and interesting.

#### References
N/A

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
