### ISSUE TITLE
Working with java synchronization

### ISSUE THREAD

**Issue by gracy20** [section-engineering-education/engineering-education#5936]
#### Proposed title of article
[Languages] Working with java synchronization

#### Proposed article introduction
The synchronization mechanism in java prohibits multiple threads from accessing shared resources. Shared resources include external files, class variables, and database information.
Synchronization is prevalent in multithreaded programming. Synchronized is the keyword that allows your code to run on a single thread at a time without interruption.

#### Key takeaways 
After reading this article, the reader should be able to understand:
-  What is synchronization in java and why do we need it.
- How synchronization works
- How to declare a method as synchronized
- Synchronized method vs Synchronized block 

#### Article quality
This will be an in-depth article covering all the aspects of this concept. It will explain key concepts to readers which is unavailable in the documentations and other platforms. I aim at making it more beginner-friendly simple and easy to understand. More on the coverage will be on the types of synchronization as well as multi-threading with and without synchronization

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by ahmadmardeni1** [comment]
I'm closing this topic-suggestion due to inactivity.
It can be reopened.

**Comment by gracy20** [comment]
Can anyone reopen this for me?

**Comment by hectorkambow** [comment]
@gracy20 
FYI
Just going through your PR & topic form.

We can proceed to get it (reviewed &) published, but it will not be eligible for a payout. (due to the fact that it was closed and re-opened).

Then the fact that the article was re-opened after our transition announcement - that is also a main reason.

The topic form was closed on https://github.com/section-engineering-education/engineering-education/issues/5936#event-6627803039

& I just noticed that you had closed it May 4th.

Thank you - and we are working on getting all the articles reviewed and published asap 🚀
