### ISSUE TITLE
[Languages] Understanding the Tree Data Structure in Python.

### ISSUE THREAD

**Issue by OMONDIELLY** [section-engineering-education/engineering-education#5944]
### Topic Suggestion
[Languages] Understanding the Tree Data Structure in Python.

#### Proposed article introduction
The term tree is commonly used in Computer Science to define how data may be organized. Python, a very rich language with features and data structures, also has the implementation of trees data structure. 
In this article, we will learn about the Tree Data Structure in Python. Later in the article, we will see how to create custom class based trees and how to implement them.

#### Key takeaways 
1. What is a Tree (Data Structure)
2.  Components of a Tree Data Structure
3.  How to Construct a Tree Data Structure
4.  How to traverse a Tree
5.  When to use a Tree Data Structure.
6. Conclusion.  

#### Article quality
Besides learning the basics of Tree Data Structure, the learner will get information about creating custom tree data structure using classes.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
