### ISSUE TITLE
Creating mutable and immutable objects in java

### ISSUE THREAD

**Issue by Wainich21** [section-engineering-education/engineering-education#5945]
#### Proposed title of article
[Languages] Creating mutable and immutable objects in java

#### Proposed article introduction
Java is an object-oriented programming language the objects are at the centre of everything. In Java, the concepts of mutable and immutable are both object-based.  It is possible to iterate through Java objects in two ways: as mutable objects or as immutable objects. Fields in mutable objects can be altered after creation, whereas fields in immutable objects cannot. The state of an immutable object cannot be changed after it has been formed.

#### Key takeaways 
The reader will be able to understand:
-  What are Mutable and Immutable objects
- What differentiates mutable objects from immutable objects
- How we can create mutable classes and immutable classes in Java
- Benefits of mutable and immutable objects in java

#### Article quality
The aim is to make it more interesting and understandable to the reader especially beginners. There will be in-depth coverage of these concepts. I will be pointing out the differences between mutable and immutable objects in java with relevant examples and screenshots. I will employ easy and simple language to enhance understanding.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
