### ISSUE TITLE
How to mask password text in asterisk in C

### ISSUE THREAD

**Issue by RayBrian269** [section-engineering-education/engineering-education#5950]
How to mask password text in an asterisk in C

Password is supposed to be very confidential, and the only way that, this can be done is by masking all the passwords, and in this program, I will show you how to mask passwords using C language. The program will show how user authentication, is made before allowing the user to access the resources. It will be more secure because the username must be valid and also the password must be valid. The password that the user will enter will not be displayed, but instead, the character will simply be replaced by an asterisk.

Key Takeaways
1. How to mask password in C
2. Using asterisks to mask the password
3. Why you should mask all your passwords.

Article Quality
The program will be very beneficial to a beginner because everything will be displayed and the codes are not very complex as compared to other existing programs. On the other hand Masking, passwords prevent snoopers from catching the user’s passwords. It is also a very good security practice.
References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
