### ISSUE TITLE
[Machine Learning] A guide To Machine Learning Cross-Validation and its integration with python

### ISSUE THREAD

**Issue by munenekelvin** [section-engineering-education/engineering-education#5964]
#### Proposed title of article
[Machine Learning] A guide To Machine Learning Cross-Validation and its integration with python

#### Proposed article introduction
With machine learning, there are a lot of interesting things that can be done. It's a field that we can see all around us. In machine learning, you can use data in a different way than you did before. With cross-validation, we train our model using one subset of the data set and then assess it using another subset of the data set that is complimentary to that used to train the model.

In machine learning, we were unable to fit the model to the training data and so cannot predict whether or not the model would perform properly on the actual data. In order to do this, we must ensure that our model extracted the relevant patterns from the data and that it does not generate an excessive amount of noise. In order to do this, we use the cross-validation approach.

#### Key takeaways 
- Understanding what Cross-Validation is and using a real life example.
- Understanding the phases consisted in cross-validation
- Understanding the different techniques of cross-validation.
- Using Python to accomplish Cross-Validation

#### Article quality
The readers stands a lot to gain in this article as it touches essential areas needed for those interested learning how to improve their model performance using Cross Validation. Also,  I will employ easy use of language to enhance understanding. It will be in-depth article explaining all concept. I will explain all code snippet to ensure it's beginners friendly.

#### References
N/A

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
