### ISSUE TITLE
Creating a seven segment display in java using multidimensional array

### ISSUE THREAD

**Issue by Davestrings** [section-engineering-education/engineering-education#5975]
### Topic Suggestion
Creating a seven segment display in java using multidimensional array.

#### Proposed article introduction
This tutorial explains the seven segment display and it real world applications. Learn the basics of working with arrays, understand multi-dimensional array then display different characters base on the seven segments display using multi-dimensional array.

#### Key takeaways 
1. Understand arrays
2.  Understand multi-dimensional array
3. implement the seven segments display using a multi-dimensional array

#### Article quality
This tutorial is aim at beginners. It will employ a practical "by example" approach with a beginner friendly language.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
