### ISSUE TITLE
[Security] Developer's Guide on Passwordless Authentication

### ISSUE THREAD

**Issue by JudyNduati** [section-engineering-education/engineering-education#5976]
### Topic Suggestion
Developer's Guide on Passwordless Authentication

#### Proposed title of article
Developer's Guide on Passwordless Authentication

#### Proposed article introduction
Passwordless authentication refers to any identity verification method that doesn't use a password. In terms of features and implementation, passwordless authentication solutions differ, but they all allow users to log in without creating or remembering a static password. Passwordless logins minimize friction, improve security, and provide a better user experience by removing passwords from the login process.

Passwordless authentication aims to deliver solutions and support use cases that reduce, if not eliminate, the use of passwords. This is a critical goal because passwords have long been associated with usability concerns and security dangers. This article will discuss passwordless authentication, How it works, its implementation, its level of security, and discuss passwordless authentication methods.

#### Key takeaways 
1. An overview of passwordless authentication 
2. How passwordless authentication works
3. Pros and Cons of passwordless authentication
4. Passwordless authentication in practice
5. Passwordless security
6. Passwordless authentication methods
#### Article quality
This is a detailed article about why passwordless authentication might make sense for specific use cases and tips for implementing it using an SMS or OTP service.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
