### ISSUE TITLE
how to make a simple calculator using C

### ISSUE THREAD

**Issue by vin351** [section-engineering-education/engineering-education#5982]
The calculator is an essential tool in helping us to do both simple and complex mathematics. In this program, I will show you how to make a simple calculator using C.  The calculator will help you add, subtract, divide and even multiply two or more numbers. I will guide you through each step of the coding process.
key takeaways
1. Adding two numbers
2. subtracting two numbers
3. multiplying two numbers
4. dividing two numbers
Article Quality.
This calculator will be simple to use and it will be able to carry out about four different operations. 
References
N/A
### Templates to use as guides

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
