### ISSUE TITLE
Genetic Algorithm & their application in data science

### ISSUE THREAD

**Issue by fely545** [section-engineering-education/engineering-education#5985]
### Proposed title of article
Genetic Algorithm & their application in data science
### Proposed article introduction
Today, in this world of information processing, business intelligence and business analytics, are gaining in importance very fast. The three major techniques or groups of algorithms which have gained a lot of visibility in recent times are fuzzy logic, neural networks and genetic algorithms. In this article we will learn what genetic algorithms are, the intuition behind Genetic Algorithms, steps involved in Genetic Algorithm, and finally we will discuss their applications. By end of this article, you will be comfortable applying genetic algorithms and can expect similar benefit on the problems you are working on.

### Key takeaways

> Intuition behind Genetic Algorithms
> Biological Inspiration
> What is Genetic Algorithm?
> Steps Involved in Genetic Algorithm
> Application of Genetic Algorithm

### Article quality
In this article we will gain understanding about what genetic algorithm is and also how to implement it using TPOT library. I will also use simple example that can be easily understood by beginners to explain all about genetic algorithm.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
