### ISSUE TITLE
How To Build APIs in Go using Gin and MongoDb

### ISSUE THREAD

**Issue by Babatunde13** [section-engineering-education/engineering-education#5987]
### Writing samples: 
[Building a React App with TypeScript](https://www.section.io/engineering-education/building-a-react-app-with-typescript/)
[How To Build GraphQL APIs with ExpressJS and Typescript](https://www.section.io/engineering-education/how-to-build-graphql-apis-with-expressjs-and-typescript/)
[Building A Password Manager With React JS, Crypto JS, and Fauna](https://dev.to/bkoiki950/building-a-password-manager-with-react-js-crypto-js-and-fauna-29g9)

### Topic Suggestion
How To Build APIs in Go using Gin and MongoDb

#### Proposed article introduction
Go is a statically typed programming language designed at Google around 2007. One of its main features is the concurrency, which is why most people choose Golang as their language of choice when starting a new project. However, Gin is one of the most popular Golang web framework out there. One of the advantages of using a popular tool is that the tool will have a lot of users and therefore fixing bugs is easier and learning curves will also be high.

#### Key takeaways 
1. What is Gin
2. How to create a simple hello world API in Gin
3. Getting data from a request 
4. Interacting with MongoDb
5. Dealing with file system in Go and Gin

#### Article quality
Most introductory article in Golang and Gin does not explain how to handle files, upload files sent from the client to disk or to an external server etc. This article will be dealing with users uploading files to the server and we will handle the files well as well as validating and ensuring that our application is secure.

#### References
[Gin documentation](https://github.com/gin-gonic/gin)
[MongoDb in Golang Docs](https://docs.mongodb.com/drivers/go/current/)

### Conclusion
This article will serve as an in depth guide to building APIs using Gin and MongoDb.

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
