### ISSUE TITLE
How to transform images in Matlab(Rotate, Scale, Affine and homography)

### ISSUE THREAD

**Issue by peterAdongo** [section-engineering-education/engineering-education#5988]
### Topic Suggestion
How to transform images in Matlab(Rotate, Scale, Affine and homography)

#### Proposed article introduction
Image transformation is a function that takes an image as the input and gives an image as the output. It is applied to an image to convert one domain to another. It helps identify the features that are not identified in the spatial domain. The spatial domain is the normal image space. These processes are mostly applied in the image processing sector. The output in the transformed space can be analyzed and further processed for implementation in the diverse image processing task.

This tutorial will show how to rotate, scale, affine and homograph images in Matlab. These processes can help to analyze images, and they are widely used for image processing.

#### Key takeaways 
-  Background theory of image transformation.
- Importance of image transformation.
- Matlab code for rotation, scaling, affine, and homography.

#### Article quality
This article creates a single code that can perform all these processes.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by ahmadmardeni1** [comment]
Good afternoon and thank you for submitting your topic suggestion.
Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
