### ISSUE TITLE
[Machine Learning] How to use MLBox library to automate and optimize models.

### ISSUE THREAD

**Issue by simonndiritu477** [section-engineering-education/engineering-education#6007]
#### Proposed title of article
[Machine Learning] How to use MLBox library to automate and optimize models.

#### Proposed article introduction
MLBox is a Python library that is used to automate and optimize machine learning models. MLBox has various methods that are used to find an optimal solution when building a model. Through the use of MLBox we will have a high-performing model which is more sophisticated.

MLBox is also used to automate machine learning processes. It automates the processes of preprocessing, model building, and making predictions. This speeds up the development process and saves developers time. MLBox also applies various optimization techniques in choosing the best algorithm to build the model. MLBox will automatically search through all the algorithms and find the best one that will provide the best solution. It also automatically searches for the best parameters for the model.

In this tutorial, we will install MLBox and then create the Pipeline to automate the machine learning processes.  We will also implement the optimization technique to find the best parameters for the model.

#### Key takeaways 
1. What is MLBox?
2. Installing MLBox.
3. Create the Pipeline to automate the machine learning process.
4. Preprocessing the dataset using MLBox.
5. Model optimization using techniques such as Missing Values Encoder, Categorical Values Encoder, Feature Selector and Estimator.

#### Article quality
In this tutorial we will discuss MLBox in detail ad use it to build a model. We will practically implement the Pipeline so that to automate all the MLBox techniques.  This tutorial will also use simple steps and explanations so that the reader can comfortably follow along. In this tutorial, we will also explain explain the techniques Missing Values Encoder, Categorical Values Encoder, Feature Selector and Estimator that MLBox will use to optimize the model. This will enable a reader to grasp all the conecpets related to MLBox.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
