### ISSUE TITLE
[Machine Learning] Using TensorFlow.js and Fingerpose for AI Gesture Recognition

### ISSUE THREAD

**Issue by smkinyan** [section-engineering-education/engineering-education#6053]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Use keyword research to improve your article's SEO.

Using TensorFlow.js and Fingerpose for AI Gesture Recognition

#### Proposed article introduction
*We're looking for the first 2-3 paragraphs of your article that appropriately summarize what your article will be about.*
We will use this writing snippet to help us assess the overall quality before approval so ensure it has been proofread, spellchecked and grammarchecked.

Gesture recognition is a technique that allows you to determine hand gestures from the MediaPipe's [Handpose model](https://github.com/tensorflow/tfjs-models/tree/master/handpose). It could be used to control computer input, to detect sign language, and for active gameplay. 
This tutorial will teach us how to leverage the fingerpose model and tensorflow.js to build an AI gesture recognition app. 

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader should be able to:
- Understand gesture recognition
- How to install the fingerpose model.
- Learn how to detect gestures from different handposes 
- Using the detected gestures, control web applications

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

- [Fingerpose](https://openbase.com/js/fingerpose/documentation)

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
