### ISSUE TITLE
[ LANGUAGES ]  How to create a WinForms File management tool in C #

### ISSUE THREAD

**Issue by Donel254** [section-engineering-education/engineering-education#6054]
#### Proposed title of the article
[ LANGUAGES ]  How to create a WinForms File management tool in C #

#### Proposed article introduction
While working with WinForms  .NET framework as a programmer, it is important to know how to manipulate logical drives, directories and also files. How you represent them in your User Interface is also very important.

In this tutorial, we will create a tool that can select any drive in windows, and also provide a way of navigating through the directories and files while representing them in a tree view. We shall also use a list view to show the contents of any selected directory together with its attributes. We shall also add control to create, rename and delete directories.

#### Key takeaways 
At the end of the tutorial, the reader should be able to understand :
  1. Working with Drives, Directories and Files in WinForms .NET
  2. Working with Tree Views in WinForms
  3. How to represent Files and Directories using Icons
  4. Implementing a list view with  a dynamic source of the data items
  5. Requesting admin permission using a manifest file
  
#### Article quality
I mean to go deeper than most articles and cover the integration of various components such as dropdown, tree view, list view, icons etc. at the end the reader will have learnt more than they expected.
Also what we are building will have the ability of switching in between drives from the users side.

#### References
N/A

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
