### ISSUE TITLE
[Python] How to install new version of Python on Ubuntu 20.04 Operating system

### ISSUE THREAD

**Issue by AndrewOdera** [section-engineering-education/engineering-education#6056]
#### Introduction
Since Ubuntu 20.04 comes with Python 3.8 installed, one can have an interest of changing the version of Python installed in Ubuntu 20.4. In this tutorial you will learn a guide step by step on how to configure and install the latest version Python in your machine. 

#### key take aways
By the end of this tutorial the learner:
-  Will be able to understand some use of sudo commands during installation.
- Be able to change the version of Python installed on Ubuntu 20.04 operating system.
- How to get the new version source file and install.

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
