### ISSUE TITLE
Python One-Liners

### ISSUE THREAD

**Issue by Shee254** [section-engineering-education/engineering-education#6057]
#### Proposed title of article
Python One-Liners

#### Proposed article introduction
A Python one-liner is a snippet of code that solves a problem in a single line.Python One-Liners can help you perform complex tasks with just one line of Python code.In this article, you'll learn many Python one-liners that will help you code like a pro.

#### Key takeaways 
1.Convert String to Integer
2.Reverse a List
3.Generate Random Password
4.Display the Current Date and Time in String Format
5.Prime Number
6HTTP Server
7.Multiple Variable Assignments

#### Article quality
In this article python one liners I will explain in-depth covering most of the content in this concept.I will make use of simple language that a beginner will find it easy to read and understand.
#### References
N/A

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
