### ISSUE TITLE
[Machine Learning] Building Time Series Models using Auto Time-Series Library

### ISSUE THREAD

**Issue by francis966** [section-engineering-education/engineering-education#6068]
#### Proposed title of article
[Machine Learning] Building Time Series Models using Auto Time-Series Library

#### Proposed article introduction
Time series is a type of machine learning model that is used to forecast future events based on previous events that have been observed at regular time intervals.  Times series models can be used to forecast stock market prices, forex prices, pandemic spread, and weather forecasts.

Time series models are used to extract meaningful statistics and other characteristics of the data. This makes the model understand patterns from data and gain useful insights. The model uses the knowledge gained to make forecasts of future values such as a stock. The time series model uses curve fitting techniques to plot the forecast values and come up with a line of best fit.  The plot diagrams are used to represent the predicted values.

In this tutorial, we will collect our dataset from various sources and perform dataset preprocessing.  We will then use the auto series library to build our model. The auto series library will use a machine learning pipeline to automate the time series modeling process.

#### Key takeaways 
1. Types of Time series models.
2. Steps used in time series models.
3. Installing auto time series.
4. Data preprocessing and analysis.
5. Using auto time series functions to build the model.

#### Article quality
This tutorial is unique because it will discuss different types of time series models and libraries. The tutorial will also discuss the steps used in building a time series model before we start using the auto time-series library. This tutorial will explain the various functions used by the auto time-series library to automate the modeling process. It will have detailed and guided steps that are easy for a reader to follow. This is a practical guide.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
