### ISSUE TITLE
How to implement annotation at runtime via reflection in Java

### ISSUE THREAD

**Issue by Bugah-Kondiwa** [section-engineering-education/engineering-education#6186]
#### Proposed title of article
HOW TO IMPLIMENT ANNOTATION AT RUNTIME VIA REFLECTION IN JAVA

#### Proposed article introduction
The Reflection API is part of the standard Java API Library which enable us to explore both the intrinsic nature of the class and intensities without using any explicit new operator at runtime.

This tutorial guides on how to get stated with field's annotation at runtime. we will us reflection API to define class and method information about annotation that are attached to class and methods. We will discus some step by step on how to implement annotation at runtime via reflection. 

#### Key takeaways 
By the end of this tutorial the learner will be able to:
- Defines reflection on annotation
- Check fields that are annotated at a specific time through some codes.
- Modify application using reflection.

#### References
N/A

**Comment by WanjaMIKE** [comment]
How does this topic differ from existing documentation such as http://tutorials.jenkov.com/java-reflection/annotations.html?

**Comment by Bugah-Kondiwa** [comment]
The article has just tackle some types of annotation and there use. In this tutorial, I will show how to obtain annotations of class and methods using reflection via reflection API. Besides we will also discuss how to get an information and read information about annotation that are attached to the class used and methods.

**Comment by Bugah-Kondiwa** [comment]
Any updates @WanjaMIKE ???

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀 


We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀
