### ISSUE TITLE
How to Reshape Data Using Pandas

### ISSUE THREAD

**Issue by Ericksonodiaga** [section-engineering-education/engineering-education#6202]
### Topic Suggestion
How to Reshape Data Using Pandas

#### Proposed title of the article
How to Reshape Data Using Pandas

#### Proposed article introduction
Reshaping data involves changing the way data is organized either by rows or columns. Python has pandas which help us in achieving this. It splits, merges, and changes rows to columns and columns to rows when dealing with datasets. Pandas have different operations and functions for performing this task.

Data reshaping is common in data science when dealing with data analysis,data wrangling, and data mining.

#### Prerequisites
Basic knowledge of Python
Basic knowledge of working with data frames
Using pip

#### Key takeaways 
Understanding data reshaping
Usage of melting method
Stacking and Unstacking data frames
Reshaping and Combining data

#### Article quality
In this article, you will master everything you need to know about data reshaping in data science using Pandas 

#### References
Python official documentation
Pandas documentation

**Comment by WanjaMIKE** [comment]
How does this article differ from https://github.com/section-engineering-education/engineering-education/pull/428/files?

**Comment by Ericksonodiaga** [comment]
The article you have highlighted covers the basics of Pandas, usage of wide to long functions, melting methods, stacking and unstacking, the transformation of columns that are not covered in the article.

**Comment by Ericksonodiaga** [comment]
What is the way foward.Are we working on it or I will have to provide a new one

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀 


We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀
