### ISSUE TITLE
CREATING A SIMPLE BLOCKCHAIN WITH THE NEWLY R6 OBJECTS CLASS IN R

### ISSUE THREAD

**Issue by valentineomondi99** [section-engineering-education/engineering-education#6448]
### Topic Suggestion
CREATING A SIMPLE BLOCKCHAIN WITH THE NEWLY R6 OBJECTS CLASS IN R

#### Proposed title of article
CREATING A SIMPLE BLOCKCHAIN WITH THE NEWLY R6 OBJECTS CLASS IN R

#### Proposed article introduction
R defined as "a free software environment for statistical computing and graphics" according to r -project.org. The  addition of R6 enables the possibility of R to be stretched beyond that meaning. In my tutorial for creating a simple blockchain we will require R6 for creating the block and blockchain objects and open SSL for the SHA-256 hash function which is used for encryption.

My methods are a Genesis block creation method ,an "add block" method", get latest block" method, a chain validation method :checks if the blockchain was altered returns FALSE if it has, TRUE if it has not.

#### Key takeaways 
-The student will have a good insight on how R6 objects class work.
-The student will be able to understand how blockchain technology works
-The student will be able to create a simple blockchain in R using R6 class objects.

#### Article quality
-I am going to create a simple blockchain with R6 which is fairly new.
-The article is beginner friendly as it does not merge with other languages.

#### References
[Creating a simple blockchain in R](http://users.dimi.uniud.it/~massimo.franceschet/HEX0x6C/blockchain/blockchainR.html)

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
