### ISSUE TITLE
[languages] Understanding and implementing cookies in JSP 

### ISSUE THREAD

**Issue by munenekelvin** [section-engineering-education/engineering-education#6462]
#### Proposed title of the article
[languages] Understanding and implementing cookies in JSP 

#### Proposed article introduction
Cookies, which are little text files kept on the client computer, are used to monitor a variety of actions such as login credentials, file transfers, and other similar activities. Cookies may also be seen in debug mode by selecting "Application ->Storage ->Cookies" in web browsers and web-based apps, among other options. In web browsers and web applications, we can see whatever is in the cookies column, and we can delete it. 

When it comes to cookies, we deal with the topic of cookie management in the JSP programming language. A number of cookie handling solutions are provided as presets in JSP, which makes use of HTTP cookies in a transparent manner to support cookies and offers various other features. Interactions between clients and servers, such as those involving requests, make significant use of request and response protocols to facilitate communication. The array of cookies associated with the cookie instance was returned by the get cookies() function. In this tutorial, we will understand the cookies concept in JSP in detail.

#### Key takeaways 
The article will cover
- An introduction to cookies, types, and how they work
- How to create cookies in JSP/ Send cookies to the client
- JSP Cookies API
- Servlet Cookies Methods
- How to handle cookies in JSP (reading and deleting cookies)
- Implementing cookies in JSP

#### Article quality
This article will cover as much to help the reader not only understand the concept of cookies in JSP and its relevance but also how we can implement cookies in JSP.

#### References
N/A

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
