### ISSUE TITLE
Predictive Search and Autocomplete

### ISSUE THREAD

**Issue by Pauline-Mwangi** [section-engineering-education/engineering-education#6481]
### Topic Suggestion
Predictive Search and Autocomplete

#### Proposed title of article
Predictive Search and Autocomplete

#### Proposed article introduction
Predictive search is a useful UX tool for effectively assisting users in discovering the needs they want to find. The goal is to save time for the user by letting them click on the suggestions instead of forcing them to complete their queries. Autocomplete is core functionality for predictive search, and most website users expect search bars to provide it.

This article will help the reader gain a complete understanding of predictive search and how it works. The reader will also be introduced to its best practices and how to implement the autocomplete and typeahead search.

#### Key takeaways 
1. An overview of predictive search and autocomplete.
2. How predictive search and autocomplete works.
3. Introduce use cases for predictive search for autocomplete
4. What is needed to effectively use prediction and autocomplete.
5. Best practices for predictive search and autocomplete.

#### Article quality
Predictive search is a great UX tool for assisting users in finding exactly what they're looking for. This article will explain how predictive search works in detail to the reader. It'll go through common pitfalls in predictive search and how to avoid them and introduce best practices and effective patterns for implementing autocomplete and typeahead search.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
