### ISSUE TITLE
[Languages]Discrete wavelet transform based spread-spectrum watermarking for grayscale images in Matlab

### ISSUE THREAD

**Issue by jumapaul** [section-engineering-education/engineering-education#6600]
### Topic Suggestion
Discrete wavelet transform based spread-spectrum watermarking for grayscale images in Matlab

#### Introduction
The discrete wavelet transform(DWT) implements the wavelet transform using a discrete set of the wavelet scales and translations, obeying some defined rules. In other words, this transform decomposes the signal into a mutually orthogonal set of wavelets. Watermarking is the process of hiding digital information in a carrier signal; the hidden information should, but does not need to, contain a relation to the carrier signal. We can add a watermark to an image using DWT.
This tutorial will look at watermarking grayscale images using Discrete Wavelet Transform (DWT). The proposed watermarking scheme is based on spread spectrum watermarking. It is known to be robust against several watermarking methods. We will see the watermarking algorithms and Matlab code to perform these operations.

#### Key takeaways 
- What is image watermarking?
- Types of watermarking and challenges in image watermarking 
- DWT based spread-spectrum watermarking for grayscale images.
- Watermark embedding and watermark extraction algorithms.
- Performance evaluation parameters.
- MATLAB Code to implement watermarking.
- Result analysis.

#### Article quality
This article covers in detail how to perform the watermarking of the greyscale images.

**Comment by LinusMuema** [comment]
Hi @jumapaul 

It seems this article has been covered a lot by [other scholars](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&as_vis=1&q=Discrete+wavelet+transform+based+spread-spectrum+watermarking+for+grayscale+images+in+Matlab+evaluation+parameters&btnG=&oq=Discrete+wavelet+transform+based+spread-spectrum+watermarking+for+grayscale+images+in+Matlab+evaluation+para) on the internet. Due to this, we cannot move forward with this article. You are welcome to explore other topics.
