### ISSUE TITLE
[Python] Understanding and Implementing Behaviors API to mix-in Behaviors of Base Widgets in Kivy 

### ISSUE THREAD

**Issue by kariuki-boniface** [section-engineering-education/engineering-education#6602]
#### Proposed article introduction
Behaviors Api helps implementing behaviors that can be mixed in with existing base widgets. The idea behind these classes is to encapsulate properties and events associated with certain types of widgets.
Isolating these properties and events in a mixin class allows you to define your own implementation for standard kivy widgets that can act as drop-in replacements. This means you can re-style and re-define widgets as desired without breaking compatibility: as long as they implement the behaviors correctly, they can simply replace the standard widgets.

For example, you can add button capabilities to an image. 

#### Key takeaways 
- Understanding Behaviors Api
- What are behaviors in Kivy
- How to implement widget behaviors to other widgets

#### Article quality
This article will teach a reader on all you need to know so as to implement this in their project. This will be of help to developers looking to build mobile applications using Kivy [Python]

#### References
- Kivy APIs Documentation

**Comment by LinusMuema** [comment]
Hi @kariuki-boniface 

Thanks for submitting your article suggestion. There are some statements in your description that are taken verbatim from the [official documentation](https://kivy.org/doc/stable/api-kivy.uix.behaviors.html). This is a red flag in terms of plagiarism checking.

Also, it seems your article will be covering the same content as the docs. Because of this, we cannot move forward with your article. Feel free to explore other topics.
