### ISSUE TITLE
How to Build Reusable GitHub Actions Workflow to Run Python Tests

### ISSUE THREAD

**Issue by khabdrick** [section-engineering-education/engineering-education#6685]
### Writing sample(s): 
https://www.section.io/engineering-education/authors/muhammed-ali/
#### Proposed title of article
How to Build Reusable GitHub Actions Workflow to Run Python Tests

#### Proposed article introduction
Here the reader will learn how to build reusable GitHub Action workflows to run Unit tests and linting tests for Python code, some details on the limitations, and how far you can go when making a workflow reuseable. Readers will also learn how to use the workflows they have built, in their projects.

ONLY viable topics to pick from:
- Languages

#### Key takeaways 
-  reader will learn how to build reusable GitHub Action workflows to run Unit tests and linting tests
- Learn how to use reusable workflows in projects
- limitations of reuseable workflows

#### Article quality
This article cannot be found on any blog

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentation.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
