### ISSUE TITLE
]Language]How to  generate QRCoder in ASP.NET Core using C# 

### ISSUE THREAD

**Issue by cathy-254** [section-engineering-education/engineering-education#7021]
### Topic Suggestion
How to  generate QRCoder in ASP.NET Core using C# 
 
#### Proposed article introduction
QRCoder is a very popular QR Code implementation library written in C#.  Here I am going to implement the QRCoder library to generate QR Codes in my ASP.NET Core application using C#. ASP.NET is a web application framework developed and marketed by Microsoft to allow programmers to build dynamic web sites. It allows you to use a full featured programming language such as C# or VB.NET to build web applications easily. 
#### Key takeaways 
By the end of the article, the readers will have:
- Installed QRCoder
- Created a QR Code Bitmap image for any text.
- Created a QR Code File for any text and then save these files in the application.
- Read and display all the QR Code File.
#### Article quality
This article will give the learner a step-by-step guide on how to generate QR Code in ASP.NET core using C#. It will also give the learner an overview of both ASP.NET core and C# along with their features.

#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀 


We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 


https://www.google.com/search?q=QR+Code++in+ASP.NET+Core+using+C%23&rlz=1C1CHBF_enUS891US891&ei=ThQyYv_jL-O60PEP0YKkoAI&ved=0ahUKEwj_wvyyisv2AhVjHTQIHVEBCSQQ4dUDCA8&uact=5&oq=QR+Code++in+ASP.NET+Core+using+C%23&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABKBAhGGABQ6whYgx9ghCJoAnABeACAAfkBiAH8BZIBBTUuMS4xmAEAoAEByAEIwAEB&sclient=gws-wiz
