### ISSUE TITLE
How to add a splash screen with animation transitions in android studio

### ISSUE THREAD

**Issue by judywambaki** [section-engineering-education/engineering-education#7027]
### Topic Suggestion
How to add a splash screen with animation transitions in android studio

#### Proposed article introduction
A splash screen is a screen that loads first whenever an application is launched. It can be designed as a motion layout splash screen, onboarding splash screen, or graphics that are animated. It is mostly used to catch the attention of the user by displaying certain information about the application such as a brief title of the application and the logo of the company. The importance of the splash screen is to give room for the application to load the data to the cache ready for the user and sometimes check internet connection for apps that requires internet for operating among others.

In this tutorial, we will be majoring in creating an animated splash screen that has transitions animation of a graphic that occur for a few seconds then the main activity opens. I will be using simple terms to explain every bit of the Kotlin code that beginners can understand and implement in the application they are building.

#### Key takeaways 
- Introduction to the splash screen
- Creating the activities splash and main
- Working with the activities XML's
- Creating animated XML files
- Writing Kotlin code in the splash activity.kt file
- Configuring the manifest file
- Conclusion

#### Article quality
In this article, i will be using other transition features that are not used in other blogs so that we can build a more catchy animation transition in our splash screen. I will also discuss the importance of developers using splash screens in their applications.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀 


We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 


https://www.google.com/search?q=splash+screen+with+animation+transitions+in+android+studio&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
