### ISSUE TITLE
[Android] How to store and fetch data from MySQL database and presenting in android ListView (JSON data format)

### ISSUE THREAD

**Issue by Barasa-Mercyline** [section-engineering-education/engineering-education#7029]
#### Proposed article introduction
Almost every app we use or develop has to store data for one purpose or another. In most cases, developers prefer using firebase as the storage location for their android app users. Since firebase provides small memory allocation for data storage, they limit the number of users of an app since it cannot support many users due to limited storage capacity. 

Also, firebase requires an internet connection which sometimes there might be a network failure. Hence we often prefer storing data in our local machine to accommodate many users of the app since the developer can control the memory storage allocation. 
#### Key takeaways 

-The learner should be able to understand how  to :
-Create a registration form in  Android studio.
-Connect android studio and XAMPP.
-Create database and table in localhost.
-Insert Data into the database table. 
-Create a login form in  Android studio.
-Authenticate a user before logging in.
-Fetch data from MySQL database.
- Display fetched data in form of the JSON format.
- 
#### Article quality
 Unlike other publications, the code will be thoroughly described rather than simply copied and pasted. However, it was built in an unusual way to make it easier to grasp and consume. Also  I will use PHP for storing data at the backend.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. Please feel free to suggest an alternate topic to explore. 🚀 


We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 

https://www.google.com/search?q=store+and+fetch+data+from+MySQL+database+and+presenting+in+android+ListView+(JSON+data+format)&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
