### ISSUE TITLE
Building a simple Casino game using App designer in Matlab

### ISSUE THREAD

**Issue by peterAdongo** [section-engineering-education/engineering-education#7035]
### Topic Suggestion
Building a simple Casino game using App designer in Matlab

### Writing sample(s): 
https://www.section.io/engineering-education/tracking-of-objects-using-the-histogram-based-tracker-in-matlab/

#### Introduction
App Designer is an interactive development environment for designing an app layout and programming its behaviour. It provides a fully integrated version of the Matlab Editor and a large set of interactive UI components. It also offers a grid layout manager to organize your user interface and automatic reflow options to make your app detect and respond to changes in screen size.
The casino is a gambling facility. The game uses slot machines that operate randomly. This is due to a Random Number Generator (RNG) inside each machine, which continuously cycles through millions of numbers. The RNG automatically determines the outcome of a spin when you hit the spin button, making it impossible to predict whether you'll win or lose. In this article, we will see how to construct this App in Matlab.

#### Key takeaways 
- Understanding of the App Designer.
- Features of the App Designer.
- Callback codes for the various components.
- Accessing this App in Matlab

#### Article quality
This article shows the step by step and proper understanding of the process of making this simple App.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 


We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 

https://www.google.com/search?q=Casino+game+using+App+designer+in+Matlab&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
