### ISSUE TITLE
[Security] Fixing File Upload Vulnerabilities on Web Servers with Kali linux

### ISSUE THREAD

**Issue by Adespscientist** [section-engineering-education/engineering-education#7045]
### Topic Suggestion
Fixing file Upload Vulnerabilities

#### Pre-submission advice
The transmission of a file from one computer system to another, generally bigger computer system, is known as uploading. From the perspective of a network user, uploading a file means sending it to another machine that is configured to receive it. People who use bulletin board services (BBS) to share photographs with others submit files to the BBS.
When a web server lets users to upload files to its filesystem without properly validating things like their name, type, contents, or size, it creates file upload vulnerabilities.
Existing important files can thus be replaced, with the. htaccess file implanted to run specified scripts. Inject phishing pages into the web application to make it look bad. Error messages containing vital internal information, such as server-specific paths, may be exposed during file uploads.

#### Key takeaways 
- How to prevent executables in file uploading (php, exe).
- How to check the file type and it File extensions.
- Analyzing the uploaded file itself, recreating and renaming it.

#### Article quality
The most important thing to remember is that you should never enable individuals to submit executables such as php, bash scripts, or exe programs. There's a good chance these files will harm the server. In these lesson we will guide you through the important steps to take in preventing executables and also provide you with in-depth knowledge on these topic

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 


We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 

https://www.google.com/search?q=Fixing+File+Upload+Vulnerabilities+on+Web+Servers+with+Kali+linux&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
