### ISSUE TITLE
[Language] Introduction to File Input and Output in C#

### ISSUE THREAD

**Issue by Tracychelangat** [section-engineering-education/engineering-education#7066]
#### Proposed article introduction
Most of the programs we've written require us to re-enter data every time the program runs. This is due to the fact that once the application is stopped, the data saved in variables and objects in RAM vanishes. The application must be able to save data in order to keep the data between runs.

Data can be saved as a file, which is often saved on the hard drive of a computer. When data is saved in a file, it will remain there even if the program is stopped. The information can be recovered and used at a later time.

Net foundation library allows you to send and receive data from various storage mediums. It allows us to read and write files from and to storage drives, memory, and networks. It also supports a variety of data reading and writing formats, including binary, text, and other encodings. The is the. Net has grouped all of these functionalities under one namespace called "System.IO." This namespace contains a number of classes and functions that allow for seamless data storage and retrieval interaction.

#### Key takeaways 
The learner should be able to understand how to  :
- Write Data to a File.
- Appending Data to a File.
- Specifying the File Location.
- Reading from a File.
- Detecting the end of a File.

#### Article quality
Unlike other publications, the code will be thoroughly described rather than simply copied and pasted. However, it was built in an unusual way to make it easier to grasp and consume by a new beginner.

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀
