### ISSUE TITLE
How to work with Spring Boot and ThymeLeaf

### ISSUE THREAD

**Issue by Erastuskanyatta** [section-engineering-education/engineering-education#7078]
#### Proposed title of article
How to work with Spring Boot and ThymeLeaf

#### Proposed article introduction
`Spring Boot` is a stand-alone application that automates several time-consuming development tasks and eliminates boilerplate code and settings.  It enables developers to generate a standalone JAR file with no XML configuration and an embedded web server for a web application.

`Thymeleaf` is a Java library that is based on the Java Server Pages (JSP) technology.  It can apply a set of transformations to template files to display data and/or text produced by your applications.

In this tutorial, we will look at how to integrate Spring Boot and Thymeleaf and come up with a simple web application.

#### Key takeaways 
1. Develop a simple web application using Spring Boot and Thymeleaf 
2. How to use request parameters with Spring and Thymeleaf.
3. How to change the Thymeleaf Template Directory in Spring Boot.
4. Define some important terminologies.
#### Article quality
This article will help developers learn how to integrate Thymeleaf and Spring boot without any challenge.  The content covered here will be different from that of the other tutorials.

#### References
N/A

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
