### ISSUE TITLE
A look at  mangling/decoration of images using python

### ISSUE THREAD

**Issue by adikutch** [section-engineering-education/engineering-education#7081]
#### Proposed title of article
A look at  magling/decoration of images using python

#### Proposed article introduction
In many modern programming languages, name decorating is a strategy for resolving issues generated by the necessity to resolve unique names for programming things.

In this article, we'll look at the name mangling process in Python and how we may use it with various methods. And it will be made possible through the implementation of several examples

#### Key takeaways 
1. Name mangling using method overriding
2. Accessing name mangled variables
3. Name Mangling in Python

#### Article quality
The quality of the content in this article will be well understood and easy to follow for our learners.

#### References
N/A

**Comment by lalith1403** [comment]
Errors in the issue.

**Comment by adikutch** [comment]
@lalith1403 Where may be the problem

**Comment by adikutch** [comment]
mangling

**Comment by hectorkambow** [comment]
👀 

Not sure what the issue was. Please address before continuing. 

Sounds like a helpful topic - **lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (We're really looking for unique/original content. EngEd articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).**
 
Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
 
>ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
 
Please be sure to double check that it **does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure.** 
Please reference any relevant EngEd articles in yours. - Approved


https://www.google.com/search?q=A+look+at+mangling%2Fdecoration+of+images+using+python&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
