### ISSUE TITLE
How to sort a table in ascending or descending order in React

### ISSUE THREAD

**Issue by twish-254** [section-engineering-education/engineering-education#7083]
#### Proposed title of article
How to sort a table in ascending or descending order in React

#### Proposed article introduction
For data management, we may wish to include sorting capabilities while creating a table for our application.

If you want a basic table with complete flexibility, you may not want to use tools like React Table, which allows us to add sorting features and more.

We'll learn how to build a sortable table from the ground up in React in this tutorial. By clicking on the table headings, we will arrange the rows in ascending or descending order.

The JavaScript `sort()` method will also be covered, as well as some fundamental React concepts. We will have a sortable table at the end of this tutorial.

#### Key takeaways 
- Developing a table in React
- Getting and rendering the table
- Sorting the React table data

#### Article quality
I recommend this tutorial since most blogs that I've read gloss over information that is already included in the documentation. Using `localeCompare()` with the `sort()` function and sorting by number and date (not mentioning all here) have not been well described by most of them. There will be no other article like this one, thus it is important that this one stays true to the spirit of the community while also adding something new.

#### References
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀
