### ISSUE TITLE
How to Trigger a Function when Scrolling to an Element in React Intersection Observer

### ISSUE THREAD

**Issue by Titusian72** [section-engineering-education/engineering-education#7084]
#### Proposed title of article
How to Trigger a Function when Scrolling to an Element in React Intersection Observer

#### Proposed article introduction
You can detect if someone scrolled to an element by adding an event listener that fires a function any time someone scrolls. But that alone doesn’t give us a lot to work with, still needing a way to figure out where on the page we’re at, and it can end up eating precious resources without complicated throttling or debouncing problems.

Instead, we can use the intersection observer which provides a way to asynchronously observe changes in the intersection (overlapping) of elements. This can be in relation to other elements, or the viewport. In this article, we’ll take a look at a few demos and discuss the relevance that Intersection Observer will play in the future for web developers. 

#### Key takeaways 
1.  Creating a new Next.js app from a demo starter
2. Accessing DOM node Ref in React with UseRef and UseState
3. Using intersection observer to detect when HTML element is in view
4. Storing visibility status of an element with UseState
5. Using the React intersection Observer hook to detect visibility
6. Triggering a CSS element when an element is in view

#### Article quality
This article will give the learner a step-by-step guide on how to  Trigger a Function when Scrolling to an Element in React Intersection Observer and an overview of  Intersection Observer  along with its features.

#### References
N/A

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
