### ISSUE TITLE
 [Networking] How to gain access to full remote desktop environment of raspberry pi using VNC and SSH

### ISSUE THREAD

**Issue by ronobenard** [section-engineering-education/engineering-education#7103]
#### Proposed title of article
 [Networking] How to gain access to full remote desktop environment of raspberry pi using VNC and SSH

#### Proposed article introduction
The Raspberry Pi is the most widely used computer in the disciplines of IoT and Arduino, as well as in general areas of automation, such as programming RFID/NFC devices, PWM servor motors, and sensors such as PIR motor sensors, Ultrasonic Distance sensors, and touch sensors. As a result, knowing how to connect your Pi to your desktop environment remotely via network is critical for easier and more efficient automation programming.

I'd like to walk you through how to set up remote access to the desktop environment of a Raspberry Pi using VNC and SSH in this article.

#### Key takeaways 
- The reader will understand some fundermental linux commands
- Understanding the SSH
- Do some raspi configuration for communication protocols, display and localization.
- Accessing Pi's remote desktop environment using SSH and VNC viewer
- Modify Pi's default credentials

#### Article quality
The article will be full and detailed, with plenty of examples. I will deliver high-quality, error-free, original, and non-plagiarized work. In addition, I make every effort to present my contribution in a professional manner.

#### References
N/A

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
