### ISSUE TITLE
Mediapipe library for pose detection

### ISSUE THREAD

**Issue by puritymutunga** [section-engineering-education/engineering-education#7112]
### Topic Suggestion
Mediapipe library for pose detection

#### Proposed article introduction
MediaPipe is an open-source framework developed by Google for the purpose of media processing. It is cross-platform, or we could say it is platform-friendly, depending on your perspective. It runs on Android, iOS, the web, and YouTube servers, which is what cross-platform means: it can run on any device, on any platform.
In its most basic form, MediaPipe is a framework for Computer Vision and Deep Learning that allows you to create perception pipelines for your data. For the time being, all you need to know is that perception pipelines are any type of audio, video, or time-series data that captures the process while it is in the pipelining zone.
In this article, we will demonstrate how to perform pose detection using Mediapipe and OpenCV software. We will go into greater detail about all of the processes and code for the same later in the article, but first, let's take a look at some real-world examples of how pose detection is used.

#### Key takeaways 

-  Introduction to Mediapipe library
-  Importing the necessary libraries
-  Initializing the pose detection model
-  Implementing the pose detection
- Application areas of pose detection

#### Article quality
The article will be a complete guide on how to import libraries used in MediaPipe which are used to detect pose and after that we also show how to use the library to detect a pose.

#### References
N/A

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
