### ISSUE TITLE
Python Audio Analysis Using Pydub

### ISSUE THREAD

**Issue by Joesongoma** [section-engineering-education/engineering-education#7114]
#### Proposed article introduction
In the recent world, audio has been  the nerve centre of communication. This means means that without audio, communication will not be easily effected and this will mean that the message is not conveyed to the receiver.

`Pydub` is a python module that works with audio files.  This implies that we can use `pydub` to analyze data in python. We can merge, play, split, and edit an audio file with this library, specifically a `.wav` file. We will also have a look at dimensionality reduction techniques and see how it is applied and works in the pydub library.

In this tutorial, we will be looking at how we can analyse audio data in Python using pydub, a python library` to analyse an audio file and be able to edit, split, or merge different source files to one.

#### Key takeaways 
From this tutorial:
- the reader will gain the concept of pydub library and how to work with it.
- since this is a machine learning tutorial, this tutorial will give the reader the concept of machine learning.
- the reader will also get concept of dimensionality reduction techniques from this tutorial.

#### Article quality
This article will be taking the reader through a step by step concept of audio analysis and using the pydub library and the concept of dimensionality reduction techniques from this tutorial. This will make the reader have a better understanding of this article as compared from other sites.

#### References
N/A

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
