### ISSUE TITLE
[Android]Working with validation of an email address and password client side, by using regular expressions

### ISSUE THREAD

**Issue by kamothosimon** [section-engineering-education/engineering-education#7117]
#### Proposed title of article
Working with validation of an email address and password client side, by using regular expressions

#### Proposed article introduction
We will learn, how to validate an email address and password client side, by using regular expressions (regex).
This way we can check, if the inserted email address is formed like an email address, and if the password contains certain characters, like upper and lower case letters, digits and special characters.
For this we will use a class, with which we can compile a regex from a string and then use the matcher method to compare it with the input.

#### Key takeaways 
1.Creating a class that is going to handle regular expression
2.How to validate the email
3.Checking  if the inserted email address is formed like an email address

#### Article quality
Its gives a complete guide step by guideline of validation of email and password

#### References
N/A

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
