### ISSUE TITLE
Implementing loading animation on websites using Tailwindcss

### ISSUE THREAD

**Issue by mwangangi1998** [section-engineering-education/engineering-education#7128]
#### Proposed article introduction.

Tailwind CSS one of the fast growing utility -first CSS framework .Tailwind CSS is easier to use and easy to impliment  as long as one as basic understanding of CSS.
In my article i will be stressing out how to create a preloader or animation in tailwind CSS in web pages as the content is being loaded to avoid delay and boring .

#### Key takeaways 

- What is tailwind CSS
- How to install and configure Tailwind CSS in HTML.
- How Tailwind CSS relates with CSS .
- What is HTML?
- Installing and customization of tailwindcss in a project.
- 
#### Article quality
I will be using a practicals to show how you can use tailwind  CSS to create animations on web page to avoid delays and automate loading time .

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 


We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀
