### ISSUE TITLE
Pytorch Sentiment Analysis with Pretrained Transformers

### ISSUE THREAD

**Issue by AshaIha** [section-engineering-education/engineering-education#7140]
### Topic Suggestion
Pytorch Sentiment Analysis with Pretrained Transformers
#### Proposed article introduction
Since the birth of Natural Language Processing, sentiment analysis has been a popular task (NLP). Subtask or application of text categorization, feelings or subjective information from distinct texts are extracted and identified in this case.

The Transformers library from Huggingface can be used to implement sentiment analysis rapidly and effectively. To save time, we'll be relying on pre-tuned transformers rather than building our own.
#### Key takeaways 
- Build Sentiment Analysis Pipeline
- Input Text
- Perform Semantic Analysis

#### Article quality
Using transformers library from Huggingface, we will implement sentiment analysis rapidly and effectively. To save time, we'll be relying on pre-tuned transformers rather than building our own. The code will be simple and easy to grasp.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 

https://www.google.com/search?q=Pytorch+Sentiment+Analysis+with+Pretrained+Transformers&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
