### ISSUE TITLE
Localization in Flutter with a BuildContext extension

### ISSUE THREAD

**Issue by vincentkims49** [section-engineering-education/engineering-education#7141]
### Topic Suggestion
Localization in Flutter with a BuildContext extension
#### Proposed article introduction
If you want to make your Flutter app available to people all over the world, you'll have to make it so that it can speak different languages at some point. The good news is that Flutter already comes with useful APIs that make this task easier, as well as detailed documentation that explains how to do it in more depth.  This means that we can use the new skeleton app template that comes with ARB files already set up, so we don't have to set everything up by hand.

In this post, we'll look at the skeleton app template and make some changes. The end result will be a simple app template that uses a BuildContext extension to make it easy to find localized strings in our widgets.
#### Key takeaways 
- Accessing AppLocalizations
- BuildContext extension
- Skeleton App Template
#### Article quality
We'll look at the skeleton app template and make some changes to. The end result will be a simple app template that uses a BuildContext extension to make it easy to find localized strings in our widgets. The code snippets will be simple and easy to grasp.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 

https://www.google.com/search?q=Localization+in+Flutter+with+a+BuildContext+extension&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
