### ISSUE TITLE
Theano with GPU for Deep Neural Networks on python with OSX

### ISSUE THREAD

**Issue by Geofreytech** [section-engineering-education/engineering-education#7145]
### Topic Suggestion
Theano with GPU for Deep Neural Networks on python with OSX

#### Proposed article introduction

Theano is a Python library that lets you write, optimize, and evaluate math expressions that use multi-dimensional arrays quickly. Theano is also the practical process of putting together a neural network in Python, which is how it works (using Theano package).

Codes that are more efficient, faster, and save space in our machines are going to be made with theano in this piece.

#### Key takeaways 
- Theano Overview
- Implementing Simple expressions
- Theano Variable Types
-  Theano Functions
- Modeling a Single Neuron
- Modeling a Two-Layer Networks

#### Article quality
We're going to write this article utilizing theano packages. Giving us high-level models with faster-running scripts that take up less space on our Computers. Additionally, the code samples will be straightforward to comprehend.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 

https://www.google.com/search?q=Theano+with+GPU+for+Deep+Neural+Networks+on+python+with+OSX&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
