### ISSUE TITLE
[Security] Introduction to security threats of Cloud Computing and possible solutions

### ISSUE THREAD

**Issue by Greyhat23** [section-engineering-education/engineering-education#7150]
### Topic Suggestion
Introduction to security threats of Cloud Computing and possible solutions

#### Proposed title of article
Introduction to security threats of Cloud Computing and possible solutions

#### Proposed article introduction
This article will try to handle the shared security responsibility,  infrastructure security, and the security services in the cloud. It will then major on the security challenges that are rampant in cloud computing and the security technical architecture of the cloud.

It will finally outline some of the cloud security services, their functions and application, and also, the security solution design for cloud computing.

#### Key takeaways
The learner should learn the:
1. Cloud security architecture.
2. Key security threats.
3. Security solutions to typical cloud security threats.

#### Article quality
This article will elaborate the cloud computing security architecture and the various services whose security is critical in the cloud.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 

https://www.google.com/search?q=security+threats+of+Cloud+Computing&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
