### ISSUE TITLE
[Networking] What is DNS?

### ISSUE THREAD

**Issue by JGatura421** [section-engineering-education/engineering-education#7154]
### Proposed title of the article.

What is DNS? Domain Name System.

Proposed article introduction.

Every great country has a list of founding fathers. The internet has a list of founding fathers.
The DNS is one of the founding fathers. Most people don't realize the use of it.
The Domain Name System is (DNS) is the internet phone book. (comprises of numbers) Just like a phone book maps a person's phone number the DNS is used for mapping internet protocol  (IP) addresses. The IP address is the number that computers use to communicate with each other. The human can only access online information through domain names. A good example, like apple.com .mi.com or dell.com.
When a user types a domain name on a World Wide Web (www)browser, an immediate conversation occurs of what the user types on their web browser into an IP address required to locate the domain.
_(apple.com)_
 The big question does arise, what DNS? How does it work?

**### Key takeaways**
At the end of this article, The user will understand:

- what is DNS?
- How does DNS work.
-  Types of DNS servers involved in loading a webpage.
-  What is a DNS Resolver.
- The main difference between the recursive and authoritative DNS resolver.
- The steps of DNS  lookup.
- What is DNS caching?

### **Article quality**
The article covers broadly the DNS (Domain Name System) by further explaining its methodology of performance.

### **reference**
N/A

**Comment by WanjaMIKE** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀
