### ISSUE TITLE
Managing KVM Virtual Environment in Linux using Command Line Tools

### ISSUE THREAD

**Issue by Ken-muriithi** [section-engineering-education/engineering-education#7156]
#### Proposed title of article
Managing KVM Virtual Environment in Linux using Command Line Tools

#### Proposed article introduction
KVM (Kernel-based Virtual Machine) is free, open-source virtualization software for Linux. It consists of a kernel module (kvm.ko) and a processor-specific module.

KVM provides two techniques to create virtual machines. You may use the virt-manager program, an X11 server with a GUI for building virtual machines. You may also use the command line to construct a virtual machine by specifying parameters.

#### Key takeaways 
The reader will be able to understand:
- What is KVM with what it entails
- The configuration of the storage pool
- How to do configuration of the storage volumes/disk images
- How to create virtual machines

#### Article quality
I will enhance the explanation of this concept with proper steps and output screenshots. This tutorial will be in-depth covering all the aspects of this concept and further different ways related to this concept. This will be more beginner-friendly.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 

https://www.google.com/search?q=KVM+Virtual+Environment+in+Linux+using+Command+Line+Tools&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
