### ISSUE TITLE
[Artificial Intelligence] How a Modern Pager can help improve Healthcare Services in Hospitals.

### ISSUE THREAD

**Issue by Eric-mburu** [section-engineering-education/engineering-education#7157]
###Topic Suggestion
[Artificial Intelligence] How a Modern Pager can help improve Healthcare Services in Hospitals.

#### Proposed title of article
[Artificial Intelligence] How a Modern Pager can help improve Healthcare Services in Hospitals. 

#### Proposed article introduction
*Healthcare facilities have experienced difficulty in managing overcrowding in the waiting room as more patients continue to seek medical attention due to COVID-19 infection. This article will show how modern pager can solve this problem by reducing congestion within the hospital. This device will also help minimizing the spread of COVID-19 and other contagious diseases. Finally, the article will show some of the limitations of using this device.*

#### Key takeaways 
At the end of this article, the learner will understand:
1.	How a pager works
2.	What is a paging network?
3.	How does modern paging differ from the earlier one
4.	Benefits of pager systems in healthcare facilities
5.	Limitations of pager systems 

#### Article quality
This article will elaborate more on how a pager works and how it has proved helpful in healthcare facilities.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
https://www.google.com/search?q=Modern+Pager+can+help+improve+Healthcare+Services+in+Hospitals&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
