### ISSUE TITLE
Multiple Documents Operations in MongoDB

### ISSUE THREAD

**Issue by beatynyambura** [section-engineering-education/engineering-education#7159]
#### Proposed title of article
How to Operate Multiple Documents CRUD Operations in MongoDB

#### Proposed article introduction
MongoDB is a persistent document-oriented database used to store and process data in the form of documents. As with other database management systems, MongoDB allows you to manage and interact with data through four fundamental types of data operations which include: Creating, Reading, Updating and Deleting operations.
These four operations are jointly referred to as CRUD operations.

This article will outline how to perform CRUD operations of single documents and later discuss in details how to go about it in a project involving multiple documents in Mongo DB. By reading this article the reader will be able insert new multiple documents into a MongoDB database, modify existing ones, retrieve documents already present in a collection, and also delete documents as needed.

#### Key takeaways 
By the end of this article the reader will be able to:
- Have broad overview of CRUD data management operations involving single document in MongoDB.
- Insert new multiple documents into a MongoDB database,
- Modify existing ones,
- Retrieve documents already present in a collection and
- Delete documents as needed.

#### Article quality
This article will focus on CRUD data management operations step by step for multiple documents only.
This will help begginers understand this concept as one without wondering around single and multiple document which might be confusing.
It is unique in that,this approch and content orientation lacks in other blog sites for begginers.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 

https://www.google.com/search?q=Documents+Operations+in+MongoDB&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
