### ISSUE TITLE
[Networking] Monitorization of a network ;Internet Protocol version (IPV4 & IPV6) 

### ISSUE THREAD

**Issue by JGatura421** [section-engineering-education/engineering-education#7160]
### **Topic Suggestion**

Monitorization of a network (IPV4 & IPV6) 

### **Proposed article introduction**

IPV4 _(Internet Protocol version 4)_is a protocol used in a packet-switched link-layer network while IPV6 _(Internet Protocol version 6)_ is more advanced and has more advantages compared to IPV4.
The wide growth of networks over the world has helped fix the IP address exhaustion problem.

IPV6 is faster, more efficient, and more advanced than IPV4.

**### Key takeaways**

1. Internet Protocol version overview.
2. what is IPV4?
3. What is IPV6?
4. Monitoring IPV4.
5. Monitoring IPV6.
6.IPV6 route.

### **Article quality**
The article will elaborate internet protocol version and how to monitor the internet protocol version.

### **references**
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 

https://www.google.com/search?q=Monitorization+of+a+network+%3BInternet+Protocol+version+(IPV4+%26+IPV6)&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
