### ISSUE TITLE
How to generate eigenfaces in Matlab using singular value decomposition

### ISSUE THREAD

**Issue by florenceatieno45** [section-engineering-education/engineering-education#7162]
### Topic Suggestion
How to generate eigenfaces in Matlab using singular value decomposition

### Writing sample(s): 
https://www.section.io/engineering-education/how-to-use-edge-histogram-descriptor-to-retrieve-images-in-matlab/

#### Proposed article introduction
Eigenfaces refer to an appearance-based approach to face recognition. It seeks to capture the variation in a collection of face images and use this information to encode and holistically compare images of individual faces. Singular Value Decomposition (SVD) is a widely used technique to decompose a matrix into several component matrices, exposing many of the valuable and interesting properties of the original matrix.

This tutorial will show how to take a matrix where the columns are examples of human faces pictures reshaped into tall skinny vectors. Also, we will see how to use the singular value decomposition to get these eigenfaces representations. It is very useful for classification and analysis.

#### Key takeaways 
- How the eigenfaces are created.
- Reshaping human face pictures to tall skinny vectors.
- How to use SVD to get the eigenfaces representation.
- Matlab code for the eigenfaces generation.

#### Article quality
This article combines the concept of singular value decomposition and the eigenvectors to get the eigenface representations.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.


https://www.google.com/search?q=eigenfaces+in+Matlab+singular+value+decomposition&rlz=1C1CHBF_enUS891US891&ei=IzQ6YuvbMLTZ0PEPo66o8As&start=10&sa=N&ved=2ahUKEwir-dzwydr2AhW0LDQIHSMXCr4Q8tMDegQIARA4&biw=1706&bih=801&dpr=2.25
