### ISSUE TITLE
[MACHINE LEARNING] Passing a CSV dataset to a C++-powered model in a Python machine learning project

### ISSUE THREAD

**Issue by Agusioma** [section-engineering-education/engineering-education#7167]
### Writing sample(s): 
[Samples](https://www.section.io/engineering-education/authors/terrence-aluda/).

#### Proposed title of article
Passing a CSV dataset to a C++-powered model in a Python machine learning project

#### Proposed article introduction
We are going to build on [this](https://www.section.io/engineering-education/cpp-model-in-a-python-machine-learning-project/) article and learn how to pass a CSV dataset to a model built using C++. We will look at preprocessing the dataset, splitting it,and then making a prediction.

> I'm still researching on this. More will be shown.

#### Key takeaways 
- Preprocessing a dataset using C++
- Splitting the dataset and checking how to set random seeds to preserve the states using C++
- Making predictions from the dataset

#### Article quality
It is easy to follow through, and this is not much explored.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.


https://www.google.com/search?q=CSV+dataset+to+a+C%2B%2B+model+in+a+Python+machine+learning&rlz=1C1CHBF_enUS891US891&ei=fTQ6YrilHOmt0PEPvJCM-Aw&ved=0ahUKEwj4172bytr2AhXpFjQIHTwIA88Q4dUDCA4&uact=5&oq=CSV+dataset+to+a+C%2B%2B+model+in+a+Python+machine+learning&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABKBAhGGABQlwRY7AhgtgpoAXABeACAAUyIAZUBkgEBMpgBAKABAcgBCMABAQ&sclient=gws-wiz
