### ISSUE TITLE
How to control devices using DTMF signals and Matlab App designer

### ISSUE THREAD

**Issue by florenceakinyi** [section-engineering-education/engineering-education#7172]
### Topic Suggestion
How to control devices using DTMF signals and Matlab App designer

### Writing sample(s): 
https://www.section.io/engineering-education/how-to-perform-parallel-computing-using-matlab/

#### Proposed article introduction
Dual-tone multi-frequency (DTMF) is the sounds or tones generated by a telephone when the numbers are pressed. These tones are transmitted with the voice channel. DTMF controls automated equipment and signals user intent, such as the number they wish to dial. Each key has two tones at specific frequencies.

This article will look at how we can generate these tones in Matlab. Also, we will look at the DTMF recognition and relay driver hardware and a detailed understanding of the DTMF generation. It is basically to help students with various projects requiring DTMF.
#### Key takeaways 
- Device Control Strategy.
- Understanding DTMF generation.
- DTMF Recognition and Relay Driver Hardware.
- MATLAB Code to generate DTMF tones.
- Building applications using App designer.
- Matlab code for the App.

#### Article quality
It provides a detailed explanation of the DTMF generation and the DTMF recognition and relay driver hardware. It also shows how you can create a control application using the App designer.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.


https://www.google.com/search?q=DTMF+signals+and+Matlab+App+designer&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
