### ISSUE TITLE
[Languages]Automating Flutter Application Deployment Process using Fastlane

### ISSUE THREAD

**Issue by Eze4Manuel** [section-engineering-education/engineering-education#7173]
### Topic Suggestion
[Languages]Automating Flutter Application Deployment Process using Fastlane
  
#### Proposed title of the article
[Languages]Automating Flutter Application Deployment Process using Fastlane

#### Proposed article introduction
When we are done creating our mobile application using flutter, there is a rigorous process we have to undergo when we try to take this next step of deploying our application to google play or the app store. The strain in the process becomes clear whenever we need to release the latest feature of our application onto app distributors.  With fastlane, you have a way to automate the deployment process to ensure you have enough time to focus on your application creation.
 
#### Key takeaways 
- Reader will see implementation and the benefits of using fastlane for his deployment
- Deploy our application to app distributors
- Exposure to the capabilities of fastlane.

#### Article quality
My article is unique and has working examples that have the latest methods and functions used in fastlane.  
Exposure with a live application deployed to app distributors where your application can be shared and tested.

#### References 
![https://docs.fastlane.tools/] (fastlane documentation)
 ![https://github.com/fastlane/fastlane](fastlane)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.


https://www.google.com/search?q=Automating+Flutter+Application+Deployment+Process+using+Fastlane&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
