### ISSUE TITLE
Python Cyclic Redundancy Check

### ISSUE THREAD

**Issue by Gatimu22** [section-engineering-education/engineering-education#7176]
#### Proposed title of article
[Languages] Python Cyclic Redundancy Check

#### Proposed article introduction
Using CRC, or Cyclic Redundancy Check, a communication channel may be checked for unintended modifications or mistakes.
In order to generate a CRC, the sender and receiver must both have access to a Generator Polynomial. An (n-k) bit sequence known as the frame check sequence is used by the transmitter to verify the integrity of the k-bit message. There is a definite number of bits in the n-bit output frame that can be divided exactly by that number. This binary addition with no carries uses Modulo 2 Arithmetic, precisely as the XOR procedure.
By redundancy, we mean the occurrence of multiple instances of something. To modify the CRC's redundancy bits, the data unit must be divided by a predetermined divisor. CRC is remaining.

#### Key takeaways 
- An insight of cyclic redundancy check
- Qualities of cyclic redundancy check
- Understand cyclic redundancy check and modulo-2 division
- How to convert a string to binary string data
- Working with cyclic redundancy check in socket programming python at both sender and receiver sides

#### Article quality
The article will be in-depth and unique in beginner-friendly. To enhance understanding this article will be covered in an interesting way especially in running the program and how to fix cyclic redundancy check errors.
 
#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.


https://www.google.com/search?q=Python+Cyclic+Redundancy+Check&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
