### ISSUE TITLE
Insertion Sort of Algorithms in Javascript and C++

### ISSUE THREAD

**Issue by Wendymwangi** [section-engineering-education/engineering-education#7194]
#### Proposed title of article

Insertion Sort of Algorithms in Javascript and C++

#### Proposed article introduction

* Insertion sort is a sorting algorithm that creates a sorted array of items from an unsorted array, one item at a time.
 In this article, we will see how the algorithm works and how to apply it in our code. Note if the current number from the unsorted array is less than any number it is being compared with in the sorted array, the one in the sorted array will move to the right and create an empty space on its previous position to insert the current number.
 This will continue until the current number gets to a position where it is greater than the number it is being compared with. At this point, you insert the current number into the last created space.

#### Key takeaways 

* By the end of this article, the following is expected;

1. How to Use Insertion Sort
2. Insertion Sort in Java
3. Insertion Sort in C++

#### Article quality

This article will be on point, simple to understand, well formatted and I'm sure users will be able to learn how to sort Algorithm in both Javascript and C++ programming languages. The code snippets in this article will be simple to understand and implement. I hope we will have a good ride all along.

#### Reference

N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

https://www.google.com/search?q=Insertion+Sort+of+Algorithms+in+Javascript+and+C%2B%2B&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
