### ISSUE TITLE
Using and Re-using Layouts in Spark Application

### ISSUE THREAD

**Issue by twish-254** [section-engineering-education/engineering-education#7195]
#### Proposed title of article
Using and Re-using Layouts in Spark Application

#### Proposed article introduction
When building an application, we may notice some redundancy between templates. They all have the same opening <DOCTYPE>, <html>, and other basic required tags at the tops and bottoms of their files.

In this article, we will be creating a reusable layout, that will be able to render all pages at once in a Spark application. This layout will contain the HTML that all templates have in common in our applications. Then, each individual page will render the HTML unique to it through the layout. Reusable layouts and creating small page chunks is where templating will begin.

#### Key takeaways 
- Creating Reusable Layouts
- Streamlining the Layout
- How `layout.hbs` Works

#### Article quality
The article will be unique as there is blog covering tghe topic
#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=Using+and+Re-using+Layouts+in+Spark+Application&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
