### ISSUE TITLE
How to style a Vaadin application

### ISSUE THREAD

**Issue by Eztaezta** [section-engineering-education/engineering-education#7196]
#### Proposed title of article
How to style a Vaadin application

#### Proposed article introduction
Vaadin is a Java-based web app development framework. It enables developers to create dependable web apps with excellent UX faster than before.

While the Java API can be used to style specific sections of a Vaadin application, this method is limited to mid-to large-sized projects. As a result, it is recommended that Vaadin applications be styled using CSS inside standard style sheets.

In this tutorial, we will focus on the CSS-based styling of Vaadin applications.

#### Key takeaways 
1. How to selectively style the internals of a Vaadin component
2. How to override Lumo values
3. How to selectively style views and components
4. How to selectively style the internals of a Vaadin component

#### Article quality
In this article, I will make sure that the beginner  can easily understand the covered concepts unlike other blogs that are not easy to understand.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

**Comment by hectorkambow** [comment]
https://www.google.com/search?q=How+to+style+a+Vaadin+application&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
