### ISSUE TITLE
Working with hamming code in python

### ISSUE THREAD

**Issue by terry254** [section-engineering-education/engineering-education#7198]
#### Proposed title of article
[Languages] Working with hamming code in python

#### Proposed article introduction
It is possible to identify and fix data transmission faults using the Hamming code, which is a collection of error-correction codes. Sources in Hamming coding contribute extraneous bits to messages to encode them. Error detection and rectification are facilitated by inserting and generating redundant bits at strategic locations throughout the message. Developed by R.W. Hamming, this method is used to identify errors. Data units of any length may benefit from Hamming code, which makes use of the link between data and redundancy bits to do so.
He worked on the error-correction approach and created the Hamming code, an ever-increasingly powerful collection of algorithms.

#### Key takeaways 
The reader will be able to:
1. Have an insight into what is a hamming code and what it entails including its merits and demerits as well as how to apply it in various ways
2. Working with hamming code in python:
- How to input the data that will be transmitted
- Calculating the number of redundant bits that are necessary
- Determining the bits of parity
- Prepare test data with errors
- Making sure there aren't any mistakes

#### Article quality
This will be an interesting read-through. The article will major on stepwise implementation in a beginner-friendly manner. It will be deeper in the aspects of this concept.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=Working+with+hamming+code+in+python&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
