### ISSUE TITLE
[Languages] Creating a three-column layout with React, Typescript and Ant design library

### ISSUE THREAD

**Issue by FredBenson** [section-engineering-education/engineering-education#7202]
### Topic Suggestion
Creating a three-column layout with React, Typescript and Ant design library

### Writing sample(s): 
-	https://www.section.io/engineering-education/image-handling-and-cropping-component-in-react.js/
-	https://www.section.io/engineering-education/responsive-charts-with-semantic-ui-and-react/

#### Proposed title of article
Creating a three-column layout with React, Typescript and Ant design library

Use keyword research to improve your article's SEO.

#### Proposed article introduction
The three-column layout design in front-end web development has been widely adopted by social media, blogs, etc. with notable examples being Facebook, Twitter and LinkedIn.
In this tutorial, we will build from scratch a fully functional three-column web application with React, Typescript and Ant design Library. The application will consist of four (4) major responsive components:
-	The Widget
-	Footer component
-	Navbar component
-	Sidebar component
 We will also explore the advantages/benefits of Ant design library and how it can be utilized in building complex designs and layouts in React.js. 

#### Key takeaways 
At the completion of this tutorial, the reader is expected to have the understanding and required skill to implement the following:
-	Getting started with React.js application development.
-	Adding Typescript and Ant design libraries to your React application.
-	Creating a three-column layout design with Ant design and Typescript.
-	Best practices when working with third-party design libraries.
-	Customizing components with Ant design library and CSS.
-	 Error handling in Typescript.

#### Article quality
This article is a unique project-based tutorial that aims to take a deep dive into building a three-column layout with React.js, Typescript and Ant design library. The article will also shed light on the best practices and benefits of working with third-parties design libraries.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?
https://www.google.com/search?q=Typescript+and+Ant+design+library+columns&rlz=1C1CHBF_enUS891US891&ei=uVE7YuS_A4e50PEP88m6kAM&ved=0ahUKEwikgPid2tz2AhWHHDQIHfOkDjIQ4dUDCA4&uact=5&oq=Typescript+and+Ant+design+library+columns&gs_lcp=Cgdnd3Mtd2l6EAMyCAghEBYQHRAeOgcIABBHELADOgUIIRCgAUoECEEYAEoECEYYAFDaAljgDmDSFWgCcAF4AIABbIgB4gWSAQM4LjGYAQCgAQHIAQjAAQE&sclient=gws-wiz
