### ISSUE TITLE
Understanding methods to peform tokenization in python

### ISSUE THREAD

**Issue by Shee254** [section-engineering-education/engineering-education#7207]
#### Proposed title of article
Understanding methods to perform tokenization in python

#### Proposed article introduction
Tokenization in Python is the most primary step in any natural language processing program. This may find its utility in statistical analysis, parsing, spell-checking, counting and corpus generation etc. The tokenizer is a Python 2 and 3 module. In this article we will discuss more about the number of methods to perform Tokenization.

#### Key takeaways 
1. Python’s split function
2. spaCy library
3. Tokenization using Keras
4. Tokenization with Gensim

#### Article quality
In this article understanding methods to peform tokenization in python I will make use of simple language easily understandable by beginners. All code snippets Will be explain to enhance clear understanding. I will explain all the content in this field and the reader will find it more helpful.
#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=Understanding+methods+to+peform+tokenization+in+python&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
