### ISSUE TITLE
How to build a RESTful API using PHP and Laravel framework

### ISSUE THREAD

**Issue by elphazesedah** [section-engineering-education/engineering-education#7214]
#### Proposed article introduction

PHP has been the most popular web language in the present times by being simple to maintain, and quick to create feature-rich web applications. Websites that are dynamic, interactive, secure and efficient, need a powerful tool set to create and consume APIs.
An efficient API is needed in our times in order to develop content that boosts discoverability and help achieve business goals, PHP is the language that most web developers use and software that has recently been the most successful on deploying web applications.

In this article, I will be discussing the  concept behind a RESTful API and the go ahead to give a step by step process of building and testing a RESTful API using PHP and Laravel framework.

#### Key takeaways 

1. The reader will be able to understand the concept of RESTful API from the introductory background that I will give.
2. The reader will be able to understand  how to build a RESTful API using PHP and Laravel framework.
3. The reader will be able to understand how to test a RESTful API created using PHP and Laravel.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by WanjaMIKE** [comment]
Already covered here -> https://www.section.io/engineering-education/how-to-create-an-api-using-laravel/

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=RESTful+API+using+PHP+and+Laravel+framework&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
