### ISSUE TITLE
How To Develop A Progressive Web App Using Nextjs and Tailwindcss

### ISSUE THREAD

**Issue by gisioraelvis** [section-engineering-education/engineering-education#7215]
### Writing sample(s):

[ENGED PROGRAM CONTRIBUTOR Gisiora Elvis](https://www.section.io/engineering-education/authors/gisiora-elvis/)

### Topic Suggestion

How To Develop A Progressive Web App Using Nextjs and Tailwindcss

### Proposed article introduction

The Progressive Web App (PWA) is a web application that is optimized for mobile devices. They come with a number of benefits, such as a faster loading time, a better user experience, and a better offline experience. They are also a great way to help users find apps faster since they do not need to be installed from the app stores and improve their search engine rankings since they are already available on the web for crawling and indexing.

This article will guide the reader through how to develop a progressive web app using Nextjs and Tailwindcss so that they can take advantage of the benefits that come with the PWAs.

### Key takeaways

- What is a progressive web app?
- Why you should use a progressive web app.
- In-depth guide on how to implement tailwindcss progressive web app in a Nextjs application.

### Article quality

This will be a step by step beginner-friendly and in-depth guide that covers the implementation of a progressive web app using Nextjs and Tailwindcss.

### References

- [Nextjs](https://nextjs.org/docs/getting-started)
- [Tailwindcss](https://tailwindcss.com/docs/guides/nextjs)
- [Progressive Web Apps](https://web.dev/progressive-web-apps/)
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it
struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=Progessive+Web+App+Using+Nextjs+and+Tailwindcss&rlz=1C1CHBF_enUS891US891&ei=IlM7Yo_0LNHw9AOboZW4CA&ved=0ahUKEwiPjbPK29z2AhVROH0KHZtQBYcQ4dUDCA4&uact=5&oq=Progessive+Web+App+Using+Nextjs+and+Tailwindcss&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKsCOgcIABBHELADSgQIQRgASgQIRhgAUL8LWO5OYOmGAWgBcAF4AIABZ4gBxwqSAQQxNS4xmAEAoAEByAEIwAEB&sclient=gws-wiz
