### ISSUE TITLE
Formulating an Information Base Using Prolog

### ISSUE THREAD

**Issue by lizpart** [section-engineering-education/engineering-education#7242]
#### Proposed title of article

Formulating an Information Base Using Prolog

#### Proposed article introduction

Prolog is derived from PROgramming in LOGics. It is a logical and declarative programming language used to create artificial intelligence.
In Prolog, we need not mention the way how one problem can be solved, we just need to mention what the problem is so that Prolog automatically solves it.
You need to formulate your Knowledge Base so that the questions can be answered correctly, but you must abide by the following
rules:
• Your Knowledge Base must not contain any fact that is just an instance of one of the questions.
• Each question must require at least two rule firings in a procedural manner.
• Background knowledge must be in terms of general categories which contain the individuals.
• Your background knowledge need not be strictly true, but generally reasonable and appropriate for answering
the questions.
In this tutorial, we will be covering the key components of working with the Knowledge-Based. Tools to be used are SWI-prolog and any editor of choice.
#### Key takeaways 
 - Performing creation of facts.
 - Creation of rules to be used.
 - Query implementation and execution.
 - Understanding relations in prolog.
 
#### Article quality

This article is designed in an eccentric way for easier understanding and consumption for a beginner and above. It covers extensive details on the knowledge-oriented paradigm also to mention.

#### References
N/A

**Comment by lizpart** [comment]
@lalith1403 This is a reopening of topic #7098. I have made the changes.

**Comment by lalith1403** [comment]
What do you mean by the title? Formulate an Information-Based Using Prolog? Information-Based what? Are we missing anything?

**Comment by lizpart** [comment]
Procedurize

**Comment by lizpart** [comment]
Proceduralizing  a Knowledge basesd using prolog programming  language in AI

**Comment by lalith1403** [comment]
Please double check. You still have spelling mistakes. Is it information base or information based something?

**Comment by lizpart** [comment]
@lalith1403  Corrected the spelling check

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?
https://www.google.com/search?q=Knowledge+Base+Using+Prolog&rlz=1C1CHBF_enUS891US891&ei=suREYqDzIaK_0PEP5q69qAE&ved=0ahUKEwiglJbV--72AhWiHzQIHWZXDxUQ4dUDCA4&uact=5&oq=Knowledge+Base+Using+Prolog&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABKBAhGGABQogNYogNg4wVoAnABeACAAVyIAVySAQExmAEAoAECoAEByAEIwAEB&sclient=gws-wiz

**Comment by breathernzuki** [comment]
Hi

**Comment by hectorkambow** [comment]
👋  
@breathernzuki
