### ISSUE TITLE
Working with JSTL and Custom Tag Libraries

### ISSUE THREAD

**Issue by Tumorbenson** [section-engineering-education/engineering-education#7269]
Proposed title of article
Working with JSTL and Custom Tag Libraries

Proposed article introduction
JSTL 1.2 is part of Java EE platform and represents a set of tags used to simplify the development of JSP. We can use the JSTL in various pages and avoid use of script tags. Iteration and conditionals, as well as tags for manipulating XML documents, internationalization tags, and SQL tags, are all supported by JSTL. It also includes a framework for combining existing custom tags with JSTL tags.

JSTL stands for[server pages standard tag library] and it is a collection of custom JSP tag libraries that provide common web development functionality. JSTL is a standard tag library of the JSP.

ONLY viable topics to pick from:

API
Artificial Intelligence
Blockchain
Containers
Edge Computing
Languages
Machine Learning
Networking
Node.js
Security
Key takeaways
Introduction
Core Tags
SQL Tags
XML Tags
Function tags
Internationalization Tags
Article quality
JSTL and Custom Tag Libraries are advanced Java concepts that all Java developers should be familiar with. They are used to make JSP development easier, and I will go over them in detail. I've noticed that this topic has yet to be addressed in the Engineering block, and that those that have do so in a limited way or fail to explain and provide all of the necessary information.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?
https://www.google.com/search?q=JSTL+and+Custom+Tag+Libraries&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
