### ISSUE TITLE
Implementing a Spring Query Language - Spring Boot Search Operations

### ISSUE THREAD

**Issue by teevyne** [section-engineering-education/engineering-education#7271]
### Topic Suggestion
Implementing a Spring Query Language - Spring Boot Search Operations

#### Pre-submission advice
By following all our pre-submission advice and reviewing our Resources folder, you will maximise your chances of your topic being approved.

We ask that you please be patient as our team works through approving and publishing all articles/tutorials in a timely manner.

Allow 1-3 days for a topic to be reviewed and/or approved - allow 3-7 days for an articles to be reviewed and/or published (subject to vary depending on _volume and/or backlog of articles_).

Be sure to visit our [Resources Page](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/resources-page.md) for tools, resources, and example articles that will help you propose and write a successful article.

**Please ensure that you have only one open issue + linked pull request at a time. This will ensure that we complete the article in a timely manner from inception to publishing.)**

**We tend to stray away or tend not to publish reviews/comparisons of commercial product offerings.**

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
[Languages] Implementing a Spring Query Language - Spring Boot Search Operations

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Having built many endpoints and in good cases, a whole API, I know the amount of work that goes not only into bulding them but querying them for various use in the system - or maybe others. 

Making resources available is one of the things to take into serious consideration during building. In some situations, you would like to let the customer to search for information in many easy ways, while avoiding the temptation of creating too many services for this to be possible.

In comes the Search Language (also called Query Language) in Java. With this provision, you can easily make searching the API powerful, clean and easy and not have to deal with intricacies of methods, functions and lots of coding

#### Key takeaways 
At the end of the tutorial, readers would:
- understand the fundamental implmentation of Spring's search operations
- be able to implement various forms of lightweight queries for searching any system
- write tests to check for different use cases of searching

#### Article quality
This is a unique article that is based off of the whole concept and provision of the Spring JPA. It is the first of a mild series of various strategies for querying a database or an application.

**Comment by teevyne** [comment]
> 👋 @teevyne Good afternoon and thank you for submitting your topic suggestion. Your topic form has been entered into our queue and should be reviewed (for approval) as soon as a content moderator is finished reviewing the ones in the queue before it.

@lalith1403 FYI. Thank you

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=Spring+Boot+Search+Operations&rlz=1C1CHBF_enUS891US891&ei=X9BEYvn6DdrW9AO465moCw&ved=0ahUKEwi5poSk6O72AhVaK30KHbh1BrUQ4dUDCA4&uact=5&oq=Spring+Boot+Search+Operations&gs_lcp=Cgdnd3Mtd2l6EANKBAhBGABKBAhGGABQAFj6CGCYC2gAcAF4AIABWIgBqwGSAQEymAEAoAEBwAEB&sclient=gws-wiz

**Comment by teevyne** [comment]
> Good afternoon and thank you for submitting your topic to the EngEd program.
> 
> After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.
> 
> But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. rocket An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.
> 
> If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?
> 
> https://www.google.com/search?q=Spring+Boot+Search+Operations&rlz=1C1CHBF_enUS891US891&ei=X9BEYvn6DdrW9AO465moCw&ved=0ahUKEwi5poSk6O72AhVaK30KHbh1BrUQ4dUDCA4&uact=5&oq=Spring+Boot+Search+Operations&gs_lcp=Cgdnd3Mtd2l6EANKBAhBGABKBAhGGABQAFj6CGCYC2gAcAF4AIABWIgBqwGSAQEymAEAoAEBwAEB&sclient=gws-wiz

I believe my article is unique as the ones up there provide one realm of application. Mine would provide a number of applicability and approaches. My project - the biggest I have thus far; Homefort Energy - is data-intensive. Searching and querying needs to be optimised and like the rest of my articles, this one is deriving directly from my personal experience.

In that light, I would say that my article is unique and different from what obtains.

I hope this meets you well and presents my case

@hectorkambow Good morning
