### ISSUE TITLE
Building a voice translator with Azure translation API using Python

### ISSUE THREAD

**Issue by josephotienoowino** [section-engineering-education/engineering-education#7275]
### Topic Suggestion
Building a voice translator with Azure translation API using Python

#### Proposed title of article
Building a voice translator with Azure translation API using Python

#### Proposed article introduction
In this tutorial we will discuss voice translation and develop a voice translator using Azure translation API using Python programming language. Beside we will also discuss some of the models used aside to translate voices.
#### Key takeaways 
By the end of this tutorial the learner will be able to:

- Build his/her own model using Azure API packages in Python.
- Be able to learn new tricks towards voice translation.

#### Article quality
This articles is new 
#### References
None

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

@josephotienoowino 
https://www.google.com/search?q=voice+translator+with+Azure+translation+API+using+Python&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
