### ISSUE TITLE
Wavelet transform based denoising of signals in Matlab

### ISSUE THREAD

**Issue by florenceakinyi** [section-engineering-education/engineering-education#7278]
### Topic Suggestion
Wavelet transform based denoising of signals in Matlab

### Writing sample(s): 
https://www.section.io/engineering-education/how-to-perform-parallel-computing-using-matlab/

#### Proposed article introduction
Wavelet transform is a very powerful tool in the field of Signal Denoising. It gives far better denoising results as compared to frequency-selective filters. Wavelet transform is a transformation where a signal containing N samples is first filtered by a pair of filters that decompose the signal into low and high-frequency bands. Then, the low-frequency bands are approximated coefficients, and the high-frequency bands are the detailed coefficients.
In this tutorial, the Wavelet Transform based denoising of signals is explained. Then, we will look at the Matlab functions used for denoising purposes. Also, we will look at a sample program that helps implement these functions.

#### Key takeaways 
- Denoising Scheme using Wavelet Transform.
- Threshold Estimation Methods.
- Explanation of ‘wden’ and ‘wdenoise’ MATLAB functions.
- Denoising examples in MATLAB.

#### Article quality
This article shows how we can use the wavelet transform to denoising an audio signal using `wden` and `wdenoise` functions.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=Wavelet+transform+based+denoising+of+signals+in+Matlab&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
