### ISSUE TITLE
Implementing Automated End-to-end Testing In A Nextjs App Using Jest and Playwright 

### ISSUE THREAD

**Issue by gisioraelvis** [section-engineering-education/engineering-education#7279]
### Writing sample(s):

[ENGED PROGRAM CONTRIBUTOR Gisiora Elvis](https://www.section.io/engineering-education/authors/gisiora-elvis/)

### Topic Suggestion
Implementing Automated End-to-end Testing In A Nextjs App Using Jest and Playwright 

### Proposed article introduction 
End-to-end Testing is very important and should be essential in every application. In this tutorial, I will introduce the reader to end-to-end testing as a concept, the challenges the reader is likely to encounter and the importance of automating the process.

Jest is a javascript testing library that is used to test the functionality of an application. It is a tool that allows writing tests for javascript applications and then running them to make sure that the application is working as expected.

Playwright is a headless browser automation tool used to write end to end tests for web applications. It is used to emulate user interactions on the web application on a headless browser.

In this tutorial I will demonstrate in a step by step and easy to understand example how to write automated end-to-end tests using Jest and Playwright in a Nextjs application, so that the reader can take advantage of the benefits that come with testing.

### Key takeaways
- What is end-to-end testing?
- Why end-to-end testing is important.
- Overview to jest testing library and how to write tests.
- Overview to playwrite web automation library.
- In-depth guide on how to implement end-to-end testing in a Nextjs application.

### Article quality
This will be a step by step beginner-friendly and in-depth guide that covers the implementation of end-to-end testing using Jest and Playwright in a Nextjs application. 

### References
- [jest](https://jestjs.io/)
- [playwright](https://www.playwright.dev/)
- [Nextjs](https://nextjs.org/docs/getting-started)
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=End-to-end+Testing+In+A+Nextjs+App+Using+Jest+and+Playwright&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8

**Comment by gisioraelvis** [comment]
I believe that knowledge can never be exhausted, and when I look at nearly similar content online, none combine the 2 libraries(jest+playwright) in the same tutorial. The real power comes in combining the 2 libraries when testing an application. With that, you get the benefits and strengths of both libraries. In addition, this will be beginner-friendly and as engaging as possible. Making this article one-of-a-kind. Will address these issues as gracefully as possible in order to maintain quality and add value to the community.
