### ISSUE TITLE
[Languages]Getting the required methods in classes that comprise multi-inheritance in Python

### ISSUE THREAD

**Issue by Joshuathuo** [section-engineering-education/engineering-education#7280]
#### Proposed title of article
Getting the required methods in classes that comprise multi-inheritance in Python

#### Proposed article introduction
In each and every programming language, there are always classes that are usually created while implementing various functionalities. And when creating a class, it can be a one single class or it can be several classes but they are inherited the main or the parent class. 

Therefore if this will be the case, we shall want to know what classes have been inherited from the super class. This will be done using a python module that is used to search the order in which the execution of the base class or the parent class is done.

#### Key takeaways 
1. A look at linearization Algorithm
2. A look at some of the tasks of linearization Algorithm
3. Implementation 
#### Article quality
The quality of the content that will be in this article will be of help to our students and learners at any level of learning.
#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=multi-inheritance+in+Python&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
