### ISSUE TITLE
How To Use Docker Application To Run Python Discord Bot

### ISSUE THREAD

**Issue by Lavenda99** [section-engineering-education/engineering-education#7289]
Writing sample(s): 
https://en.wikipedia.org/wiki/Discord (software)

 Proposed article introduction

Discord is a voice platform with IP, instant messaging, and digital distribution. Users communicate in private conversations or as part of "servers" via voice calls, video calls, text messaging, media, and files. [Footnote 1] Server is a collection of permanent chat sites and voice chat channels accessible through invitation links. Windows, macOS, Android, iOS, iPad, Linux, and web browsers all support Discord. The service has had over 350 million registered users and 150 million active users since 2021. 

Bots can use the Discord field to perform automated tasks by responding to human commands. As a result, this post will show you how to use the Python-based Discord bot in the Docker container.

#### Key takeaways 

1.  Make your own Discord request.
2. Set Requirements.
3. Make Discord Bot.
4. Activate Discord Bot.
5. Join Discord Server with Bot.

 Article quality
This post will include the implementation of the Docker Application Application to Run the Python Discord Bot in a step-by-step and in-depth manner.

#### References
Docker application
Tutorial template
Python

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?
https://www.google.com/search?q=Docker+Application+To+Run+Python+Discord+Bot&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
