### ISSUE TITLE
 Data Manipulation Language (DML) in Database

### ISSUE THREAD

**Issue by SHARONCHEROTICH** [section-engineering-education/engineering-education#7291]
#### Proposed title of article
 Data Manipulation Language (DML) in Database 

#### Proposed article introduction
A data manipulation language is a computer programming language used to perform CRUD operations in a database. A DML is often a sublanguage of a broader database language such as SQL, with the DML comprising some of the operators in the language.

In SQL, the data manipulation language comprises the SQL-data change statements, which modify stored data but not the schema or database objects. Manipulation of persistent database objects, e.g., tables or stored procedures, via the SQL schema statements, rather than the data stored within them, is considered to be part of a separate data definition language.

#### Key takeaways 
1. Perform CRUD Operations.
2. Uses Of DML.
3. Contrast  DML with other Programming language
4. Learn how to connect a simple form to the database.

#### Article quality
This article will be unique in that it will be a beginner-friendly and all developers will understand what is  DML.
Users will be able to contrast DML with other languages.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=Data+Manipulation+Language+%28DML%29+in+SWL&rlz=1C1CHBF_enUS891US891&ei=gOFEYujQC-TP0PEPsLmxuAI&ved=0ahUKEwjokPnO-O72AhXkJzQIHbBcDCcQ4dUDCA4&uact=5&oq=Data+Manipulation+Language+%28DML%29+in+SWL&gs_lcp=Cgdnd3Mtd2l6EAMyCAghEBYQHRAeMggIIRAWEB0QHjIICCEQFhAdEB4yBAghEAo6BwgAEEcQsAM6BggAEBYQHjoFCCEQoAFKBAhBGABKBAhGGABQ8gVYnAhg-AloAnABeACAAZIBiAH0ApIBAzEuMpgBAKABAcgBCMABAQ&sclient=gws-wiz
