### ISSUE TITLE
Guide to parsing XML in Node.js

### ISSUE THREAD

**Issue by Humjerry** [section-engineering-education/engineering-education#7292]
I'll like to write a comprehensive guide on how to parse XML data in Node.js. An outline for this topic is provided below:

- What is XML ?
- Parsing XML with Node.js
- How to use xml2js
- xml2js in more detail
- Get XML content as a string 
- Convert strings to Objects 
- Write response to a File
- Alternatives to xml2js
- Conclusion

**Comment by Humjerry** [comment]
Thank you for the acknowledgement. I await your feedback.

**Comment by hectorkambow** [comment]
Welcome - Hector here.
This seems like a very cool topic - but regarding Node.js we are currently not publishing as many Node.js articles because we have more than enough currently in our EngEd library.
As we did a big push the last few months and we are currently not accepting any more Node.js articles to publish for the time being.
Please feel free to suggest an alternate topic to explore. 🚀
