### ISSUE TITLE
[Machine Learning] Biomedical Imaging

### ISSUE THREAD

**Issue by Jairusonkundi** [section-engineering-education/engineering-education#7295]
Proposed title of article
[Machine Learning] Biomedical Imaging
Proposed article introduction
The field of biomedical imaging focuses on the acquisition of pictures for diagnostic and therapeutic applications.Advanced sensors and computer technologies can provide snapshots of in vivo physiology and physiological processes.Biomedical imaging technologies assess the current condition of an organ or tissue using x-rays (CT scans), sound (ultrasound), magnetism (MRI), radioactive pharmaceuticals (nuclear medicine: SPECT, PET), or light (endoscopy, OCT) and can oversee a patient over time for diagnostic and treatment assessment.
Images collected using x-ray, ultrasound, MRI, nuclear medicine, and optical imaging technologies are analyzed, enhanced, and displayed.Computerized algorithms can discover patterns and traits suggestive of cancers and other diseases using temporal and geographical analysis.
In this tutorial, we will discuss biomedical imaging,how the biomedical images are processed and how biomedical imaging is implemented in various fields.
Key takeaways
Introduction to biomedical imaging
Image processing in biomedical
Systems for diagnostic and therapeutic purposes
Clinical imaging systems
Imaging molecular and cellular biomarkers
Imaging receptors
Imaging in drug therapy
Conclusion

Article quality
This tutorial is unique because we will implement biomedical imaging in detail so that a reader can understand the concepts in biomedical imaging. We will discuss on how biomedical images are processed ,how diagnostic and therapeutic systems works. We will also discuss on how image receptors are used.

References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=Biomedical+Imaging&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
