### ISSUE TITLE
Creating Phone calls Application in Android

### ISSUE THREAD

**Issue by morwabe1234** [section-engineering-education/engineering-education#7296]
Proposed title of article
Creating Phone calls Application in Android

Proposed article introduction
In some cases, we may need to make a phone call using our program, which Android has built-in applications for. This might be accomplished quickly by combining implicit Intent with the required actions. We can also use the PhoneStateListener and TelephonyManager classes to keep track of changes in the device's telephony states.
This article outlines all of the basic stages for developing an application that can make a phone call.

Key takeaways
Action needed to make a call
Data types required to make a call
Create an Android project using Android studio IDE 
Modify the src/MainActivity.java file to include the necessary code for making a call
Design the user interface
Modify AndroidManifest.xml 
To start the Android emulator, run the program
Conclusion
Article quality
This article is unique as it explains how to make an android application for phone calls step by step. There are few authors who have tried to discuss on this topic but has not been clearly and practically dealt with.  In this article , I  will go step by step in creating an application for making calls in android in a clear and simple way. 

References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=Build+Phone+calls+Application+in+Android&rlz=1C1CHBF_enUS891US891&ei=ceVEYrSEOIHS9AOJopPwAw&ved=0ahUKEwj0gLaw_O72AhUBKX0KHQnRBD4Q4dUDCA4&uact=5&oq=Build+Phone+calls+Application+in+Android&gs_lcp=Cgdnd3Mtd2l6EANKBAhBGABKBAhGGABQAFibBWDnBmgAcAF4AIABcYgBxgSSAQMzLjOYAQCgAQHAAQE&sclient=gws-wiz
