### ISSUE TITLE
[Languages]A complete guide on Indexers in C# and its implementation

### ISSUE THREAD

**Issue by amosnjoro** [section-engineering-education/engineering-education#7301]
#### Proposed title of article
A complete guide on Indexers in C# and its implementation

#### Proposed article introduction
The idea of indexers is similar to the idea of properties. In terms of language features, indexers are analogous to properties in many ways. Indexers allow indexed properties to exist, which are properties that are referred to by one or more arguments. 

These arguments are used to build an index into a collection of values. Indexers are typically employed in types whose primary objective is to encapsulate an internal collection or array. Here, we shall in details the multi-dimension maps, dictionaries and many more using well versed examples.

#### Key takeaways 
1. A look at Multi-dimensional maps and its implementation
2. A look at Arrays and vectors and implementation
3. A look at syntax of indexes

#### Article quality
The quality of the content that is going to be written in this article will be of a level that will be understood by each and every learner at any level of this programming world.
#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. 

Please feel free to suggest an alternate topic to explore. 🚀 

An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=Indexers+in+C%23&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
