### ISSUE TITLE
[Languages] Building a Bookshelf Web Application with Django REST Framework and React.

### ISSUE THREAD

**Issue by dentonya** [section-engineering-education/engineering-education#7307]
### Proposal Submission
How to build a bookshelf application with the Django REST Framework and React Js

#### Proposed title of article
Building a Bookshelf Web Application with the Django REST Framework and React.

#### Proposed article introduction
The Django web framework allows us to build web applications quickly with a lot of tools provided. It simplifies how applications interact with databases. It is very modular, scalable, and with its MVT pattern, you can deliver quickly.
However, as time goes by, people are getting used to the idea of a more interactive UI. Building the front-end part with only Django templates is not enough; hence, other frameworks like React Js are needed. React is a component-based JavaScript library that enables you to build your framework quickly and efficiently.
This article will cover much concerning both the Django and React Js frameworks and how to implement a bookshelf application using the Django Framework Rest APIs with React Js. We will use the REST API for retrieving, creating, deleting, and changing the state of books with the React framework, which is used for the front-end design. With this app, you can keep track of books that have been read and those that have not been finished yet.

#### Key takeaways 
From this article, the reader will be able to:
- Understand how Django works with the REST Framework API.
- Understand how to build a Django rest API using the Django Rest Framework.
- Get to know how to combine Django with React Js.
- Be equipped with the knowledge of how Django Rest APIs and React combined can be used in implementing a Bookshelf Web Application for managing the books read and those yet to be finished.

#### Article quality
This article will be of high quality and be of great help to the reader. It will not only cover how Django and React can be used in web applications, but how we can integrate the Django REST Framework into building a bookshelf application. This application will help manage a high number of books to be read.
#### References
N/A

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=Bookshelf+Web+Application+with+Django+REST+Framework+and+React&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
