### ISSUE TITLE
How to process audio signal using Simulink

### ISSUE THREAD

**Issue by florenceatieno45** [section-engineering-education/engineering-education#7323]
### Topic Suggestion
How to process audio signal using Simulink

### Writing sample(s): 
https://www.section.io/engineering-education/how-to-use-edge-histogram-descriptor-to-retrieve-images-in-matlab/

#### Proposed article introduction
Simulink is a dynamic and software Matlab integrated simulation and model design system. Simulink is a graphical programming language data flow tool for modelling, simulating and analyzing models. It’s essentially a diagrammatical framework with customizable block library packages, product style control, traceability criteria, and application coverage analysis. Using this software, we can create models to process audio signals.

This tutorial presents some basic processing of Audio signals using Simulink. We are implementing FIR low pass filter to remove white Gaussian noise in an audio signal. Also, a graphic equalizer is implemented to produce various sound effects such as Pop, Rock, Jazz, etc. Few other popular sound effects such as Echo, Flange and Reverb are also realized in SIMULINK.

#### Key takeaways 
- Basic Filtering: Low Pass FIR filter to remove white Gaussian noise.
- How to perform graphic Equalizer of 10bands using Simulink.
- The echo, flange, and reverb effect using Simulink.
- Simulink simulation of these processes.

#### Article quality
This article shows how to simulate different models to process audio signals using Simulink. The simulations are well explained, and the different blocks to use.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=audio+signal+using+Simulink&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
