### ISSUE TITLE
[Machine Learning] MobileViT: A Mobile-friendly Vision Transformer

### ISSUE THREAD

**Issue by lcheop** [section-engineering-education/engineering-education#7325]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

MobileViT: A Mobile-friendly Vision Transformer

#### Proposed article introduction
Light-weight convolutional neural networks (CNNs) are the de-facto for mobile vision tasks. Their spatial inductive biases allow them to learn representations with fewer parameters across different vision tasks. However, these networks are spatially local. To learn global representations, self-attention-based vision transformers (ViTs) have been adopted. Unlike CNNs, ViTs are heavy-weight. This article aims to introduce MobileViT, a light-weight and general-purpose vision transformer for mobile devices

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

By the end of this tutorial, a reader will be able to have:
- An overview of the MobileViT model.
- How the model compares to the ViT model.
- How to implement the model.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

MobileViT is a recent model released by the Apple company ML research team. It is barely a months old. Not much content is available online.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.
- [MobileViT: Light-weight, General-purpose, and Mobile-friendly Vision Transformer](https://arxiv.org/abs/2110.02178)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=MobileViT%3A+A+Mobile-friendly+Vision+Transformer&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
