### ISSUE TITLE
Creating Metamask logins for PHP based websites

### ISSUE THREAD

**Issue by elphazesedah** [section-engineering-education/engineering-education#7331]
#### Proposed article introduction

MetaMask is an extension for accessing Ethereum enabled distributed applications in our browsers.
The extension injects the Ethereum web3 API into every website's javascript context, so that dapps
can read from the blockchain. MetaMask also lets the user create and manage their own identities, so when a Dapp wants to perform a transaction and write to the blockchain, the user gets a secure interface to review the transaction, before approving or rejecting it.
This helps in creation of more secure login pages for php programmers ensuring proper verification of users.

In this tutorial ill be discussing how to set up Metamask in your machine, i will then go ahead to give a step by step explanation of creating a Metamask login for web applications using php programming language.
#### Key takeaways 
1. The reader will understand what Metamask login is in web creation.
2. The reader will be able to understand how to set up and configure Metamask in preparation of the login creation.
3. The reader will be able to learn how to create a Metamask login in web applications using php programming language.

#### Article quality
How is your article unique? Tell us what makes your approach different from similar articles that have published on the same topic?
Is yours more in-depth? Does it cover additional topics? Do you provide handy tips or anecdotal advice?

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Really like the idea - how can we take it further ?? @elphazesedah  

cc: @ahmadmardeni1 

- 

Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

**Comment by hectorkambow** [comment]
https://www.google.com/search?q=Creating+Metamask+logins+for+PHP+based+websites&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
