### ISSUE TITLE
How To Use Python In Improving Healthcare Data Analysis And Prognosis

### ISSUE THREAD

**Issue by SandersonNyange** [section-engineering-education/engineering-education#7333]
**Proposed title of the article**
HOW TO USE PYTHON IN IMPROVING HEALTHCARE DATA ANALYSIS AND PROGNOSIS

**Proposed article introduction**
Health is very essential for every living thing on Earth. For many years we have seen deadly and chronic diseases affecting people around the globe. These diseases end up taking away many lives which impact families negatively in the long run. The ability to predict diseases has been there for a couple of years but has not been effective enough. My idea will incorporate the use of Python algorithms to analyze data for a while and predict diseases that are likely to occur. This will also be made possible by studying patterns of diseases.
Python has been used in various industries to help improve day-to-day operations. Python is an easy-to-learn programming language known for its flexibility and support vast of libraries.
In this article, we are going to learn how to use python and its various libraries to help improve the healthcare sector data analysis and medical diagnostics. We will learn further on the use of python in predictive prognosis. 

**Key Takeaways**
At the end of this article, the learner will:
•	Be in a position to write python algorithms.
•	Be in a position to use python libraries (In this case, the learner will be able to know how to use PyHealth).
•	Be able to know how to study patterns of diseases.
This article will help the health sector in the following ways:
•	Be able to use Python algorithms in data analysis of diseases and study patterns of diseases.
•	Be able to use Python algorithms in the predictive prognosis of diseases.
•	Be able to diagnose diseases in a fast and accurate manner through the use of python.

**Article Quality**
This will be a step-by-step and beginner-friendly tutorial guide that will cover the use of python programming language in data analysis, prognosis, and better improved medical diagnosis of diseases.

**References**
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?
https://www.google.com/search?q=Improving+Healthcare+Data+Analysis+And+Prognosis+with+Python&rlz=1C1CHBF_enUS891US891&ei=MmxHYumnErPE0PEP5c2MkAU&ved=0ahUKEwjpiMqV5fP2AhUzIjQIHeUmA1IQ4dUDCA4&uact=5&oq=Improving+Healthcare+Data+Analysis+And+Prognosis+with+Python&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKABOgQIABBHOgUIIRCrAjoHCCEQChCgAUoECEEYAEoECEYYAFDMCFiBI2CrKGgCcAJ4AoABoAGIAbIMkgEEMC4xMpgBAKABAcgBCMABAQ&sclient=gws-wiz
