### ISSUE TITLE
Chatbot in online shopping and the impact on the marketing industry

### ISSUE THREAD

**Issue by Geo-ogy** [section-engineering-education/engineering-education#7334]
**Proposed article introduction**
A chatbot is an AI software application that can interact with people in real-time either through speech or text. As of today, chatbots are used in most applications such as WhatsApp and Telegram. I would like to introduce this feature on online shopping to showcase the impact it would make on the marketing industry.
Most people make their purchases online but lack the means to request more services, they only get this chance through questionnaires that cover a few people.
By introducing chatbots more people will have the chance to interact with the website. This cubs the use of questionnaire since it supports real-time responses compared to the questionnaire, and the requirements are the app only. Also when a customer tries to buy an item that isn’t available instead of looking for another source or alternative he/she can make inquiries through the chatbot. On the other hand, the business tends to gain new ideas to add to make their business more profitable. These are just a few benefits, I intend to cover more in the article.

**Key takeaways**
•	I’ll cover the benefits of a chatbot in the online shopping and marketing industry.
•	I’ll cover challenges that may arise and provide their solutions.
•	After going through the article one will get to know more about the chatbot and its impact on the marketing industry and online shopping.

**Quality of the article**
This article will help one get to know more about chatbots mainly in online shopping, the impact, and their various uses in the marketing industry. Also one can get ideas on various areas they can implement the chatbot.

**References**
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=Chatbot+in+online+shopping+impact&rlz=1C1CHBF_enUS891US891&ei=ZGxHYqjkB_LZ0PEPnq-I0AU&ved=0ahUKEwiopqut5fP2AhXyLDQIHZ4XAloQ4dUDCA4&uact=5&oq=Chatbot+in+online+shopping+impact&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKABOgcIABBHELADOgYIABAWEB46BQgAEIYDOggIIRAWEB0QHkoECEEYAEoECEYYAFC8AljzDmCxEGgBcAF4AIAB3QSIAZ0JkgEHMS40LjUtMZgBAKABAcgBCMABAQ&sclient=gws-wiz

**Comment by Geo-ogy** [comment]
Thank you, I have gone through the link but some features haven't been covered I intend to talk more about those features.
In my article I intend to add more features to the chatbot like if a customer trys to buy an item that is depleted he/she would be given alternative products to choose or the time the product of his choice might be available, once the product is available the customer is notified. Else if the customer buys a product that wasn't initially in the website, it sends a request to management giving them the customer details ad and the product of their choice after coming to terms when they want the product. The chatbot can check market trends and give the customer the estimated price of the product. These are some features which are not covered in most blogs and I tend to cover more in my article
