### ISSUE TITLE
 likelihood function in hospital dynamics using R programming

### ISSUE THREAD

**Issue by Natel254** [section-engineering-education/engineering-education#7336]
### Topic Suggestion
 likelihood function analysis in hospital dynamics using R

#### Proposed title of article
 likelihood function in hospital dynamics using R programming
#### Proposed article introduction
This article is based on problem  affecting people who are in the hospital for ailments .
We review statistical methods for analysing healthcare resource use and costs, their ability to address skewness, excess zeros, multimodality and heavy right tails, and their ease for general use. We aim to provide guidance on analysing resource use and costs focusing on randomised trials, although methods often have wider applicability. 

#### Key takeaways 
-Why should I use Maximum Likelihood Estimation (MLE)?
    -Understanding MLE with an example
   - Getting to know the technical details
       - Distribution Parameters
       - Likelihood
       - Log Likelihood
        -Maximizing the Likelihood
   - Determining model coefficients using MLE in R
   - Technical team in Hospitals conveying its findings to legal team
    

#### References
NA

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

**Comment by hectorkambow** [comment]
Sounds like a helpful topic - lets please be sure it adds value beyond what is in any official docs and/or what is covered in other blog sites. (the articles should go beyond a basic explanation - and it is always best to reference any EngEd article and build upon it).

Please be attentive to grammar/readability and make sure that you put your article through a thorough editing review prior to submitting for final approval. (There are some great free tools that we reference in EngEd resources.)
ANY ARTICLE SUBMITTED WITH GLARING ERRORS WILL BE IMMEDIATELY CLOSED.
Please be sure to double check that it does not overlap with any existing EngEd articles, articles on other blog sites, or any incoming EngEd topic suggestions (if you haven't already) to avoid any potential article closure, please reference any relevant EngEd articles in yours. - Approved


cc: @section-engineering-education/content-moderator-team  - let me know if Im missing something.
