### ISSUE TITLE
 Writing test in Laravel 8  & using the null safe operator

### ISSUE THREAD

**Issue by AbdullahiAbdulkabir** [section-engineering-education/engineering-education#7338]
### Writing sample(s): 
[Laravel on subdomain](https://link.medium.com/LTQL1ECiemb) 

#### Proposed title of article

Writing test in Laravel 8  & using the null safe operator

Use keyword research to improve your article's SEO.

#### Proposed article introduction
In these article, I will be discussing how to write laravel test. Larevel is a popular PHP framework (web). Alot of people find it quite hard to write test for there codebase. I will be setting up a basic CRUD application and write test in them. While writing the CRUD application, I will be discussing about a new php 8 feature called null safe operator.

I will also use GitHub actions to run test on each PR/push to GitHub.

#### Key takeaways 
Setting up Laravel Sanctum
Setting up Laravel test
Use the new null safe operator in php 8 in Laravel.
Basic GitHub actions

#### Article quality
The article is intended to be clear and precise. It is meant to be practical with illustration and code snippet. Many online articles doesn't explain with snippet and don't really explain the full indept of Laravel test and use GitHub actions. I will also discuss the null safe operator

#### References
[PHP 8](https://php.watch/versions/8.0/null-safe-operator) 
[Laravel](https://laravel.com/docs/8.x/) 

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?
https://www.google.com/search?q=Laravel+8+%26+using+the+null+safe+operator&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
