### ISSUE TITLE
Understanding password encryption in python utilizing Bcrypt

### ISSUE THREAD

**Issue by Kushies02** [section-engineering-education/engineering-education#7343]
### Topic Suggestion
Understanding password encryption in python utilizing Bcrypt
#### Proposed title of article
Understanding password encryption in python utilizing Bcrypt
#### Proposed article introduction
The process of scrambling a readable text so that it can only be understood by the person with the decryption key is called `encryption`. It is utilized by government, businesses, military and much more to safeguard the integrity of the information exchanged. Password encryption is also applied in database systems to secure user information, encrypting a database systems ensures that the database systems is not compromised by hackers and unauthorized personnel's.
Bcrypt is a function used for encrypting passwords and data. It was developed by Niels Provos and David Mazieres, and its supported by Python, csharp, C++, PHP, Java and many other programing languages.

#### Key takeaways 
- Password encryption jargons.
- Understanding bcrypt.
- Performing password encryption using bcrypt in python.
- Merits and Demerits of Password encryption.
#### Article quality
In this article am going to introduce the user to password encryption in python utilizing the bcrypt function, am also going to show the reader how password encryption is done in python utilizing bcrypt function. Am also going to use beginer friendly language in content delivery to ensure the user understands the concept.
#### References
https://pypi.org/project/bcrypt/

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=password+encryption+in+python+utilizing+Bcrypt&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
