### ISSUE TITLE
[Containers] Setting up a Real Spring Boot Application with Real MongoDB Instance for Production

### ISSUE THREAD

**Issue by sammobola** [section-engineering-education/engineering-education#7351]
### Topic Suggestion
[Containers] Setting up a Real Spring Boot Application with Real MongoDB Instance for Production

### Writing sample(s): 
Include any links or writing samples - to help our team better gauge your writing quality.

#### Proposed title of article
[Containers] Setting up a Real Spring Boot Application with Real MongoDB Instance for Production

#### Proposed article introduction
In this article I will be describing a first-hand, gruesome experience I had connecting my project to a real-life MongoDB provision. At first glance, it seemed like a walk in the park. But then, after three hours of fighting it and overcoming, I thought it was best to share this knowledge with other growing developers.

This tutorial will involve working with a real project that requires MongoDB for concerns of stability and scalability. We would first get over to the Mongo page, get registered and settled, do a few smooth configurations and selections, pick up a URL and then head over to our IDE to set up a java-based project with Spring Boot. This would be useful as it would lead directly to accomplishemnt.

#### Key takeaways 
At the end, readers will be able to:
- Self-provision a MongoDB database instance is much reduced time
- Connect this provision database instance to a real-life Spring Boot project
- Understand the inner demands and text structure of MongoDB Atlas password syntax

#### Article quality
This article is a three-stage explanation of what it takes to go from a local database to a production instance of the database storage

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=Real+Spring+Boot+Application+with+Real+MongoDB+Instance+for+Production&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8

**Comment by sammobola** [comment]
@hectorkambow Thank you for your work for us.
I have carefully looked at the links in the search result for the link you pasted in the issue closed. You will find out that NONE OF THEM TALKS ABOUT MONGODB IN PRODUCTION. 

I already knew there were articles aplenty for Spring Boot and MongoDB using local configurations. But the production configuration requires a lot of steps and sign-ups which is what I will be talking about. None of the articles in the results talks about it this way. 

By far, I can say that this is a unique article and will meet demands of a growing community. Thank you very much 

@hectorkambow @Kayere

**Comment by sammobola** [comment]
> @hectorkambow Thank you for your work for us. I have carefully looked at the links in the search result for the link you pasted in the issue closed. You will find out that NONE OF THEM TALKS ABOUT MONGODB IN PRODUCTION.
> 
> I already knew there were articles aplenty for Spring Boot and MongoDB using local configurations. But the production configuration requires a lot of steps and sign-ups which is what I will be talking about. None of the articles in the results talks about it this way.
> 
> By far, I can say that this is a unique article and will meet demands of a growing community. Thank you very much
> 
> @hectorkambow @Kayere

@hectorkambow Could you please have a look at this? Thank you
