### ISSUE TITLE
How to use StateNotifier and AsyncValue in Flutter to handle loading and error states

### ISSUE THREAD

**Issue by MICHELLENGEI** [section-engineering-education/engineering-education#7355]
### Topic Suggestion
How to use StateNotifier and AsyncValue in Flutter to handle loading and error states.

#### Proposed article introduction
A StateNotifier is an observable class that stores a single immutable state.  Using it as a drop-in replacement for ChangeNotifier or other analogous objects such as Bloc is a viable option. Its uniqueness lies in the fact that it strives to be simple while still promoting immutable data. By utilizing immutable state, it becomes significantly easier to compare prior and new state, to construct an undo-redo mechanism, and to debug the application's state.
Applications that conduct some asynchronous work are frequently plagued with loading and error states. If we fail to provide a loading or error UI when it is necessary, users may believe that the app is not functioning properly and will be unable to determine whether the operation they are doing has been completed. In this article we will be looking at how we can use StateNotifier and AsyncValue to handle the loading and error states that might occur.

#### Key takeaways 
1. Introduction to StateNotifier and AsyncValue.
2. Using StatefulWidget for loading and error states.
3. Using AsyncValue and  StateNotifier subclass to handle loading and error states.
4. Using Dart extensions.

#### Article quality
The article will give the reader a detailed explanation of how to use StateNotifiers and Asyncvalues to handle loading and error states using well explained code snippets.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=StateNotifier+and+AsyncValue+in+Flutter&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8

**Comment by MICHELLENGEI** [comment]
Hey @hectorkambow  I have taken a look at the existing articles and my article talks about 4 ways of handling loading and error states and  using dart extensions and StatefulWidget are the two unique aspects of the article.
Thank you
