### ISSUE TITLE
[Security ]Using Least Privilege To Secure Embedded Software

### ISSUE THREAD

**Issue by BridgetMwikali** [section-engineering-education/engineering-education#7356]
#### Proposed title of article
Your title should be descriptive of the article/tutorial. Be Specific. 

Using Least Privilege To Secure Embedded Software
#### Proposed article introduction
The Principle of Least Privilege (PoLP) is used for securing servers, software, and services. The idea is that applications run with only the privileges they need to operate. If a service doesn't need the ability to modify files on your system, it shouldn't have that privilege. This allows the attacker to only gain access to those privileges needed by something executing on your server, making it much harder to exploit vulnerabilities in any given service. 

Secure embedded systems must be built with security in mind and the Principle of Least Privilege is fundamental to this effort.

#### Key takeaways 

1. What is the Principle of Least Privilege?
2. Embedded software vulnerabilities
3. Why is the Principle of Least Privilege important in embedded software security?
4. Applying the Principle of Least Privilege to Embedded Software

#### Article quality
This article digs deep into why the Principle of Least Privilege is specifically applicable to the security of embedded software. 

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=Least+Privilege+To+Secure+Embedded+Software&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
