### ISSUE TITLE
How to Write API Software Documentation

### ISSUE THREAD

**Issue by corpsgeek** [section-engineering-education/engineering-education#7367]
### Topic Suggestion
How to Write API Software Documentation

### Writing sample(s): 
- https://www.section.io/engineering-education/an-introduction-to-blockchain-architecture/
- https://www.section.io/engineering-education/an-introduction-to-defi/

#### Proposed title of article
How to Write API Software Documentation

#### Proposed article introduction
[API] An API allows a different software applications to interact with each other to exchange data in a reliable way. The developers aiming to implement certain functionality of another application require documentation to guide them through the use of such API, and as a result, there is a need to write great, clear, and concise software documentation for other developers to reference in implementing existing functionalities.

#### Key takeaways 
- What is an API
- How does an API Work
- How to Structure and Write API Documentation   

#### Article quality
This article is unique from the existing article because it aims to provide a structural framework for writing API documentation that can easily be referenced by every Technical Writer building API documentation. It will serve as a concise guide from framework to practical implementation and software tools to use in rapidly generating API documentation.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

**Comment by hectorkambow** [comment]
https://www.google.com/search?q=How+to+Write+API+Software+Documentation&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
