### ISSUE TITLE
Why SQL is a Great Choice for Time Series Analytics

### ISSUE THREAD

**Issue by LeahKui** [section-engineering-education/engineering-education#7380]
### Topic Suggestion
Why SQL is a Great Choice for Time Series Analytics

#### Proposed title of article
Why SQL is a Great Choice for Time Series Analytics

#### Proposed article introduction
Time series analysis is indexing data points by time. It’s useful for any set of data organized by time. Working with time-series data using SQL is critical, especially when working with very big datasets or regularly updated data. 
SQL Server contains a powerful range of capabilities to prepare, aggregate, and query time series data. In this article, readers will understand how SQL query language can be used to understand time series analysis effectively.

#### Key takeaways 
1. Introduce reader to time series analytics briefly
2. Why use SQL for time series analytics
-  How can SQL store time series data?
-  The article will give use cases or situations where SQL is good for time series analytics
3.  Why is SQL a good choice for time weighted averages, and how can it be used effectively?
4.  Useful SQL functions and tools
- LATEST BY
- SAMPLE BY
- Timestamp Search
- Timestamp columns
- Aggregate functions

#### Article quality
This is a well-detailed article about Using SQL with time-series analytics. The article will be straight to the point and unique as this content is not widely published by other sources.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=SQL+is+a+Great+Choice+for+Time+Series+Analytics&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
