### ISSUE TITLE
How to use lazy row and lazy column in jetpack compose as an alternative to recycler view

### ISSUE THREAD

**Issue by judywambaki** [section-engineering-education/engineering-education#7383]
### Topic Suggestion
How to use lazy row and lazy column in jetpack compose as an alternative to recycler view

#### Proposed article introduction
Following the improvements in the android development space, jetpack compose has brought about the easier designing of UI. It involves the use of lesser codes compared to using XML in designs which involves writing a bunch of lines of codes for a particular element such as when implementing a recycler view. An alternative way to implement displaying items in a recycler view is by use of a lazy column and a lazy row which is only possible in jetpack compose. Lazy column and lazy row involves only using a composable view item and displaying several items in a lazy column. Compared to the recycler view, we have to use XMLs, adaptors, and view holders which involves writing more codes in general.

In this tutorial, we will discuss displaying mutable list items using lazy rows and lazy columns in jetpack compose. 

#### Key takeaways 
- Introduction to lazy composable in jetpack compose
- Setting up the project
- Writing Kotlin code
- Running the application
- Conclusion

#### Article quality
In this tutorial, we will showcase the use of lazy composable in jetpack compose. We will go-ahead to use chips to display the list of items in the lazy row and we design the lazy column to display items in cards.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=lazy+row+and+lazy+column+in+jetpack+compose+as+an+alternative+to+recycler+view&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
