### ISSUE TITLE
[Android]Getting Started with Paparazzi in Android

### ISSUE THREAD

**Issue by phenny001** [section-engineering-education/engineering-education#7387]
Getting Started with Paparazzi in Android

#### Introduction
When developing (or attempting to write) shippable code, the most crucial thing a developer should worry about is testing. Testing, no matter how vital it is, may be intrinsically challenging at times. This is especially true with Android UI frameworks, where unit testing and UI testing (using Espresso, UiAutomator) become less useful.

This is another snapshot testing library, however unlike other solutions currently available, it operates entirely on the JVM without the use of a device or emulation.

#### Key takeaways 
- What is Paparazzi
- Importance of using Paparazzi
- Pron and Cons of Paparazzi
- How to write several tests using Paparazzi 

#### Article quality
Looking through the various blogs and articles, it appears that most of them are concerned with building tests, including the recording procedure and even how to utilize paparazzi to generate an application. This lesson focuses on how to do various tests such as `LaunchView`,`KeypadView`, and many more. It also discusses the benefits and drawbacks of utilizing paparazzi, as well as the necessity of paparazzi in Android applications.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=paparazzi+in+android+tutorial&rlz=1C1CHBF_enUS891US891&ei=1DdKYpmMJryU0PEPt-C-gA0&oq=Paparazzi+in+Android+tuto&gs_lcp=Cgdnd3Mtd2l6EAMYADIFCCEQoAEyBQghEKsCOgcIABBHELADOgYIABAWEB46BQgAEIYDOggIIRAWEB0QHkoECEEYAEoECEYYAFDZAVjIHGCzImgEcAF4AIABa4gBqASSAQM1LjGYAQCgAQHIAQjAAQE&sclient=gws-wiz
