### ISSUE TITLE
Using NLTK for tokenization

### ISSUE THREAD

**Issue by oleey** [section-engineering-education/engineering-education#7390]
#### Proposed title of article
Using NLTK for tokenisation (a data preprocessing method)

#### Proposed article introduction
Tokenisation is a data preprocessing method that involves dividing text- data into a set of meaningful pieces depending on the task at hand. These pieces are called tokens. NLTK (Natural Language Toollkit) is a natural language processing tool written in python programming language that provides libraries for sentence and word tokenisation.

#### Key takeaways 
Readers will be able to install NLTK on various operating systems
Readers will be able to download datasets that NLTK provides
Readers will be able to tokenize text data
Readers will be informed on other things to use tokenized data for

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?
https://www.google.com/search?q=NLTK+for+tokenization&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8

**Comment by oleey** [comment]
####Alternate proposed title of article
Permissioned blockchain based databases

#### Proposed article introduction
The most common blockchain based databases are the permissionless blockchain based databases. General implementation of a permissioned blockchain solution is a tough one which is why most people leverage on the permissionless part of blockchain. 


#### Key takeaways 
Readers will be able to understand general blockchain based databases
Readers will be able to differentiate between permissioned and permissionless blockchain based databases
Readers will be able to differentiate between traditional databases and permissioned blockchain databases
Readers will be able to choose the right permissioned blockchain database for a particular solution
A list of permissioned blockchain databases will be stated

#### Conclusion
At the end of this article, blockchain enthusiasts will be able to understand the general blockchain concept and then differentiate between permissioned blockchain databases and permissionless blockchain databases
