### ISSUE TITLE
[Security]A Quickstart to GraphQL Data Security

### ISSUE THREAD

**Issue by Frankline012** [section-engineering-education/engineering-education#7391]
#### Proposed title of article

A Quickstart to GraphQL Data Security

#### Proposed article introduction

* GraphQL has been adopted by the biggest platforms out there such as Facebook, Twitter, Github, Pinterest and Walmart. But even though GraphQL can be a very secure option for your API, it does not come secure out of the box. It’s actually quite the opposite because all doors are open even for the most novice hackers. The primary categories of attacks that you must absolutely protect your application from are:
1. access control
2. brute-force attacks
3. DoS (Denial of Service)
4. injections (SQL, XSS, CCS, etc)
5. CSRF 

#### Key takeaways 

* Introspection Query
* Limit Access control with Authorization and Authentication
* Timeout
* Query Whitelisting
* Depth Limiting
* Resource Limitations with Complexity Analysis
*  Rate Limiting to block Brute Force attacks
* Verbose Errors
*  Injections
* POST vs GET requests

#### Article quality

* This article will be on point, simple to understand, well formatted and I'm sure users will be able to familiarize themselves with the attack vectors for GraphQL APIs and strategies to adopt to protect the APIs. The code snippets in this article will be simple to understand and implement. I hope we will have a good ride all along.

#### References

N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=GraphQL+Data+Security&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
