### ISSUE TITLE
Creating a Single Page Application (SPA) using React routes.

### ISSUE THREAD

**Issue by NMJD** [section-engineering-education/engineering-education#7394]
#### Proposed title of article
Creating a Single Page Application (SPA) using React routes.

#### Introduction:
Single page application become a trend in the web. Many big companies use it to build modern web apps.
In traditional web apps pages are reloaded everytime you navigate through the links. But with the coming of SPA, web pages load once and you can navigate without reloading anything.
Among the cutting-edge technologies that give the possibility of building SPA, reactjs is one of the best. With the concept of react routers you can easily create a SPA in no time.

To correctly grasp the concepts, we will build a little blog SPA through the tutorial. However the main point is not building a great app but understanding the implementation of the spa in the app.
This tutorial is a walkthrough towards a good understanding of what is a SPA and how to implement it with react routes. Please code along while following the tutorial to effectively understand the concepts..

#### Key takeaways:
At the end of this tutorial you will understand:

- What is a SPA
- How to use react routes
- How to manage the links in react

### References:
https://reactrouter.com/web/api/Link
https://www.pluralsight.com/guides/understanding-links-in-reactjs

#### Templates to use as guides
[Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=Single+Page+Application+(SPA)+using+React+routes&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
