### ISSUE TITLE
[Languages]Implementing Data Streams in Flutter and Dart

### ISSUE THREAD

**Issue by Eze4Manuel** [section-engineering-education/engineering-education#7397]
#### Proposed title of article
[Languages]Implementing Data Streams in Flutter and Dart.

### Writing sample(s): 
https://www.section.io/engineering-education/advanced-concepts-of-programming-using-dart/
https://www.section.io/engineering-education/testing-angular-app-with-protractor-and-jasmine/
https://www.section.io/engineering-education/flutter_speech_recognition_using_alan_voice/

 
 
#### Proposed article introduction
 Dart has implementations for streams. This listens/emits bits or chunks of data. Such streams can be used to process continuous data supply, which, if read synchronously, can cause your application to suffer functionally. Such streams have intrinsic methods that enable performing complex functionality easily.

#### Key takeaways 
- How to implement streams in flutter and dart with hands-on coding examples.
- Have knowledge of the possible methods that are present in dart streams
- Know how to create, subscribe, broadcast, and listen to streams while handling errors gracefully.

#### Article quality
This article is more detailed, exposes built-in methods used by dart streams, and does so with coding samples for users to reference
 
#### References
https://dart.dev/tutorials/language/streams

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?


https://www.google.com/search?q=Data+Streams+in+Flutter+and+Dart&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
