### ISSUE TITLE
How to implement ML Kit text recognition v2 API using jetpack compose

### ISSUE THREAD

**Issue by carolinenji** [section-engineering-education/engineering-education#7400]
### Topic Suggestion
 How to implement ML Kit text recognition v2 API using jetpack compose

#### Proposed article introduction
Machine learning enables software systems to become increasingly accurate at predicting outcomes without being explicitly planned.
ML Kit text recognition is an API that is developed to recognize text written on any surface and sends the data to a dedicated destination. It has also the ability to recognize any text that is written in a different Latin language and is difficult to be recorded. ML Kit is preferred to be integrated into mobile applications due to its ability to reduce labor and time used to do manual data input to a record. It works hand in hand with the CameraX library to scan the surfaces and extract texts from the surfaces. The major applications of the API are processing credit cards and extracting business card details. ML Kit text recognition has also played a major role in helping the visually impaired who can't see what is written on a surface.

In this tutorial, we will be using ML Kit text recognition API to build an application using Jetpack compose in android studio. The application will be extracting text from surfaces that have text written in languages supported by the API and can share the extracted text data with other applications.

#### Key takeaways 
- Brief walkthrough of the ML Kit text recognition API
- Implementing the MLKit text recognition API in the android app
- Conclusion

#### Article quality
This article will showcase the use of the CameraX library to snap surfaces and use the text recognition API to extract the writings on the surface. This article will be unique from other blogs and will use simple composes that will be beginner-friendly, easy to understand, and integrate the API in their applications.

#### References
N/A

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=ML+Kit+text+recognition+v2+API+using+jetpack+compose&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
