### ISSUE TITLE
A Complete on how to Set Up and Implement Scroll to Position in Android Applications

### ISSUE THREAD

**Issue by JuliusGikonyoNyambura** [section-engineering-education/engineering-education#7405]
#### Proposed title of article

A Complete on how to Set Up and Implement Scroll to Position in Android Applications 

#### Proposed article introduction

Android has many features that allow you to build and implement different sets up based on your application setup. In many cases, an application can have an overview that displays major components. In this case, the application has a long list of these components implemented in the application. In such a case, it would be appropriate to detect the user to scroll to different sections of the components displayed in the app.

This can be implemented in the android studio, where you can add features to scroll to Scroll to Position. This android feature allows users to access the application content with a single click. Instead of the user manually scrolling down a long list of items. You can add scroll to the position that will enable the user to scroll the different selected and important sections on your application. This will automatically scroll down the application screen and direct the user to that specif section that you have specified in your application. This tutorial will help the reader set up and implement scroll to position in android applications. Below is some of the topic that the tutorial will cover:

#### Key takeaways 

- What is the scroll to position in android
- Why a developer should implement the scroll to position
- When is scroll to position applicable
- Set up the android studio basic application
- Build a View app  with content
- Set up the UI screen
- Set a location master model
- Add a Scroll Position Listener
- Inflate the created content in the MainActivity screen
- Add Smooth Scroll
- Examine the built android application

#### Article quality

The reader will understand the concept of Scroll to Position in Android. The tutorial will also build a complete application that will guide the reader on how to effectively implement the Scroll to Position in Android applications.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquoted notes as you fill in the form before you submit.
We look forwarding to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?


https://www.google.com/search?q=Set+Up+and+Implement+Scroll+to+Position+in+Android+Applications&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
