### ISSUE TITLE
How to Import From Your Local PostgreSQL Database into a Heroku PostgreSQL Database

### ISSUE THREAD

**Issue by ehizman** [section-engineering-education/engineering-education#7409]
#### Proposed title of the article
How to Import From Your Local PostgreSQL Database into a Heroku PostgreSQL Database

#### Proposed article introduction
Oftentimes, you will need to migrate data from one [PostgreSQL](https://www.postgresql.org) database to another. The Heroku [PG Backups](https://devcenter.heroku.com/articles/heroku-postgres-backups) tool that you can use to export to
and import from external PostgreSQL databases.

In completing this post, readers will learn how to use the PG Backup tool to import data from your local PostgreSQL database
to your Heroku PostgreSQL database.

In this tutorial we will cover:
1. A brief explanation of the Dumping database backup technique.
2. How to create dump files.
3. How to create a new AWS(Amazon Web Services) s3 bucket.
3. How to upload dump files into an AWS s3 bucket.
4. How to create signed URLs to an AWS s3 bucket.
5. How to import data into a Heroku PostgreSQL Database from a dump file in an s3 bucket.

#### Key takeaways
At the end of this tutorial, the reader should:
1. Understand dumping and should know how to create a dump file.
2. Know how to create an AWS s3 bucket and how to upload it into an s3 bucket.
3. Know how to import data from an s3 bucket into a Heroku PostgreSQL Database.

#### Article quality
In creating new applications, we oftentimes want to migrate data from our local database to a cloud database. This article provides 
extensive coverage of how to do this. The article is inspired by the author's challenge with importing data into a cloud database.
The article offers a simplified guide to readers and is fitted with screenshots that provide visual help for each step of the process.

#### References
- https://stackoverflow.com/questions/6842393/import-sql-dump-into-postgresql-database
- https://devcenter.heroku.com/articles/heroku-postgres-import-export#import
- https://stackoverflow.com/questions/55681397/heroku-missing-required-flag-when-restoring-database

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=Import+Local+PostgreSQL+Database+into+a+Heroku+PostgreSQL+Database&rlz=1C1CHBF_enUS891US891&ei=WUtPYuWHBOH99APU4p6QBA&ved=0ahUKEwilmN_75oL3AhXhPn0KHVSxB0IQ4dUDCA4&uact=5&oq=Import+Local+PostgreSQL+Database+into+a+Heroku+PostgreSQL+Database&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABKBAhGGABQ6AdY6xJgkxVoAnABeACAAV-IAd4DkgEBNpgBAKABAcgBCMABAQ&sclient=gws-wiz
