### ISSUE TITLE
[languages] JQuery Datepicker

### ISSUE THREAD

**Issue by Emusugut** [section-engineering-education/engineering-education#7412]
#### Introduction
Datepickers in jQueryUI make it simple for users to input dates graphically. Users can simply change the date formatting and language, limit the date range that may be selected, and add other navigation button options. The Datepicker is commonly used in conjunction with a text box. It can easily shift the specified date from the calendar to the text box.
This article will contain examples of how jQuery Datepicker is implemented. It will also show how to interlock two Datepickers and finally a clear step by step process of adding Datepickers to MVC. 

#### Key takeaways 
At the end of this tutorial the reader should be able to understand the following:
1. How to implement jQuery Datepicker
2. Interlocking two Datepickers
3. Add Datepickers in MVC

#### Article quality
The article will contain unique and original information about jQuery Datepickers. The language I will use will be simple in order to enhance understanding for anyone reading it.

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?


https://www.google.com/search?q=JQuery+Datepicker&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8
