### ISSUE TITLE
[Languages] How to create a JSON Object as a dynamic response with JSONArray and JSONObject in Java

### ISSUE THREAD

**Issue by neeshegz** [section-engineering-education/engineering-education#7418]
### Topic Suggestion
[Languages] How to create a JSON Object as a dynamic response with JSONArray and JSONObject in Java

#### Proposed title of article
[Languages] How to create a JSON Object as a dynamic response with JSONArray and JSONObject in Java

Use keyword research to improve your article's SEO.

#### Proposed article introduction
Generally, it is said that responses are best generated from the backend for the frontend in JSON format i.e. as an object. This is regardless of what is being passed; lists, objects, lists of objects etc.

In this tutorial, we wil build a small project and generate a response on the fly in jJSON format regardless of whatthe frontend wants and how it wants it.

#### Key takeaways 
What are the 3-5 most important things the reader should understand or be able to do after reading this article?
Use this area to get your ideas down on the bulk of your article or tutorial.

- Understand the dependencies for performing the dynamic response creation action
- Be able to implement dynamic response in JSON format
- Understand the classes JSONArray and JSONObject and their core functionalities

#### Article quality
This is be a useful project for simplifying work for frontend engineers. It combines libraries to bring a solution to an actual challenge

**Comment by hectorkambow** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program. 

After some careful consideration it struck us that this topic may be a bit over saturated throughout other blog sites and official documentations. We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts. 

But in order to approve the topic it has to serve value to the larger developer community at large. Please feel free to suggest an alternate topic to explore. 🚀 
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project. 

If you believe your article is unique enough - please present your case to explain how it will be different from what is currently out there?

https://www.google.com/search?q=How+to+create+a+JSON+Object+as+a+dynamic+response+with+JSONArray+and+JSONObject+in+Java&rlz=1C1CHBF_enUS891US891&sourceid=chrome&ie=UTF-8

**Comment by teevyne** [comment]
@hectorkambow 
These links are not the same as what you have pointed in the links. There are either a stackoverflow response, which is not the same as explaining via an article (assuming we are pointing in the same direction of answers) or an article that talks about something different. I checked one of them. The author is focused on Jackson as a library, while I am focused on generating responses after consuming an API using another library entirely

My article is and will be unique from the ones in your search results

Please reopen the issue. Thank you

**Comment by neeshegz** [comment]
@hectorkambow
These links are not the same as what you have pointed in the links. There are either a stackoverflow response, which is not the same as explaining via an article (assuming we are pointing in the same direction of answers) or an article that talks about something different. I checked one of them. The author is focused on Jackson as a library, while I am focused on generating responses after consuming an API using another library entirely

My article is and will be unique from the ones in your search results

Please reopen the issue. Thank you
