### ISSUE TITLE
[Machine Learning] Building a Deep learning model with Keras and ResNet-50

### ISSUE THREAD

**Issue by charles721** [section-engineering-education/engineering-education#7419]
#### Proposed title of the article
[Machine Learning] Building a Deep learning model with Keras and ResNet-50

#### Proposed article introduction
Deep learning has gained massive popularity in scientific computing, and its algorithms are widely used by industries that solve complex problems. All deep learning algorithms use different types of neural networks to perform specific tasks. 

Deep learning uses artificial neural networks to perform sophisticated computations on large amounts of data. It is a type of machine learning] that works based on the structure and function of the human brain.  Deep learning algorithms train machines by learning from examples. Industries such as health care, eCommerce, entertainment, and advertising commonly use deep learning. During the training process, algorithms use unknown elements in the input distribution to extract features, group objects and discover useful data patterns.

Deep-learning architectures such as deep neural networks, deep belief networks, deep reinforcement learning, recurrent neural networks, and convolutional neural networks are applied to fields including computer vision, speech recognition, natural language processing, and machine translation. In this tutorial, we will implement the deep learning model with Keras and ResNet-50.

ResNet-50 is a pre-trained convolutional neural network that is 50 layers deep. You can load a pre-trained version of the network trained on more than a million images from the ImageNet database. The pretrained network can classify images into 1000 object categories, such as keyboard, mouse, pencil, and many animals. We will use Keras to fine-tune the deep neural network and add other additional layers.

#### Key takeaways 
1. Types of  models used in Deep Learning
2. What Is ResNet-50?
3. The Importance Of ResNet-50 in Computer Vision
4. How Residual Networks work – ResNet-50 Architecture
5. ResNet50 With Keras
6. Import pre-trained ResNet50 Model
7. Fine-tuning the pre-trained model with Keras.
8. Model evaluation and making predictions.

#### Article quality
In this article, we will explain the concepts of deep learning in detail. We will discuss all the types of models used in Deep Learning before focusing on Keras and ResNet-50. We will explain the how ResNet-50 model works and its architecture. We will explore all the layers of the ResNet-50 so that the reader can know how all the layers are assembled to form the final model. We will then import the ResNet-50 model and fine-tune it using Keras to perform image classification. We will use Keras to add the layers the model requires and the tutorial will be easy to follow.

#### References
Please list links to any published content/research that you intend to use to support/guide this article.

### Conclusion
Finally, remove the Pre-Submission advice section and all our blockquote notes as you fill in the form before you submit.
We look forward to reviewing your topic suggestion.

### Templates to use as guides
- [How To Guide Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/how-to-guide-template.md)
- [Software Review Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/software-review-template.md)
- [Tutorial Template](https://github.com/section-engineering-education/engineering-education/blob/master/new_contributors/tutorial-template.md)

**Comment by hectorkambow** [comment]
@lalith1403  

Might need your 👀  On this one

**Comment by lalith1403** [comment]
Good afternoon and thank you for submitting your topic to the EngEd program.
After some careful consideration, it struck us that this topic may be a bit over-saturated throughout other blog sites and official documentations.

We typically refrain from publishing content that is covered widely on the net or other blogs. We're more interested in original, practitioner-focused content that takes a deeper dive into programming-centric concepts.

But in order to approve the topic, it has to serve value to the larger developer community at large.
An option and a great way to write this as an in-depth article and make it more add value to the greater developer community at large would be to walk the reader through the USE of methods and functions by building a unique, different, useful project.

> We would love to learn your thought process behind the solution you arrived at using these concepts and topics.

That way a developer could see them in action.
As mentioned above - we believe this topic is widely covered on other blog sites.

The best way for students to build a great portfolio is by building what does not exist and what can provide the most value.
