### ISSUE TITLE
[Android] Uploading Text and Image data to Firebase Real-time database in Kotlin

### ISSUE THREAD

**Issue by Donel254** [section-engineering-education/engineering-education#7469]
### Writing sample(s): 
https://www.section.io/engineering-education/authors/donel-mwangi/
#### Proposed title of the article
[Android] Uploading Text and Image data to Firebase Real-time database in Kotlin
### Proposed article introduction
By combining both firebase storage and firebase realtime database, it is possible to store both image and and text data generated by users to firebase cloud storage. This can be accomplished by uploading the image data to firebase storage, then returning the image download link upon the successful image upload. The link is then uploaded along with the text data to the object that it belongs to.

We shall begin by creating a simple app that can select an image from a users gallery, then display it on their app. The user can then add a caption to go along with the image in order to create a post. Using a data class, we shall create a post object and upload it to firebase realtime database.

#### Key takeaways 
By the end of this tutorial the reader should be able to:
1. Integrate their app to firebase storage and realtime database.
2. Work with a kotlin dataclass
3. Create an image selector button, and display the selected image in their app
4. Upload the image to firebase storage and return the image link
5. Upload the text data along with the image link to firebase realtime databse

#### Article quality
There is a gap of kotlin tutorials that can demonstrate how to upload both image and text data to firebase realtime database. My article intends to fill that gap and also give a detailed explanation of the working.
#### References
https://firebase.google.com/docs/build

**Comment by LinusMuema** [comment]
Hi @Donel254 

Thank you for your article suggestion. 

It is a great article, however, we have doubts regarding the technical aspect of it. What your article covers in specific sections is covered as a whole article on other websites. For instance, uploading files to Cloud storage, it is well covered in the official docs as well as other articles but in your article, it's one of the key takeaways/sections. Which means your article will be a summary or will contain fragments of other articles that have covered the specifics in greater detail. 

Due to this we cannot move forward with your article. Please feel free to explore other options.
