### ISSUE TITLE
Comparison Between Unit Testing and Integration Testing

### ISSUE THREAD

**Issue by EssyH** [section-engineering-education/engineering-education#7472]
### Topic Suggestion
Comparison Between Unit Testing and Integration Testing

#### Proposed title of the article
Comparison Between Unit Testing and Integration Testing

#### Proposed article introduction
Many people instantly think of unit tests when they hear "automated testing." Unit testing is one of the most well-known types of automated tests, thus this is understandable. It isn't the only one, though. To mention a few, we have user interface testing, end-to-end testing, and load testing. This article focuses on two types of automated tests and how they connect to one another.

#### Key takeaways 
- Defining unit testing
- Integration test
- Unit testing rules
- Unit test vs. integration test: what’s the same, what’s different, when to use which
- Why isolation is good for unit testing?

#### Article quality
This is a more detailed article comparing Unit Testing and Integration Testing. The article's content is unique and it will contain simple grammar hence being beginner-friendly.

#### References
N/A

**Comment by LinusMuema** [comment]
Hi @EssyH 

Thanks for submitting your article suggestion. 

After a short google search, your article seems to have been covered widely over the net by sites like [GeeksForGeeks](https://www.geeksforgeeks.org/difference-between-unit-testing-and-integration-testing/). Due to this, we cannot move forward with your article as it will raise flags during plagiarism checks.

Please feel free to explore other options.
